# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: test-runs).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Any, Dict, List, Literal, Optional

from confidentai.api import Api, HttpMethods
from confidentai.common.types import ToolCall
from confidentai.endpoints import Endpoints
from confidentai.test_runs.types import (
    CreateTestRunRequest,
    SubmitTestCaseResultRequest,
    SubmittedTestCaseResult,
    TestRun,
    TestRunList,
    TestRunRef,
)


class TestRunsClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list_test_runs(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        sort_by: Optional[Literal["createdAt", "runDuration"]] = None,
        ascending: Optional[bool] = None,
        status: Optional[
            Literal["IN_PROGRESS", "COMPLETED", "ERRORED", "CANCELLED"]
        ] = None,
        multi_turn: Optional[bool] = None
    ) -> TestRunList:
        """List Test Runs

        Lists the test runs in your Confident AI project, newest first by
        default. Filter by `status`, `multiTurn` and the `start`/`end` window,
        sort with `sortBy` and `ascending`, and page with `page` and `pageSize`.
        Requires an active trial or paid plan.

        Args:
            page: The page of test runs to return. Defaults to 1.
            page_size: The number of test runs per page, at most 100. Defaults
                to 25.
            start: Returns only test runs created at or after this ISO 8601
                datetime. Defaults to 60 days ago.
            end: Returns only test runs created at or before this ISO 8601
                datetime. Defaults to now.
            sort_by: The field to sort by. Defaults to `createdAt`.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`.
            status: Returns only test runs with this status.
            multi_turn: When true, returns only multi-turn test runs; when
                false, only single-turn test runs. Omit to return both.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.TEST_RUNS_ENDPOINT,
            response_schema=TestRunList,
            query={
                "page": page,
                "pageSize": page_size,
                "start": start,
                "end": end,
                "sortBy": sort_by,
                "ascending": ascending,
                "status": status,
                "multiTurn": multi_turn,
            },
        )

    async def a_list_test_runs(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        sort_by: Optional[Literal["createdAt", "runDuration"]] = None,
        ascending: Optional[bool] = None,
        status: Optional[
            Literal["IN_PROGRESS", "COMPLETED", "ERRORED", "CANCELLED"]
        ] = None,
        multi_turn: Optional[bool] = None
    ) -> TestRunList:
        """List Test Runs

        Lists the test runs in your Confident AI project, newest first by
        default. Filter by `status`, `multiTurn` and the `start`/`end` window,
        sort with `sortBy` and `ascending`, and page with `page` and `pageSize`.
        Requires an active trial or paid plan.

        Args:
            page: The page of test runs to return. Defaults to 1.
            page_size: The number of test runs per page, at most 100. Defaults
                to 25.
            start: Returns only test runs created at or after this ISO 8601
                datetime. Defaults to 60 days ago.
            end: Returns only test runs created at or before this ISO 8601
                datetime. Defaults to now.
            sort_by: The field to sort by. Defaults to `createdAt`.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`.
            status: Returns only test runs with this status.
            multi_turn: When true, returns only multi-turn test runs; when
                false, only single-turn test runs. Omit to return both.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.TEST_RUNS_ENDPOINT,
            response_schema=TestRunList,
            query={
                "page": page,
                "pageSize": page_size,
                "start": start,
                "end": end,
                "sortBy": sort_by,
                "ascending": ascending,
                "status": status,
                "multiTurn": multi_turn,
            },
        )

    def create_test_run(
        self,
        *,
        metric_collection: Optional[str] = None,
        identifier: Optional[str] = None
    ) -> TestRunRef:
        """Create Test Run

        Creates a new in-progress test run and returns its id. Use this id as
        the `testRunId` when ingesting traces so that each trace becomes one
        test case in this run, evaluated with `metricCollection` when one is
        given.

        Args:
            metric_collection: The name of the metric collection used to
                evaluate the test cases formed from traces ingested into this
                test run. It must be a single-turn collection.
            identifier: An optional human-readable identifier for the test run,
                shown on the Confident AI platform.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.TEST_RUNS_ENDPOINT,
            response_schema=TestRunRef,
            request_schema=CreateTestRunRequest,
            body={
                "metricCollection": metric_collection,
                "identifier": identifier,
            },
        )

    async def a_create_test_run(
        self,
        *,
        metric_collection: Optional[str] = None,
        identifier: Optional[str] = None
    ) -> TestRunRef:
        """Create Test Run

        Creates a new in-progress test run and returns its id. Use this id as
        the `testRunId` when ingesting traces so that each trace becomes one
        test case in this run, evaluated with `metricCollection` when one is
        given.

        Args:
            metric_collection: The name of the metric collection used to
                evaluate the test cases formed from traces ingested into this
                test run. It must be a single-turn collection.
            identifier: An optional human-readable identifier for the test run,
                shown on the Confident AI platform.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.TEST_RUNS_ENDPOINT,
            response_schema=TestRunRef,
            request_schema=CreateTestRunRequest,
            body={
                "metricCollection": metric_collection,
                "identifier": identifier,
            },
        )

    def submit_test_case_result(
        self,
        test_case_id: str,
        *,
        actual_output: Optional[str] = None,
        retrieval_context: Optional[List[str]] = None,
        tools_called: Optional[List[ToolCall]] = None,
        expected_tools: Optional[List[ToolCall]] = None,
        token_cost: Optional[float] = None,
        input_token_count: Optional[int] = None,
        output_token_count: Optional[int] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> SubmittedTestCaseResult:
        """Submit Test Case Result

        Submits the result for a single test case in a long-running agent
        evaluation. Confident AI evaluates the test case and finalizes the test
        run once every result has been received; a repeated submission for the
        same test case is ignored and reported as `already_received`. Long-
        running mode is available for single-turn AI connection evaluations
        only. Responds 410 when the `testCaseId` is unknown or its result window
        has closed, 404 when its test run is not in this project, 409 when the
        test run is no longer accepting results, and 400 when the test run is
        multi-turn or has no metric collection.

        Args:
            test_case_id: The test case id Confident AI sent to your AI
                connection as `confident.testCaseId` when it dispatched this
                golden.
            actual_output: The actual output produced by your agent.
            retrieval_context: The retrieval context your agent used, if any.
            tools_called: The tools your agent called while producing the
                output.
            expected_tools: The tools you expected to be called for this test
                case.
            token_cost: This is the cost of the tokens used to produce the
                output.
            input_token_count: This is the number of input tokens passed to the
                LLM model.
            output_token_count: This is the number of output tokens generated by
                the LLM model.
            metadata: Optional additional metadata to attach to the test case.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.TEST_RUNS_EVALUATE_ENDPOINT,
            response_schema=SubmittedTestCaseResult,
            request_schema=SubmitTestCaseResultRequest,
            body={
                "actualOutput": actual_output,
                "retrievalContext": retrieval_context,
                "toolsCalled": tools_called,
                "expectedTools": expected_tools,
                "tokenCost": token_cost,
                "inputTokenCount": input_token_count,
                "outputTokenCount": output_token_count,
                "metadata": metadata,
            },
            path={"testCaseId": test_case_id},
        )

    async def a_submit_test_case_result(
        self,
        test_case_id: str,
        *,
        actual_output: Optional[str] = None,
        retrieval_context: Optional[List[str]] = None,
        tools_called: Optional[List[ToolCall]] = None,
        expected_tools: Optional[List[ToolCall]] = None,
        token_cost: Optional[float] = None,
        input_token_count: Optional[int] = None,
        output_token_count: Optional[int] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> SubmittedTestCaseResult:
        """Submit Test Case Result

        Submits the result for a single test case in a long-running agent
        evaluation. Confident AI evaluates the test case and finalizes the test
        run once every result has been received; a repeated submission for the
        same test case is ignored and reported as `already_received`. Long-
        running mode is available for single-turn AI connection evaluations
        only. Responds 410 when the `testCaseId` is unknown or its result window
        has closed, 404 when its test run is not in this project, 409 when the
        test run is no longer accepting results, and 400 when the test run is
        multi-turn or has no metric collection.

        Args:
            test_case_id: The test case id Confident AI sent to your AI
                connection as `confident.testCaseId` when it dispatched this
                golden.
            actual_output: The actual output produced by your agent.
            retrieval_context: The retrieval context your agent used, if any.
            tools_called: The tools your agent called while producing the
                output.
            expected_tools: The tools you expected to be called for this test
                case.
            token_cost: This is the cost of the tokens used to produce the
                output.
            input_token_count: This is the number of input tokens passed to the
                LLM model.
            output_token_count: This is the number of output tokens generated by
                the LLM model.
            metadata: Optional additional metadata to attach to the test case.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.TEST_RUNS_EVALUATE_ENDPOINT,
            response_schema=SubmittedTestCaseResult,
            request_schema=SubmitTestCaseResultRequest,
            body={
                "actualOutput": actual_output,
                "retrievalContext": retrieval_context,
                "toolsCalled": tools_called,
                "expectedTools": expected_tools,
                "tokenCost": token_cost,
                "inputTokenCount": input_token_count,
                "outputTokenCount": output_token_count,
                "metadata": metadata,
            },
            path={"testCaseId": test_case_id},
        )

    def get_test_run(self, test_run_id: str) -> TestRun:
        """Get Test Run

        Retrieves a test run with its aggregated metric scores and every test
        case in it, each with its metric results. The test cases are single-
        turn, multi-turn or trace-based depending on how the run was evaluated,
        never a mix. Requires an active trial or paid plan.

        Args:
            test_run_id: The id of the test run.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.TEST_RUN_ENDPOINT,
            response_schema=TestRun,
            path={"testRunId": test_run_id},
        )

    async def a_get_test_run(self, test_run_id: str) -> TestRun:
        """Get Test Run

        Retrieves a test run with its aggregated metric scores and every test
        case in it, each with its metric results. The test cases are single-
        turn, multi-turn or trace-based depending on how the run was evaluated,
        never a mix. Requires an active trial or paid plan.

        Args:
            test_run_id: The id of the test run.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.TEST_RUN_ENDPOINT,
            response_schema=TestRun,
            path={"testRunId": test_run_id},
        )
