// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: organization).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { GovernancePoliciesSkillOperations } from "../governance-policies/skill/operations";
import {
  GovernanceProject,
  GovernanceProjectList,
  GovernanceProjectStatus,
} from "../types";

export class GovernanceProjectsOperations extends GovernancePoliciesSkillOperations {
  /**
   * List Projects
   *
   * Lists every project in your organization with its governance standing,
   * ordered by project name, alongside an organization-wide roll-up of how many
   * projects fall into each status. Projects enrolled in no governance policy
   * are included, with a `status` of `not_enrolled` and a null `health`, since
   * the inventory is what tells you which projects are ungoverned.
   *
   * @param status Only return projects with this status. The
   *   `governanceProjectPortfolio` roll-up always covers the whole organization
   *   and is not narrowed by this filter.
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of projects per page, at most 100. Defaults to
   *   25.
   */
  async listGovernanceProjects(
    options: {
      status?: GovernanceProjectStatus;
      page?: number;
      pageSize?: number;
    } = {},
  ): Promise<GovernanceProjectList> {
    const { status, page, pageSize } = options;
    return this.api.sendRequest<GovernanceProjectList>(
      HttpMethods.GET,
      Endpoints.ORGANIZATION_GOVERNANCE_PROJECTS_ENDPOINT,
      { params: { status, page, pageSize } },
    );
  }

  /**
   * Get Project
   *
   * Retrieves one project's governance view in full: every control its policy
   * applies, inherited ones included, together with its recent verdict history.
   * A project enrolled in no policy is reported as not found, so use the
   * inventory listing to tell an ungoverned project from one that does not
   * exist.
   *
   * @param projectId The id of the project.
   */
  async getGovernanceProject(projectId: string): Promise<GovernanceProject> {
    return this.api.sendRequest<GovernanceProject>(
      HttpMethods.GET,
      Endpoints.ORGANIZATION_GOVERNANCE_PROJECT_ENDPOINT,
      { urlParams: { projectId } },
    );
  }
}
