# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: dashboards).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import List, Optional

from confidentai.api import Api, HttpMethods
from confidentai.common.types import CreateWidgetRequest, WidgetGranularity
from confidentai.dashboards.types import (
    CreateDashboardRequest,
    Dashboard,
    DashboardList,
    DashboardQueryRequest,
    DashboardQueryResult,
    DashboardRef,
    UpdateDashboardRequest,
)
from confidentai.endpoints import Endpoints


class DashboardsOperations:
    _api: Api

    def list(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> DashboardList:
        """List Dashboards

        Lists the dashboards in your Confident AI project one page at a time,
        newest first. Each dashboard is returned with its widgets counted;
        retrieve one by id for their configuration, or query it for their data.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.DASHBOARDS_ENDPOINT,
            response_schema=DashboardList,
            query={"page": page, "pageSize": page_size},
        )

    async def a_list(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> DashboardList:
        """List Dashboards

        Lists the dashboards in your Confident AI project one page at a time,
        newest first. Each dashboard is returned with its widgets counted;
        retrieve one by id for their configuration, or query it for their data.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.DASHBOARDS_ENDPOINT,
            response_schema=DashboardList,
            query={"page": page, "pageSize": page_size},
        )

    def create(
        self,
        name: str,
        *,
        description: Optional[str] = None,
        private: Optional[bool] = None,
        widgets: Optional[List[CreateWidgetRequest]] = None
    ) -> DashboardRef:
        """Create Dashboard

        Creates a dashboard in your Confident AI project and returns its id.
        Send `widgets` to create it with its charts already on it, which saves a
        call per widget; any widget you send without a `layout` is packed onto
        the grid in the order given.

        Args:
            name: The name of the dashboard.
            description: What the dashboard covers. Send null to leave it unset.
            private: Whether the dashboard is visible only to its creator.
                Defaults to false, which shares it with the project.
            widgets: The widgets to create the dashboard with. Each one that
                sends no `layout` is packed onto the grid in the order given.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.DASHBOARDS_ENDPOINT,
            response_schema=DashboardRef,
            request_schema=CreateDashboardRequest,
            body={
                "name": name,
                "description": description,
                "private": private,
                "widgets": widgets,
            },
        )

    async def a_create(
        self,
        name: str,
        *,
        description: Optional[str] = None,
        private: Optional[bool] = None,
        widgets: Optional[List[CreateWidgetRequest]] = None
    ) -> DashboardRef:
        """Create Dashboard

        Creates a dashboard in your Confident AI project and returns its id.
        Send `widgets` to create it with its charts already on it, which saves a
        call per widget; any widget you send without a `layout` is packed onto
        the grid in the order given.

        Args:
            name: The name of the dashboard.
            description: What the dashboard covers. Send null to leave it unset.
            private: Whether the dashboard is visible only to its creator.
                Defaults to false, which shares it with the project.
            widgets: The widgets to create the dashboard with. Each one that
                sends no `layout` is packed onto the grid in the order given.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.DASHBOARDS_ENDPOINT,
            response_schema=DashboardRef,
            request_schema=CreateDashboardRequest,
            body={
                "name": name,
                "description": description,
                "private": private,
                "widgets": widgets,
            },
        )

    def get(self, dashboard_id: str) -> Dashboard:
        """Get Dashboard

        Retrieves a dashboard by id, with every widget on it and the lines each
        widget plots. This is the widgets' configuration, not their data — query
        the dashboard to compute that.

        Args:
            dashboard_id: The id of the dashboard.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.DASHBOARD_ENDPOINT,
            response_schema=Dashboard,
            path={"dashboardId": dashboard_id},
        )

    async def a_get(self, dashboard_id: str) -> Dashboard:
        """Get Dashboard

        Retrieves a dashboard by id, with every widget on it and the lines each
        widget plots. This is the widgets' configuration, not their data — query
        the dashboard to compute that.

        Args:
            dashboard_id: The id of the dashboard.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.DASHBOARD_ENDPOINT,
            response_schema=Dashboard,
            path={"dashboardId": dashboard_id},
        )

    def update(
        self,
        dashboard_id: str,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None,
        private: Optional[bool] = None
    ) -> Dashboard:
        """Update Dashboard

        Renames a dashboard, changes its description, or makes it private, and
        returns it. Its widgets are managed through their own endpoints.

        Args:
            dashboard_id: The id of the dashboard.
            name: The name of the dashboard.
            description: What the dashboard covers. Send null to clear it.
            private: Whether the dashboard is visible only to its creator.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.DASHBOARD_ENDPOINT,
            response_schema=Dashboard,
            request_schema=UpdateDashboardRequest,
            body={"name": name, "description": description, "private": private},
            path={"dashboardId": dashboard_id},
        )

    async def a_update(
        self,
        dashboard_id: str,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None,
        private: Optional[bool] = None
    ) -> Dashboard:
        """Update Dashboard

        Renames a dashboard, changes its description, or makes it private, and
        returns it. Its widgets are managed through their own endpoints.

        Args:
            dashboard_id: The id of the dashboard.
            name: The name of the dashboard.
            description: What the dashboard covers. Send null to clear it.
            private: Whether the dashboard is visible only to its creator.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.DASHBOARD_ENDPOINT,
            response_schema=Dashboard,
            request_schema=UpdateDashboardRequest,
            body={"name": name, "description": description, "private": private},
            path={"dashboardId": dashboard_id},
        )

    def delete(self, dashboard_id: str) -> DashboardRef:
        """Delete Dashboard

        Permanently deletes a dashboard. Its widgets are detached rather than
        deleted, so any that another dashboard also shows are untouched.

        Args:
            dashboard_id: The id of the dashboard.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.DASHBOARD_ENDPOINT,
            response_schema=DashboardRef,
            path={"dashboardId": dashboard_id},
        )

    async def a_delete(self, dashboard_id: str) -> DashboardRef:
        """Delete Dashboard

        Permanently deletes a dashboard. Its widgets are detached rather than
        deleted, so any that another dashboard also shows are untouched.

        Args:
            dashboard_id: The id of the dashboard.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.DASHBOARD_ENDPOINT,
            response_schema=DashboardRef,
            path={"dashboardId": dashboard_id},
        )

    def query(
        self,
        dashboard_id: str,
        *,
        start_time: Optional[str] = None,
        end_time: Optional[str] = None,
        granularity: Optional[WidgetGranularity] = None,
        widget_ids: Optional[List[str]] = None
    ) -> DashboardQueryResult:
        """Query Dashboard

        Computes the data behind every widget on a dashboard, or behind the
        subset named by `widgetIds`. A time range you send overrides each
        widget's own for this query only. Widgets are computed independently, so
        one that fails comes back with `status` `ERROR` while the rest still
        carry their data.

        Args:
            dashboard_id: The id of the dashboard.
            start_time: The start of the range to compute over, as an ISO 8601
                datetime. Must be sent together with `endTime`, and overrides
                each widget's own range for this query only.
            end_time: The end of the range to compute over, as an ISO 8601
                datetime. Must be sent together with `startTime`, and must be
                later than it.
            widget_ids: The widgets to compute. Omit it to compute every widget
                on the dashboard.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.DASHBOARD_QUERY_ENDPOINT,
            response_schema=DashboardQueryResult,
            request_schema=DashboardQueryRequest,
            body={
                "startTime": start_time,
                "endTime": end_time,
                "granularity": granularity,
                "widgetIds": widget_ids,
            },
            path={"dashboardId": dashboard_id},
        )

    async def a_query(
        self,
        dashboard_id: str,
        *,
        start_time: Optional[str] = None,
        end_time: Optional[str] = None,
        granularity: Optional[WidgetGranularity] = None,
        widget_ids: Optional[List[str]] = None
    ) -> DashboardQueryResult:
        """Query Dashboard

        Computes the data behind every widget on a dashboard, or behind the
        subset named by `widgetIds`. A time range you send overrides each
        widget's own for this query only. Widgets are computed independently, so
        one that fails comes back with `status` `ERROR` while the rest still
        carry their data.

        Args:
            dashboard_id: The id of the dashboard.
            start_time: The start of the range to compute over, as an ISO 8601
                datetime. Must be sent together with `endTime`, and overrides
                each widget's own range for this query only.
            end_time: The end of the range to compute over, as an ISO 8601
                datetime. Must be sent together with `startTime`, and must be
                later than it.
            widget_ids: The widgets to compute. Omit it to compute every widget
                on the dashboard.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.DASHBOARD_QUERY_ENDPOINT,
            response_schema=DashboardQueryResult,
            request_schema=DashboardQueryRequest,
            body={
                "startTime": start_time,
                "endTime": end_time,
                "granularity": granularity,
                "widgetIds": widget_ids,
            },
            path={"dashboardId": dashboard_id},
        )
