# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: report-templates).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import List, Optional

from pydantic import Field

from confidentai.common.types import (
    ScheduleIntervalUnit,
    ScheduleRecurrenceType,
)
from confidentai.types import ConfidentBaseModel


class ReportTemplateSectionSeverity(Enum):
    INFO = "INFO"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    DANGER = "DANGER"


class ReportTemplateSectionType(Enum):
    CONTENT = "CONTENT"
    STAT_CARDS = "STAT_CARDS"
    TABLE = "TABLE"
    GRAPH = "GRAPH"
    ADMONITION = "ADMONITION"


class ReportTemplateType(Enum):
    RISK_ASSESSMENT_REPORT = "RISK_ASSESSMENT_REPORT"
    EXECUTIVE_REPORT = "EXECUTIVE_REPORT"


class ReportTemplateSectionContent(ConfidentBaseModel):
    text: Optional[str] = None
    severity: Optional[ReportTemplateSectionSeverity] = None


class ReportTemplateSectionConfig(ConfidentBaseModel):
    id: Optional[str] = None
    type: ReportTemplateSectionType
    heading: Optional[str] = None
    use_ai: Optional[bool] = Field(default=None, alias="useAI")
    prompt: Optional[str] = None
    content: Optional[ReportTemplateSectionContent] = None
    start_on_new_page: Optional[bool] = Field(
        default=None,
        alias="startOnNewPage",
    )


class CreateReportTemplateRequest(ConfidentBaseModel):
    name: str
    description: Optional[str] = None
    template_sections: Optional[List[ReportTemplateSectionConfig]] = Field(
        default=None,
        alias="templateSections",
    )
    enabled: Optional[bool] = None
    recurrence: Optional[ScheduleRecurrenceType] = None
    repeat_every: Optional[int] = Field(default=None, alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(
        default=None,
        alias="repeatUnit",
    )
    start_at: Optional[str] = Field(default=None, alias="startAt")
    max_runs: Optional[int] = Field(default=None, alias="maxRuns")
    end_at: Optional[str] = Field(default=None, alias="endAt")


class ReportTemplateSchedule(ConfidentBaseModel):
    recurrence: ScheduleRecurrenceType
    repeat_every: Optional[int] = Field(alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(alias="repeatUnit")
    start_at: Optional[str] = Field(alias="startAt")
    max_runs: Optional[int] = Field(alias="maxRuns")
    end_at: Optional[str] = Field(alias="endAt")
    run_count: int = Field(alias="runCount")
    last_run_at: Optional[str] = Field(alias="lastRunAt")


class ReportTemplateSection(ConfidentBaseModel):
    id: str
    type: ReportTemplateSectionType
    heading: Optional[str]
    order: int
    use_ai: bool = Field(alias="useAI")
    prompt: Optional[str]
    content: Optional[ReportTemplateSectionContent]
    start_on_new_page: bool = Field(alias="startOnNewPage")


class ReportTemplate(ConfidentBaseModel):
    id: str
    name: str
    description: Optional[str]
    type: Optional[ReportTemplateType]
    enabled: bool
    created_at: str = Field(alias="createdAt")
    schedule: Optional[ReportTemplateSchedule]
    template_sections: List[ReportTemplateSection] = Field(
        alias="templateSections",
    )


class ReportTemplateSummary(ConfidentBaseModel):
    id: str
    name: str
    description: Optional[str]
    type: Optional[ReportTemplateType]
    enabled: bool
    created_at: str = Field(alias="createdAt")


class ReportTemplateList(ConfidentBaseModel):
    report_templates: List[ReportTemplateSummary] = Field(
        alias="reportTemplates",
    )
    total_report_templates: int = Field(alias="totalReportTemplates")
    page: int
    page_size: int = Field(alias="pageSize")


class ReportTemplateRef(ConfidentBaseModel):
    id: str


class UpdateReportTemplateRequest(ConfidentBaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    template_sections: Optional[List[ReportTemplateSectionConfig]] = Field(
        default=None,
        alias="templateSections",
    )
    enabled: Optional[bool] = None
    recurrence: Optional[ScheduleRecurrenceType] = None
    repeat_every: Optional[int] = Field(default=None, alias="repeatEvery")
    repeat_unit: Optional[ScheduleIntervalUnit] = Field(
        default=None,
        alias="repeatUnit",
    )
    start_at: Optional[str] = Field(default=None, alias="startAt")
    max_runs: Optional[int] = Field(default=None, alias="maxRuns")
    end_at: Optional[str] = Field(default=None, alias="endAt")
