// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: organization).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { InvitationsOperations } from "../invitations/operations";
import { MemberRef } from "../../common/types";
import { OrganizationMember, OrganizationMemberList } from "../types";

export class MembersOperations extends InvitationsOperations {
  /**
   * List Organization Members
   *
   * Lists the members of your organization one page at a time, each with the
   * organization role that decides what they can do. Membership here is what
   * grants access to the organization itself; a member still has to be added to
   * a project before they can see that project's data, so every project's
   * member list is drawn from this one.
   *
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of members per page, at most 100. Defaults to
   *   25.
   */
  async listMembers(
    page?: number,
    pageSize?: number,
  ): Promise<OrganizationMemberList> {
    return this.api.sendRequest<OrganizationMemberList>(
      HttpMethods.GET,
      Endpoints.ORGANIZATION_MEMBERS_ENDPOINT,
      { params: { page, pageSize } },
    );
  }

  /**
   * Update Organization Member Role
   *
   * Replaces a member's organization role, which changes what they may do
   * across the organization from their next request onwards. Assigning the
   * `Owner` role transfers ownership: the member becomes Owner and the previous
   * Owner is demoted to `Admin` in the same transaction. That is the only way
   * the Owner's role changes — moving the Owner onto any other role directly is
   * refused. A role id belonging to another organization is rejected, and the
   * member's project roles are left untouched.
   *
   * @param userId The id of the user whose organization membership to change.
   * @param roleId The id of the role to assign. It must be a Confident AI
   *   built-in role or one of the roles the organization or project owns.
   */
  async updateMemberRole(
    userId: string,
    roleId: string,
  ): Promise<OrganizationMember> {
    return this.api.sendRequest<OrganizationMember>(
      HttpMethods.PUT,
      Endpoints.ORGANIZATION_MEMBER_ENDPOINT,
      { body: { roleId }, urlParams: { userId } },
    );
  }

  /**
   * Remove Organization Member
   *
   * Revokes a member's access to the organization and to everything inside it:
   * they are detached from the organization, disconnected from every project in
   * it, their organization and project roles are deleted, and any invitation
   * still outstanding for their email address is cleared. The Owner cannot be
   * removed, so transfer ownership first. Removal is not reversible through
   * this endpoint — the only way back is a fresh invitation, which returns them
   * with no project access. The user's own account and the records they created
   * are kept.
   *
   * @param userId The id of the user whose organization membership to change.
   */
  async removeMember(userId: string): Promise<MemberRef> {
    return this.api.sendRequest<MemberRef>(
      HttpMethods.DELETE,
      Endpoints.ORGANIZATION_MEMBER_ENDPOINT,
      { urlParams: { userId } },
    );
  }
}
