// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: metrics).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { MetricEvaluationParam, Rubric } from "../common/types";

export interface UpdateMetricRequest {
  criteria?: string | null;
  evaluationSteps?: string[] | null;
  evaluationParams?: MetricEvaluationParam[];
  rubric?: Rubric[];
}
