# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: prompts).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.prompts.types import (
    CreatePromptBranchRequest,
    PromptBranch,
    PromptBranchList,
    PromptBranchRef,
    UpdatePromptBranchRequest,
)


class BranchesOperations:
    _api: Api

    def get_branches(self, prompt_id: str) -> PromptBranchList:
        """List Prompt Branches

        Lists the branches of the prompt.

        Args:
            prompt_id: The unique id of the prompt.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.PROMPT_BRANCHES_ENDPOINT,
            response_schema=PromptBranchList,
            path={"promptId": prompt_id},
        )

    async def a_get_branches(self, prompt_id: str) -> PromptBranchList:
        """List Prompt Branches

        Lists the branches of the prompt.

        Args:
            prompt_id: The unique id of the prompt.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.PROMPT_BRANCHES_ENDPOINT,
            response_schema=PromptBranchList,
            path={"promptId": prompt_id},
        )

    def create_branch(self, prompt_id: str, name: str) -> PromptBranch:
        """Create Prompt Branch

        Creates a branch of the prompt diverging from the head commit of `main`.

        Args:
            prompt_id: The unique id of the prompt.
            name: The name of the branch to create. It diverges from the head
                commit of `main`.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.PROMPT_BRANCHES_ENDPOINT,
            response_schema=PromptBranch,
            request_schema=CreatePromptBranchRequest,
            body={"name": name},
            path={"promptId": prompt_id},
        )

    async def a_create_branch(self, prompt_id: str, name: str) -> PromptBranch:
        """Create Prompt Branch

        Creates a branch of the prompt diverging from the head commit of `main`.

        Args:
            prompt_id: The unique id of the prompt.
            name: The name of the branch to create. It diverges from the head
                commit of `main`.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.PROMPT_BRANCHES_ENDPOINT,
            response_schema=PromptBranch,
            request_schema=CreatePromptBranchRequest,
            body={"name": name},
            path={"promptId": prompt_id},
        )

    def update_branch(
        self, prompt_id: str, branch_id: str, name: str
    ) -> PromptBranchRef:
        """Update Prompt Branch

        Renames a branch of the prompt. The `main` branch cannot be renamed.

        Args:
            prompt_id: The unique id of the prompt.
            branch_id: The unique id of the branch.
            name: The new name of the branch. The `main` branch cannot be
                renamed.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.PROMPT_BRANCH_ENDPOINT,
            response_schema=PromptBranchRef,
            request_schema=UpdatePromptBranchRequest,
            body={"name": name},
            path={"promptId": prompt_id, "branchId": branch_id},
        )

    async def a_update_branch(
        self, prompt_id: str, branch_id: str, name: str
    ) -> PromptBranchRef:
        """Update Prompt Branch

        Renames a branch of the prompt. The `main` branch cannot be renamed.

        Args:
            prompt_id: The unique id of the prompt.
            branch_id: The unique id of the branch.
            name: The new name of the branch. The `main` branch cannot be
                renamed.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.PROMPT_BRANCH_ENDPOINT,
            response_schema=PromptBranchRef,
            request_schema=UpdatePromptBranchRequest,
            body={"name": name},
            path={"promptId": prompt_id, "branchId": branch_id},
        )

    def delete_branch(self, prompt_id: str, branch_id: str) -> PromptBranchRef:
        """Delete Prompt Branch

        Deletes a branch of the prompt. The `main` branch, branches with open
        pull requests, and branches referenced by AI connections cannot be
        deleted.

        Args:
            prompt_id: The unique id of the prompt.
            branch_id: The unique id of the branch.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.PROMPT_BRANCH_ENDPOINT,
            response_schema=PromptBranchRef,
            path={"promptId": prompt_id, "branchId": branch_id},
        )

    async def a_delete_branch(
        self, prompt_id: str, branch_id: str
    ) -> PromptBranchRef:
        """Delete Prompt Branch

        Deletes a branch of the prompt. The `main` branch, branches with open
        pull requests, and branches referenced by AI connections cannot be
        deleted.

        Args:
            prompt_id: The unique id of the prompt.
            branch_id: The unique id of the branch.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.PROMPT_BRANCH_ENDPOINT,
            response_schema=PromptBranchRef,
            path={"promptId": prompt_id, "branchId": branch_id},
        )
