# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: metrics-data).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import List

from pydantic import Field

from confident_ai.common.types import MetricData
from confident_ai.types import ConfidentBaseModel


class MetricDataList(ConfidentBaseModel):
    metrics_data: List[MetricData] = Field(alias="metricsData")
    total_metrics_data: int = Field(alias="totalMetricsData")
    page: int
    page_size: int = Field(alias="pageSize")
