# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: classifiers).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Optional

from confidentai.api import Api, HttpMethods
from confidentai.classifiers.types import (
    Classifier,
    ClassifierAutoGenerationConfig,
    ClassifierDataModel,
    ClassifierLabelGeneration,
    ClassifierList,
    ClassifierPreset,
    ClassifierRef,
    CreateClassifierRequest,
    UpdateClassifierRequest,
)
from confidentai.common.types import FilterSet
from confidentai.endpoints import Endpoints


class ClassifiersOperations:
    _api: Api

    def list(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        data_model: Optional[ClassifierDataModel] = None
    ) -> ClassifierList:
        """List Classifiers

        Lists the classifiers in your Confident AI project one page at a time,
        ordered by name. Each is returned as a summary row — enough to pick one;
        retrieve a classifier by id for its filters, generation config, and
        labels. Requires the Starter plan or above.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.CLASSIFIERS_ENDPOINT,
            response_schema=ClassifierList,
            query={
                "page": page,
                "pageSize": page_size,
                "dataModel": data_model,
            },
        )

    async def a_list(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        data_model: Optional[ClassifierDataModel] = None
    ) -> ClassifierList:
        """List Classifiers

        Lists the classifiers in your Confident AI project one page at a time,
        ordered by name. Each is returned as a summary row — enough to pick one;
        retrieve a classifier by id for its filters, generation config, and
        labels. Requires the Starter plan or above.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.CLASSIFIERS_ENDPOINT,
            response_schema=ClassifierList,
            query={
                "page": page,
                "pageSize": page_size,
                "dataModel": data_model,
            },
        )

    def create(
        self,
        name: str,
        data_model: ClassifierDataModel,
        *,
        preset: Optional[ClassifierPreset] = None,
        description: Optional[str] = None,
        enabled: Optional[bool] = None,
        auto_classify: Optional[bool] = None,
        filters: Optional[FilterSet] = None,
        auto_generation_config: Optional[ClassifierAutoGenerationConfig] = None
    ) -> ClassifierRef:
        """Create Classifier

        Creates a classifier that tags incoming traces or threads with labels,
        and returns its id. A name is unique per data model within the project.
        Sending a `preset` seeds the classifier with a description, a generation
        config, and a starting set of labels; any field you send explicitly
        overrides what the preset would have set. SENTIMENT arrives with its
        labels ready, while USE_CASES and ISSUES ship with none and expect a
        generation run next. Retrieve the classifier by id to read back what the
        preset seeded. Requires the Starter plan or above.

        Args:
            name: The name of the classifier, unique per data model within the
                project.
            description: What this classifier is for. Send null to clear it.
            enabled: Whether the classifier runs at all. Defaults to true.
            auto_classify: Whether incoming items are classified automatically
                as they arrive. Defaults to true.
            filters: Narrows which traces or threads the classifier runs on, so
                it can watch one route rather than the whole project. Only the
                groups are stored, so the set's top-level operator is dropped
                and the groups are combined by the platform. Send null to clear
                the filters and classify everything of this data model.
            auto_generation_config: How a generation run samples and clusters
                your traffic to discover labels. Send null to clear it.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.CLASSIFIERS_ENDPOINT,
            response_schema=ClassifierRef,
            request_schema=CreateClassifierRequest,
            body={
                "name": name,
                "dataModel": data_model,
                "preset": preset,
                "description": description,
                "enabled": enabled,
                "autoClassify": auto_classify,
                "filters": filters,
                "autoGenerationConfig": auto_generation_config,
            },
        )

    async def a_create(
        self,
        name: str,
        data_model: ClassifierDataModel,
        *,
        preset: Optional[ClassifierPreset] = None,
        description: Optional[str] = None,
        enabled: Optional[bool] = None,
        auto_classify: Optional[bool] = None,
        filters: Optional[FilterSet] = None,
        auto_generation_config: Optional[ClassifierAutoGenerationConfig] = None
    ) -> ClassifierRef:
        """Create Classifier

        Creates a classifier that tags incoming traces or threads with labels,
        and returns its id. A name is unique per data model within the project.
        Sending a `preset` seeds the classifier with a description, a generation
        config, and a starting set of labels; any field you send explicitly
        overrides what the preset would have set. SENTIMENT arrives with its
        labels ready, while USE_CASES and ISSUES ship with none and expect a
        generation run next. Retrieve the classifier by id to read back what the
        preset seeded. Requires the Starter plan or above.

        Args:
            name: The name of the classifier, unique per data model within the
                project.
            description: What this classifier is for. Send null to clear it.
            enabled: Whether the classifier runs at all. Defaults to true.
            auto_classify: Whether incoming items are classified automatically
                as they arrive. Defaults to true.
            filters: Narrows which traces or threads the classifier runs on, so
                it can watch one route rather than the whole project. Only the
                groups are stored, so the set's top-level operator is dropped
                and the groups are combined by the platform. Send null to clear
                the filters and classify everything of this data model.
            auto_generation_config: How a generation run samples and clusters
                your traffic to discover labels. Send null to clear it.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.CLASSIFIERS_ENDPOINT,
            response_schema=ClassifierRef,
            request_schema=CreateClassifierRequest,
            body={
                "name": name,
                "dataModel": data_model,
                "preset": preset,
                "description": description,
                "enabled": enabled,
                "autoClassify": auto_classify,
                "filters": filters,
                "autoGenerationConfig": auto_generation_config,
            },
        )

    def get(self, classifier_id: str) -> Classifier:
        """Get Classifier

        Retrieves a classifier by id, with the filters that scope what it runs
        on, its generation config, and every label it can apply. Requires the
        Starter plan or above.

        Args:
            classifier_id: The id of the classifier.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.CLASSIFIER_ENDPOINT,
            response_schema=Classifier,
            path={"classifierId": classifier_id},
        )

    async def a_get(self, classifier_id: str) -> Classifier:
        """Get Classifier

        Retrieves a classifier by id, with the filters that scope what it runs
        on, its generation config, and every label it can apply. Requires the
        Starter plan or above.

        Args:
            classifier_id: The id of the classifier.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.CLASSIFIER_ENDPOINT,
            response_schema=Classifier,
            path={"classifierId": classifier_id},
        )

    def update(
        self,
        classifier_id: str,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None,
        enabled: Optional[bool] = None,
        auto_classify: Optional[bool] = None,
        filters: Optional[FilterSet] = None,
        auto_generation_config: Optional[ClassifierAutoGenerationConfig] = None
    ) -> Classifier:
        """Update Classifier

        Updates a classifier and returns it. Only the fields you send are
        changed: omitting a field leaves it untouched, and sending null clears
        it. `dataModel` cannot be changed after creation and a preset can only
        be applied when creating one; labels are managed through their own
        endpoints. Requires the Starter plan or above.

        Args:
            classifier_id: The id of the classifier.
            name: The name of the classifier, unique per data model within the
                project.
            description: What this classifier is for. Send null to clear it.
            enabled: Whether the classifier runs at all. Defaults to true.
            auto_classify: Whether incoming items are classified automatically
                as they arrive. Defaults to true.
            filters: Narrows which traces or threads the classifier runs on, so
                it can watch one route rather than the whole project. Only the
                groups are stored, so the set's top-level operator is dropped
                and the groups are combined by the platform. Send null to clear
                the filters and classify everything of this data model.
            auto_generation_config: How a generation run samples and clusters
                your traffic to discover labels. Send null to clear it.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.CLASSIFIER_ENDPOINT,
            response_schema=Classifier,
            request_schema=UpdateClassifierRequest,
            body={
                "name": name,
                "description": description,
                "enabled": enabled,
                "autoClassify": auto_classify,
                "filters": filters,
                "autoGenerationConfig": auto_generation_config,
            },
            path={"classifierId": classifier_id},
        )

    async def a_update(
        self,
        classifier_id: str,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None,
        enabled: Optional[bool] = None,
        auto_classify: Optional[bool] = None,
        filters: Optional[FilterSet] = None,
        auto_generation_config: Optional[ClassifierAutoGenerationConfig] = None
    ) -> Classifier:
        """Update Classifier

        Updates a classifier and returns it. Only the fields you send are
        changed: omitting a field leaves it untouched, and sending null clears
        it. `dataModel` cannot be changed after creation and a preset can only
        be applied when creating one; labels are managed through their own
        endpoints. Requires the Starter plan or above.

        Args:
            classifier_id: The id of the classifier.
            name: The name of the classifier, unique per data model within the
                project.
            description: What this classifier is for. Send null to clear it.
            enabled: Whether the classifier runs at all. Defaults to true.
            auto_classify: Whether incoming items are classified automatically
                as they arrive. Defaults to true.
            filters: Narrows which traces or threads the classifier runs on, so
                it can watch one route rather than the whole project. Only the
                groups are stored, so the set's top-level operator is dropped
                and the groups are combined by the platform. Send null to clear
                the filters and classify everything of this data model.
            auto_generation_config: How a generation run samples and clusters
                your traffic to discover labels. Send null to clear it.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.CLASSIFIER_ENDPOINT,
            response_schema=Classifier,
            request_schema=UpdateClassifierRequest,
            body={
                "name": name,
                "description": description,
                "enabled": enabled,
                "autoClassify": auto_classify,
                "filters": filters,
                "autoGenerationConfig": auto_generation_config,
            },
            path={"classifierId": classifier_id},
        )

    def delete(self, classifier_id: str) -> ClassifierRef:
        """Delete Classifier

        Permanently deletes a classifier and all of its labels, and returns its
        id. Classifications already applied to traces or threads are not
        removed. This action cannot be undone. Requires the Starter plan or
        above.

        Args:
            classifier_id: The id of the classifier.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.CLASSIFIER_ENDPOINT,
            response_schema=ClassifierRef,
            path={"classifierId": classifier_id},
        )

    async def a_delete(self, classifier_id: str) -> ClassifierRef:
        """Delete Classifier

        Permanently deletes a classifier and all of its labels, and returns its
        id. Classifications already applied to traces or threads are not
        removed. This action cannot be undone. Requires the Starter plan or
        above.

        Args:
            classifier_id: The id of the classifier.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.CLASSIFIER_ENDPOINT,
            response_schema=ClassifierRef,
            path={"classifierId": classifier_id},
        )

    def generate_labels(self, classifier_id: str) -> ClassifierLabelGeneration:
        """Generate Classifier Labels

        Discovers labels for a classifier from your project's real traffic: it
        samples recent traces (or threads), clusters them using the classifier's
        `autoGenerationConfig`, and writes the themes it finds back as labels
        with status RECOMMENDED for a human to review. The run is asynchronous
        and returns no job handle: `started` true means it was dispatched, not
        that labels exist yet, so poll the labels endpoint for the results. Each
        run first deletes every existing RECOMMENDED label on the classifier;
        labels already promoted to ACTIVE are kept and passed to the generator
        so it does not propose them again. Reading production traffic and
        running the model consumes usage. `autoGenerationConfig` must already
        have both `summaryPrompt` and `nClusters` set, otherwise the request is
        rejected. A `started` false response is not an error — it means there
        was too little traffic to sample, or sampling was briefly unavailable.
        Requires the Starter plan or above.

        Args:
            classifier_id: The id of the classifier.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.CLASSIFIER_GENERATE_ENDPOINT,
            response_schema=ClassifierLabelGeneration,
            path={"classifierId": classifier_id},
        )

    async def a_generate_labels(
        self, classifier_id: str
    ) -> ClassifierLabelGeneration:
        """Generate Classifier Labels

        Discovers labels for a classifier from your project's real traffic: it
        samples recent traces (or threads), clusters them using the classifier's
        `autoGenerationConfig`, and writes the themes it finds back as labels
        with status RECOMMENDED for a human to review. The run is asynchronous
        and returns no job handle: `started` true means it was dispatched, not
        that labels exist yet, so poll the labels endpoint for the results. Each
        run first deletes every existing RECOMMENDED label on the classifier;
        labels already promoted to ACTIVE are kept and passed to the generator
        so it does not propose them again. Reading production traffic and
        running the model consumes usage. `autoGenerationConfig` must already
        have both `summaryPrompt` and `nClusters` set, otherwise the request is
        rejected. A `started` false response is not an error — it means there
        was too little traffic to sample, or sampling was briefly unavailable.
        Requires the Starter plan or above.

        Args:
            classifier_id: The id of the classifier.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.CLASSIFIER_GENERATE_ENDPOINT,
            response_schema=ClassifierLabelGeneration,
            path={"classifierId": classifier_id},
        )
