# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: organization).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Optional

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.organization.types import (
    CreateGovernanceControlGroupRequest,
    GovernanceControlGroup,
    GovernanceControlGroupList,
    GovernanceControlGroupRef,
)


class GovernanceControlGroupsOperations:
    _api: Api

    def list_governance_control_groups(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> GovernanceControlGroupList:
        """List Governance Control Groups

        Lists your organization's governance control groups, newest created
        first, with each group's controls counted rather than named. A group is
        a label for organizing controls and does not itself govern anything —
        what a control gates comes from the governance policies holding it,
        never from its group.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of control groups per page, at most 100.
                Defaults to 25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_GROUPS_ENDPOINT,
            response_schema=GovernanceControlGroupList,
            query={"page": page, "pageSize": page_size},
        )

    async def a_list_governance_control_groups(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> GovernanceControlGroupList:
        """List Governance Control Groups

        Lists your organization's governance control groups, newest created
        first, with each group's controls counted rather than named. A group is
        a label for organizing controls and does not itself govern anything —
        what a control gates comes from the governance policies holding it,
        never from its group.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of control groups per page, at most 100.
                Defaults to 25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_GROUPS_ENDPOINT,
            response_schema=GovernanceControlGroupList,
            query={"page": page, "pageSize": page_size},
        )

    def create_governance_control_group(
        self, name: str, *, description: Optional[str] = None
    ) -> GovernanceControlGroupRef:
        """Create Governance Control Group

        Creates a governance control group and returns its id. The group starts
        empty, since which controls belong to it is set on each control rather
        than here, and putting a control in a group has no effect on which
        projects it gates or when it is assessed.

        Args:
            name: The name of the control group, unique within your
                organization.
            description: What the group collects. Send null to leave it unset.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_GROUPS_ENDPOINT,
            response_schema=GovernanceControlGroupRef,
            request_schema=CreateGovernanceControlGroupRequest,
            body={"name": name, "description": description},
        )

    async def a_create_governance_control_group(
        self, name: str, *, description: Optional[str] = None
    ) -> GovernanceControlGroupRef:
        """Create Governance Control Group

        Creates a governance control group and returns its id. The group starts
        empty, since which controls belong to it is set on each control rather
        than here, and putting a control in a group has no effect on which
        projects it gates or when it is assessed.

        Args:
            name: The name of the control group, unique within your
                organization.
            description: What the group collects. Send null to leave it unset.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_GROUPS_ENDPOINT,
            response_schema=GovernanceControlGroupRef,
            request_schema=CreateGovernanceControlGroupRequest,
            body={"name": name, "description": description},
        )

    def get_governance_control_group(
        self, control_group_id: str
    ) -> GovernanceControlGroup:
        """Get Governance Control Group

        Retrieves a single governance control group with the controls inside it,
        which the list endpoint reports only as a count. Each control is named
        rather than resolved — retrieve a control by id for its health, its
        policy membership and its definition.

        Args:
            control_group_id: The id of the governance control group.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_GROUP_ENDPOINT,
            response_schema=GovernanceControlGroup,
            path={"controlGroupId": control_group_id},
        )

    async def a_get_governance_control_group(
        self, control_group_id: str
    ) -> GovernanceControlGroup:
        """Get Governance Control Group

        Retrieves a single governance control group with the controls inside it,
        which the list endpoint reports only as a count. Each control is named
        rather than resolved — retrieve a control by id for its health, its
        policy membership and its definition.

        Args:
            control_group_id: The id of the governance control group.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_GROUP_ENDPOINT,
            response_schema=GovernanceControlGroup,
            path={"controlGroupId": control_group_id},
        )

    def delete_governance_control_group(
        self, control_group_id: str
    ) -> GovernanceControlGroupRef:
        """Delete Governance Control Group

        Permanently deletes a governance control group. The controls that were
        in it are not deleted and become ungrouped, and they keep gating exactly
        the projects they gated before, since a group never scoped that.
        **Warning:** This action cannot be undone.

        Args:
            control_group_id: The id of the governance control group.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_GROUP_ENDPOINT,
            response_schema=GovernanceControlGroupRef,
            path={"controlGroupId": control_group_id},
        )

    async def a_delete_governance_control_group(
        self, control_group_id: str
    ) -> GovernanceControlGroupRef:
        """Delete Governance Control Group

        Permanently deletes a governance control group. The controls that were
        in it are not deleted and become ungrouped, and they keep gating exactly
        the projects they gated before, since a group never scoped that.
        **Warning:** This action cannot be undone.

        Args:
            control_group_id: The id of the governance control group.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_GROUP_ENDPOINT,
            response_schema=GovernanceControlGroupRef,
            path={"controlGroupId": control_group_id},
        )
