// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: scheduled-alerts).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import {
  FilterSet,
  ScheduleIntervalUnit,
  ScheduleRecurrenceType,
} from "../common/types";

export enum AlertDataModel {
  TRACE = "TRACE",
  SPAN = "SPAN",
  LLM_SPAN = "LLM_SPAN",
  AGENT_SPAN = "AGENT_SPAN",
  RETRIEVER_SPAN = "RETRIEVER_SPAN",
  TOOL_SPAN = "TOOL_SPAN",
  CUSTOM_SPAN = "CUSTOM_SPAN",
  THREAD = "THREAD",
}

export enum AlertSeverity {
  CRITICAL = "CRITICAL",
  ERROR = "ERROR",
  WARNING = "WARNING",
  INFO = "INFO",
}

export enum AlertThresholdDirection {
  ABOVE = "above",
  BELOW = "below",
}

export interface AlertThresholdSettings {
  value: number;
  direction: AlertThresholdDirection;
}

export interface CreateScheduledAlertRequest {
  recurrence?: ScheduleRecurrenceType;
  repeatEvery?: number | null;
  repeatUnit?: ScheduleIntervalUnit | null;
  startAt?: string | null;
  maxRuns?: number | null;
  endAt?: string | null;
  description?: string | null;
  filters?: FilterSet | null;
  severity?: AlertSeverity;
  name: string;
  dataModel: AlertDataModel;
  aggregation: string;
  thresholdSettings: AlertThresholdSettings;
  enabled?: boolean;
}

export interface ScheduledAlertScheduleSettings {
  recurrence: ScheduleRecurrenceType;
  repeatEvery: number | null;
  repeatUnit: ScheduleIntervalUnit | null;
  startAt: string | null;
  endAt: string | null;
  maxRuns: number | null;
  runCount: number;
  lastRunAt: string | null;
  enabled: boolean;
}

export interface ScheduledAlert {
  id: string;
  name: string;
  description: string | null;
  dataModel: AlertDataModel;
  aggregation: string;
  filters: FilterSet;
  thresholdSettings: AlertThresholdSettings;
  severity: AlertSeverity;
  scheduleSettings: ScheduledAlertScheduleSettings | null;
}

export interface ScheduledAlertSummary {
  id: string;
  name: string;
  dataModel: AlertDataModel;
  enabled: boolean;
}

export interface ScheduledAlertList {
  scheduledAlerts: ScheduledAlertSummary[];
  totalScheduledAlerts: number;
  page: number;
  pageSize: number;
}

export interface ScheduledAlertRef {
  id: string;
}

export interface UpdateScheduledAlertRequest {
  recurrence?: ScheduleRecurrenceType;
  repeatEvery?: number | null;
  repeatUnit?: ScheduleIntervalUnit | null;
  startAt?: string | null;
  maxRuns?: number | null;
  endAt?: string | null;
  description?: string | null;
  filters?: FilterSet | null;
  severity?: AlertSeverity;
  name?: string;
  dataModel?: AlertDataModel;
  aggregation?: string;
  thresholdSettings?: AlertThresholdSettings;
  enabled?: boolean;
}
