# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: evaluate).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Any, Dict, List, Optional, Union

from pydantic import Field

from confidentai.common.types import MLLMImage, PromptType, ToolCall, Turn
from confidentai.types import ConfidentBaseModel


class SingleTurnTestCase(ConfidentBaseModel):
    input: str
    actual_output: Optional[str] = Field(default=None, alias="actualOutput")
    expected_output: Optional[str] = Field(default=None, alias="expectedOutput")
    retrieval_context: Optional[List[str]] = Field(
        default=None,
        alias="retrievalContext",
    )
    tools_called: Optional[List[ToolCall]] = Field(
        default=None,
        alias="toolsCalled",
    )
    expected_tools: Optional[List[ToolCall]] = Field(
        default=None,
        alias="expectedTools",
    )
    context: Optional[List[str]] = None
    token_cost: Optional[float] = Field(default=None, alias="tokenCost")
    input_token_count: Optional[int] = Field(
        default=None,
        alias="inputTokenCount",
    )
    output_token_count: Optional[int] = Field(
        default=None,
        alias="outputTokenCount",
    )
    name: Optional[str] = None
    flaky: Optional[bool] = None
    images_mapping: Optional[Dict[str, MLLMImage]] = Field(
        default=None,
        alias="imagesMapping",
    )
    additional_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        alias="additionalMetadata",
    )
    custom_column_key_values: Optional[Dict[str, str]] = Field(
        default=None,
        alias="customColumnKeyValues",
    )
    tags: Optional[List[str]] = None


class MultiTurnTestCase(ConfidentBaseModel):
    turns: List[Turn]
    scenario: Optional[str] = None
    expected_outcome: Optional[str] = Field(
        default=None,
        alias="expectedOutcome",
    )
    user_description: Optional[str] = Field(
        default=None,
        alias="userDescription",
    )
    chatbot_role: Optional[str] = Field(default=None, alias="chatbotRole")
    context: Optional[List[str]] = None
    token_cost: Optional[float] = Field(default=None, alias="tokenCost")
    input_token_count: Optional[int] = Field(
        default=None,
        alias="inputTokenCount",
    )
    output_token_count: Optional[int] = Field(
        default=None,
        alias="outputTokenCount",
    )
    name: Optional[str] = None
    flaky: Optional[bool] = None
    images_mapping: Optional[Dict[str, MLLMImage]] = Field(
        default=None,
        alias="imagesMapping",
    )
    additional_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        alias="additionalMetadata",
    )
    custom_column_key_values: Optional[Dict[str, str]] = Field(
        default=None,
        alias="customColumnKeyValues",
    )
    tags: Optional[List[str]] = None


TestCase = Union[SingleTurnTestCase, MultiTurnTestCase]


class PromptHyperparameter(ConfidentBaseModel):
    id: str
    type: PromptType


HyperparameterValue = Union[str, PromptHyperparameter]


class EvaluateRequest(ConfidentBaseModel):
    metric_collection: str = Field(alias="metricCollection")
    test_cases: List[TestCase] = Field(alias="testCases")
    hyperparameters: Optional[Dict[str, HyperparameterValue]] = None
    identifier: Optional[str] = None


class EvaluateResult(ConfidentBaseModel):
    id: str


class EvaluateSpanRequest(ConfidentBaseModel):
    metric_collection: str = Field(alias="metricCollection")
    overwrite_metrics: Optional[bool] = Field(
        default=None,
        alias="overwriteMetrics",
    )


class EvaluateSpanResult(ConfidentBaseModel):
    id: str


class EvaluateThreadRequest(ConfidentBaseModel):
    metric_collection: str = Field(alias="metricCollection")
    chatbot_role: Optional[str] = Field(default=None, alias="chatbotRole")
    overwrite_metrics: Optional[bool] = Field(
        default=None,
        alias="overwriteMetrics",
    )


class EvaluateThreadResult(ConfidentBaseModel):
    id: str


class EvaluateTraceRequest(ConfidentBaseModel):
    metric_collection: str = Field(alias="metricCollection")
    overwrite_metrics: Optional[bool] = Field(
        default=None,
        alias="overwriteMetrics",
    )


class EvaluateTraceResult(ConfidentBaseModel):
    id: str
