// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: ai-connections).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import {
  AIConnection,
  AIConnectionKeyValue,
  AIConnectionList,
  AIConnectionPingResult,
  AIConnectionPromptRef,
  AIConnectionRef,
  AIConnectionResponseMode,
  AIConnectionType,
} from "./types";

export class AIConnectionsClient {
  constructor(protected readonly api: Api) {}

  /**
   * List AI Connections
   *
   * Lists the AI connections in your Confident AI project one page at a time,
   * ordered by name. Each connection is returned with just its endpoint and
   * whether it is active; retrieve one by id for its full configuration.
   * Requires the Starter plan or above.
   *
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   */
  async list(page?: number, pageSize?: number): Promise<AIConnectionList> {
    return this.api.sendRequest<AIConnectionList>(
      HttpMethods.GET,
      Endpoints.AI_CONNECTIONS_ENDPOINT,
      { params: { page, pageSize } },
    );
  }

  /**
   * Create AI Connection
   *
   * Registers your LLM application with Confident AI and returns the id of the
   * connection. The endpoint is called once as the connection is created to
   * work out whether it is `active`, which you read back by retrieving the
   * connection or pinging it. Requires the Starter plan or above.
   *
   * @param name The name of the AI connection, unique within the project.
   * @param endpoint The `https://` URL Confident AI calls to reach your LLM
   *   application, or a `wss://` URL when `responseMode` is WEBSOCKET. An
   *   AGENT_HANDLER connection needs none. Send null to clear it.
   * @param responseMode How your application replies. Send null to clear it,
   *   which reads the answer out of a completed HTTP response body.
   * @param asyncResponse Whether your application acknowledges the request and
   *   posts the result back later instead of answering inline. Only a non-
   *   streaming `responseMode` supports this.
   * @param timeout How many seconds to wait for your application to answer
   *   before giving up on a request. Defaults to 60 when the connection is
   *   created. Send null to clear it.
   * @param maxConcurrency The most requests Confident AI sends to your
   *   application at the same time. Send null to leave it unbounded.
   * @param maxRetries How many times a failed request is retried before the
   *   test case is recorded as errored. Send null to clear it.
   * @param defaultNumGenerations How many times your application is called per
   *   test case, so one unlucky output does not decide the result. At most 50.
   * @param headers The headers sent with every request. The list replaces the
   *   stored headers rather than merging into them, so include every header the
   *   connection should keep. Send null to clear them.
   * @param queryParams The query parameters appended to every request. The list
   *   replaces the stored parameters rather than merging into them. Send null
   *   to clear them.
   * @param payload The request body template Confident AI sends. Placeholders
   *   such as `{{input}}` are filled from the test case, and any key in
   *   `prompts` is filled with that prompt's text. Send null to clear it.
   * @param hyperparameters Free-form settings recorded against every test run
   *   made through this connection, so results can be compared across
   *   configurations. They are not sent to your application. Send null to clear
   *   them.
   * @param authentication The authentication configuration Confident AI applies
   *   when calling your application, such as Auth0, HMAC or Azure AD settings.
   *   Its shape follows the scheme you configure, and it is stored as sent and
   *   read back as stored. Send null to clear it.
   * @param cloudProvider The cloud vault configuration Confident AI uses to
   *   pull credentials at call time instead of holding them itself. Its shape
   *   follows the provider you configure, and it is stored as sent and read
   *   back as stored. Send null to clear it.
   * @param actualOutputKeyPath Where your application's answer sits in its
   *   response. Each element is an object key or an array index, walked in
   *   order, so `["choices", 0, "message", "content"]` reads
   *   `choices[0].message.content`. A connection needs this or
   *   `actualOutputTransformerId` before it can be used. Send null or an empty
   *   list to clear it.
   * @param retrievalContextKeyPath Where the retrieved context sits in your
   *   application's response, walked the same way as `actualOutputKeyPath`. Set
   *   it for RAG applications so retrieval metrics have something to score.
   *   Send null or an empty list to clear it.
   * @param toolsCalledKeyPath Where the list of tools your application called
   *   sits in its response, walked the same way as `actualOutputKeyPath`. Set
   *   it for agents so tool-use metrics have something to score. Send null or
   *   an empty list to clear it.
   * @param stateKeyPath Where the conversation state sits in your application's
   *   response, walked the same way as `actualOutputKeyPath`. Confident AI
   *   reads it after each simulated turn and sends it back on the next one.
   *   Send null or an empty list to clear it.
   * @param inputTokenCountKeyPath Where the prompt token count sits in your
   *   application's response, walked the same way as `actualOutputKeyPath`.
   *   Send null or an empty list to clear it.
   * @param outputTokenCountKeyPath Where the completion token count sits in
   *   your application's response, walked the same way as
   *   `actualOutputKeyPath`. Send null or an empty list to clear it.
   * @param tokenCostKeyPath Where the cost of the call sits in your
   *   application's response, walked the same way as `actualOutputKeyPath`.
   *   Send null or an empty list to clear it.
   * @param actualOutputEvent For a streaming `responseMode`, the name of the
   *   event carrying your application's answer. Confident AI reads the value
   *   out of the events with this name instead of out of a completed body,
   *   applying `actualOutputKeyPath` to each one. Send null to clear it.
   * @param retrievalContextEvent For a streaming `responseMode`, the name of
   *   the event carrying the retrieved context, read the same way as
   *   `actualOutputEvent`. Send null to clear it.
   * @param toolsCalledEvent For a streaming `responseMode`, the name of the
   *   event carrying the tools called, read the same way as
   *   `actualOutputEvent`. Send null to clear it.
   * @param stateEvent For a streaming `responseMode`, the name of the event
   *   carrying the conversation state, read the same way as
   *   `actualOutputEvent`. Send null to clear it.
   * @param actualOutputAccumulate For a streaming `responseMode`, whether the
   *   chunks arriving on `actualOutputEvent` are joined into one answer. Set it
   *   to false when each event already carries the whole answer and only the
   *   last one counts.
   * @param actualOutputTransformerId The id of a transformer that extracts the
   *   answer by running your code over the response, for shapes a key path
   *   cannot reach. Send this or `actualOutputKeyPath`, never both. The
   *   transformer must belong to this project. Send null to clear it.
   * @param retrievalContextTransformerId The id of a transformer that extracts
   *   the retrieved context. Send this or `retrievalContextKeyPath`, never
   *   both. Send null to clear it.
   * @param toolsCalledTransformerId The id of a transformer that extracts the
   *   tools called. Send this or `toolsCalledKeyPath`, never both. Send null to
   *   clear it.
   * @param stateTransformerId The id of a transformer that extracts the
   *   conversation state. Send this or `stateKeyPath`, never both. Send null to
   *   clear it.
   * @param inputTokenCountTransformerId The id of a transformer that extracts
   *   the prompt token count. Send this or `inputTokenCountKeyPath`, never
   *   both. Send null to clear it.
   * @param outputTokenCountTransformerId The id of a transformer that extracts
   *   the completion token count. Send this or `outputTokenCountKeyPath`, never
   *   both. Send null to clear it.
   * @param tokenCostTransformerId The id of a transformer that extracts the
   *   cost of the call. Send this or `tokenCostKeyPath`, never both. Send null
   *   to clear it.
   * @param prompts The prompts to substitute into the request body, keyed by
   *   the placeholder they fill in `payload`. The map replaces the connection's
   *   current prompts rather than merging into them.
   */
  async create(
    name: string,
    options: {
      type?: AIConnectionType;
      endpoint?: string | null;
      responseMode?: AIConnectionResponseMode | null;
      asyncResponse?: boolean;
      timeout?: number | null;
      maxConcurrency?: number | null;
      maxRetries?: number | null;
      defaultNumGenerations?: number;
      headers?: AIConnectionKeyValue[] | null;
      queryParams?: AIConnectionKeyValue[] | null;
      payload?: Record<string, unknown> | null;
      hyperparameters?: Record<string, unknown> | null;
      authentication?: Record<string, unknown> | null;
      cloudProvider?: Record<string, unknown> | null;
      actualOutputKeyPath?: (string | number)[] | null;
      retrievalContextKeyPath?: (string | number)[] | null;
      toolsCalledKeyPath?: (string | number)[] | null;
      stateKeyPath?: (string | number)[] | null;
      inputTokenCountKeyPath?: (string | number)[] | null;
      outputTokenCountKeyPath?: (string | number)[] | null;
      tokenCostKeyPath?: (string | number)[] | null;
      actualOutputEvent?: string | null;
      retrievalContextEvent?: string | null;
      toolsCalledEvent?: string | null;
      stateEvent?: string | null;
      actualOutputAccumulate?: boolean;
      actualOutputTransformerId?: string | null;
      retrievalContextTransformerId?: string | null;
      toolsCalledTransformerId?: string | null;
      stateTransformerId?: string | null;
      inputTokenCountTransformerId?: string | null;
      outputTokenCountTransformerId?: string | null;
      tokenCostTransformerId?: string | null;
      prompts?: Record<string, AIConnectionPromptRef> | null;
    } = {},
  ): Promise<AIConnectionRef> {
    const {
      type,
      endpoint,
      responseMode,
      asyncResponse,
      timeout,
      maxConcurrency,
      maxRetries,
      defaultNumGenerations,
      headers,
      queryParams,
      payload,
      hyperparameters,
      authentication,
      cloudProvider,
      actualOutputKeyPath,
      retrievalContextKeyPath,
      toolsCalledKeyPath,
      stateKeyPath,
      inputTokenCountKeyPath,
      outputTokenCountKeyPath,
      tokenCostKeyPath,
      actualOutputEvent,
      retrievalContextEvent,
      toolsCalledEvent,
      stateEvent,
      actualOutputAccumulate,
      actualOutputTransformerId,
      retrievalContextTransformerId,
      toolsCalledTransformerId,
      stateTransformerId,
      inputTokenCountTransformerId,
      outputTokenCountTransformerId,
      tokenCostTransformerId,
      prompts,
    } = options;
    return this.api.sendRequest<AIConnectionRef>(
      HttpMethods.POST,
      Endpoints.AI_CONNECTIONS_ENDPOINT,
      {
        body: {
          name,
          type,
          endpoint,
          responseMode,
          asyncResponse,
          timeout,
          maxConcurrency,
          maxRetries,
          defaultNumGenerations,
          headers,
          queryParams,
          payload,
          hyperparameters,
          authentication,
          cloudProvider,
          actualOutputKeyPath,
          retrievalContextKeyPath,
          toolsCalledKeyPath,
          stateKeyPath,
          inputTokenCountKeyPath,
          outputTokenCountKeyPath,
          tokenCostKeyPath,
          actualOutputEvent,
          retrievalContextEvent,
          toolsCalledEvent,
          stateEvent,
          actualOutputAccumulate,
          actualOutputTransformerId,
          retrievalContextTransformerId,
          toolsCalledTransformerId,
          stateTransformerId,
          inputTokenCountTransformerId,
          outputTokenCountTransformerId,
          tokenCostTransformerId,
          prompts,
        },
      },
    );
  }

  /**
   * Get AI Connection
   *
   * Retrieves an AI connection by id with its full configuration: how Confident
   * AI calls your application, and where in the response each evaluated value
   * is read from. The stored `headers`, `queryParams`, `authentication` and
   * `cloudProvider` are returned exactly as they were saved, so treat the
   * response as carrying credentials.
   *
   * @param aiConnectionId The id of the AI connection.
   */
  async get(aiConnectionId: string): Promise<AIConnection> {
    return this.api.sendRequest<AIConnection>(
      HttpMethods.GET,
      Endpoints.AI_CONNECTION_ENDPOINT,
      { urlParams: { aiConnectionId } },
    );
  }

  /**
   * Update AI Connection
   *
   * Changes an AI connection and returns it. Only the fields you send are
   * touched, and `headers`, `queryParams` and `prompts` each replace the stored
   * collection rather than merging into it. Changing anything that affects how
   * your application is called re-tests the connection, so `active` in the
   * response is the fresh verdict.
   *
   * @param aiConnectionId The id of the AI connection.
   * @param name The name of the AI connection, unique within the project.
   * @param endpoint The `https://` URL Confident AI calls to reach your LLM
   *   application, or a `wss://` URL when `responseMode` is WEBSOCKET. An
   *   AGENT_HANDLER connection needs none. Send null to clear it.
   * @param responseMode How your application replies. Send null to clear it,
   *   which reads the answer out of a completed HTTP response body.
   * @param asyncResponse Whether your application acknowledges the request and
   *   posts the result back later instead of answering inline. Only a non-
   *   streaming `responseMode` supports this.
   * @param timeout How many seconds to wait for your application to answer
   *   before giving up on a request. Defaults to 60 when the connection is
   *   created. Send null to clear it.
   * @param maxConcurrency The most requests Confident AI sends to your
   *   application at the same time. Send null to leave it unbounded.
   * @param maxRetries How many times a failed request is retried before the
   *   test case is recorded as errored. Send null to clear it.
   * @param defaultNumGenerations How many times your application is called per
   *   test case, so one unlucky output does not decide the result. At most 50.
   * @param headers The headers sent with every request. The list replaces the
   *   stored headers rather than merging into them, so include every header the
   *   connection should keep. Send null to clear them.
   * @param queryParams The query parameters appended to every request. The list
   *   replaces the stored parameters rather than merging into them. Send null
   *   to clear them.
   * @param payload The request body template Confident AI sends. Placeholders
   *   such as `{{input}}` are filled from the test case, and any key in
   *   `prompts` is filled with that prompt's text. Send null to clear it.
   * @param hyperparameters Free-form settings recorded against every test run
   *   made through this connection, so results can be compared across
   *   configurations. They are not sent to your application. Send null to clear
   *   them.
   * @param authentication The authentication configuration Confident AI applies
   *   when calling your application, such as Auth0, HMAC or Azure AD settings.
   *   Its shape follows the scheme you configure, and it is stored as sent and
   *   read back as stored. Send null to clear it.
   * @param cloudProvider The cloud vault configuration Confident AI uses to
   *   pull credentials at call time instead of holding them itself. Its shape
   *   follows the provider you configure, and it is stored as sent and read
   *   back as stored. Send null to clear it.
   * @param actualOutputKeyPath Where your application's answer sits in its
   *   response. Each element is an object key or an array index, walked in
   *   order, so `["choices", 0, "message", "content"]` reads
   *   `choices[0].message.content`. A connection needs this or
   *   `actualOutputTransformerId` before it can be used. Send null or an empty
   *   list to clear it.
   * @param retrievalContextKeyPath Where the retrieved context sits in your
   *   application's response, walked the same way as `actualOutputKeyPath`. Set
   *   it for RAG applications so retrieval metrics have something to score.
   *   Send null or an empty list to clear it.
   * @param toolsCalledKeyPath Where the list of tools your application called
   *   sits in its response, walked the same way as `actualOutputKeyPath`. Set
   *   it for agents so tool-use metrics have something to score. Send null or
   *   an empty list to clear it.
   * @param stateKeyPath Where the conversation state sits in your application's
   *   response, walked the same way as `actualOutputKeyPath`. Confident AI
   *   reads it after each simulated turn and sends it back on the next one.
   *   Send null or an empty list to clear it.
   * @param inputTokenCountKeyPath Where the prompt token count sits in your
   *   application's response, walked the same way as `actualOutputKeyPath`.
   *   Send null or an empty list to clear it.
   * @param outputTokenCountKeyPath Where the completion token count sits in
   *   your application's response, walked the same way as
   *   `actualOutputKeyPath`. Send null or an empty list to clear it.
   * @param tokenCostKeyPath Where the cost of the call sits in your
   *   application's response, walked the same way as `actualOutputKeyPath`.
   *   Send null or an empty list to clear it.
   * @param actualOutputEvent For a streaming `responseMode`, the name of the
   *   event carrying your application's answer. Confident AI reads the value
   *   out of the events with this name instead of out of a completed body,
   *   applying `actualOutputKeyPath` to each one. Send null to clear it.
   * @param retrievalContextEvent For a streaming `responseMode`, the name of
   *   the event carrying the retrieved context, read the same way as
   *   `actualOutputEvent`. Send null to clear it.
   * @param toolsCalledEvent For a streaming `responseMode`, the name of the
   *   event carrying the tools called, read the same way as
   *   `actualOutputEvent`. Send null to clear it.
   * @param stateEvent For a streaming `responseMode`, the name of the event
   *   carrying the conversation state, read the same way as
   *   `actualOutputEvent`. Send null to clear it.
   * @param actualOutputAccumulate For a streaming `responseMode`, whether the
   *   chunks arriving on `actualOutputEvent` are joined into one answer. Set it
   *   to false when each event already carries the whole answer and only the
   *   last one counts.
   * @param actualOutputTransformerId The id of a transformer that extracts the
   *   answer by running your code over the response, for shapes a key path
   *   cannot reach. Send this or `actualOutputKeyPath`, never both. The
   *   transformer must belong to this project. Send null to clear it.
   * @param retrievalContextTransformerId The id of a transformer that extracts
   *   the retrieved context. Send this or `retrievalContextKeyPath`, never
   *   both. Send null to clear it.
   * @param toolsCalledTransformerId The id of a transformer that extracts the
   *   tools called. Send this or `toolsCalledKeyPath`, never both. Send null to
   *   clear it.
   * @param stateTransformerId The id of a transformer that extracts the
   *   conversation state. Send this or `stateKeyPath`, never both. Send null to
   *   clear it.
   * @param inputTokenCountTransformerId The id of a transformer that extracts
   *   the prompt token count. Send this or `inputTokenCountKeyPath`, never
   *   both. Send null to clear it.
   * @param outputTokenCountTransformerId The id of a transformer that extracts
   *   the completion token count. Send this or `outputTokenCountKeyPath`, never
   *   both. Send null to clear it.
   * @param tokenCostTransformerId The id of a transformer that extracts the
   *   cost of the call. Send this or `tokenCostKeyPath`, never both. Send null
   *   to clear it.
   * @param prompts The prompts to substitute into the request body, keyed by
   *   the placeholder they fill in `payload`. The map replaces the connection's
   *   current prompts rather than merging into them.
   */
  async update(
    aiConnectionId: string,
    options: {
      name?: string;
      type?: AIConnectionType;
      endpoint?: string | null;
      responseMode?: AIConnectionResponseMode | null;
      asyncResponse?: boolean;
      timeout?: number | null;
      maxConcurrency?: number | null;
      maxRetries?: number | null;
      defaultNumGenerations?: number;
      headers?: AIConnectionKeyValue[] | null;
      queryParams?: AIConnectionKeyValue[] | null;
      payload?: Record<string, unknown> | null;
      hyperparameters?: Record<string, unknown> | null;
      authentication?: Record<string, unknown> | null;
      cloudProvider?: Record<string, unknown> | null;
      actualOutputKeyPath?: (string | number)[] | null;
      retrievalContextKeyPath?: (string | number)[] | null;
      toolsCalledKeyPath?: (string | number)[] | null;
      stateKeyPath?: (string | number)[] | null;
      inputTokenCountKeyPath?: (string | number)[] | null;
      outputTokenCountKeyPath?: (string | number)[] | null;
      tokenCostKeyPath?: (string | number)[] | null;
      actualOutputEvent?: string | null;
      retrievalContextEvent?: string | null;
      toolsCalledEvent?: string | null;
      stateEvent?: string | null;
      actualOutputAccumulate?: boolean;
      actualOutputTransformerId?: string | null;
      retrievalContextTransformerId?: string | null;
      toolsCalledTransformerId?: string | null;
      stateTransformerId?: string | null;
      inputTokenCountTransformerId?: string | null;
      outputTokenCountTransformerId?: string | null;
      tokenCostTransformerId?: string | null;
      prompts?: Record<string, AIConnectionPromptRef> | null;
    } = {},
  ): Promise<AIConnection> {
    const {
      name,
      type,
      endpoint,
      responseMode,
      asyncResponse,
      timeout,
      maxConcurrency,
      maxRetries,
      defaultNumGenerations,
      headers,
      queryParams,
      payload,
      hyperparameters,
      authentication,
      cloudProvider,
      actualOutputKeyPath,
      retrievalContextKeyPath,
      toolsCalledKeyPath,
      stateKeyPath,
      inputTokenCountKeyPath,
      outputTokenCountKeyPath,
      tokenCostKeyPath,
      actualOutputEvent,
      retrievalContextEvent,
      toolsCalledEvent,
      stateEvent,
      actualOutputAccumulate,
      actualOutputTransformerId,
      retrievalContextTransformerId,
      toolsCalledTransformerId,
      stateTransformerId,
      inputTokenCountTransformerId,
      outputTokenCountTransformerId,
      tokenCostTransformerId,
      prompts,
    } = options;
    return this.api.sendRequest<AIConnection>(
      HttpMethods.PUT,
      Endpoints.AI_CONNECTION_ENDPOINT,
      {
        body: {
          name,
          type,
          endpoint,
          responseMode,
          asyncResponse,
          timeout,
          maxConcurrency,
          maxRetries,
          defaultNumGenerations,
          headers,
          queryParams,
          payload,
          hyperparameters,
          authentication,
          cloudProvider,
          actualOutputKeyPath,
          retrievalContextKeyPath,
          toolsCalledKeyPath,
          stateKeyPath,
          inputTokenCountKeyPath,
          outputTokenCountKeyPath,
          tokenCostKeyPath,
          actualOutputEvent,
          retrievalContextEvent,
          toolsCalledEvent,
          stateEvent,
          actualOutputAccumulate,
          actualOutputTransformerId,
          retrievalContextTransformerId,
          toolsCalledTransformerId,
          stateTransformerId,
          inputTokenCountTransformerId,
          outputTokenCountTransformerId,
          tokenCostTransformerId,
          prompts,
        },
        urlParams: { aiConnectionId },
      },
    );
  }

  /**
   * Delete AI Connection
   *
   * Permanently deletes an AI connection. Anything scheduled against it, such
   * as a dataset run or a risk assessment, stops running.
   *
   * @param aiConnectionId The id of the AI connection.
   */
  async delete(aiConnectionId: string): Promise<AIConnectionRef> {
    return this.api.sendRequest<AIConnectionRef>(
      HttpMethods.DELETE,
      Endpoints.AI_CONNECTION_ENDPOINT,
      { urlParams: { aiConnectionId } },
    );
  }

  /**
   * Ping AI Connection
   *
   * Calls your LLM application once with a sample test case and reports what
   * came back, including what each configured key path or transformer managed
   * to extract. Use it to confirm a connection works before running an
   * evaluation through it. The verdict replaces the connection's stored
   * `active`. A ping that fails is still a 200 response: read `active` and
   * `error` in the body rather than the status code.
   *
   * @param aiConnectionId The id of the AI connection.
   * @param multiturn Whether to test the connection over a simulated multi-turn
   *   conversation instead of a single call. Defaults to false.
   */
  async ping(
    aiConnectionId: string,
    multiturn?: boolean,
  ): Promise<AIConnectionPingResult> {
    return this.api.sendRequest<AIConnectionPingResult>(
      HttpMethods.POST,
      Endpoints.AI_CONNECTION_PING_ENDPOINT,
      { body: { multiturn }, urlParams: { aiConnectionId } },
    );
  }
}
