// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: classifiers).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { ClassifiersOperations } from "../operations";
import {
  ClassifierLabel,
  ClassifierLabelList,
  ClassifierLabelRef,
  ClassifierLabelStatus,
  SignalPolarity,
} from "../types";

export class LabelsOperations extends ClassifiersOperations {
  /**
   * List Classifier Labels
   *
   * Lists a classifier's labels one page at a time, ordered by name. This is
   * also how you read the results of a generation run — generated suggestions
   * arrive with status RECOMMENDED. Each label is returned as a summary row;
   * retrieve one by id for its description and polarity. Requires the Starter
   * plan or above.
   *
   * @param classifierId The id of the classifier.
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   */
  async listLabels(
    classifierId: string,
    page?: number,
    pageSize?: number,
  ): Promise<ClassifierLabelList> {
    return this.api.sendRequest<ClassifierLabelList>(
      HttpMethods.GET,
      Endpoints.CLASSIFIER_LABELS_ENDPOINT,
      { urlParams: { classifierId }, params: { page, pageSize } },
    );
  }

  /**
   * Create Classifier Label
   *
   * Adds a label to a classifier and returns its id. The `description` is what
   * the classifying model matches against, so write it as a clear statement of
   * when the label applies rather than a restatement of the name. Label names
   * are unique within a classifier. Requires the Starter plan or above.
   *
   * @param classifierId The id of the classifier.
   * @param name The name of the label, unique within the classifier.
   * @param description When this label applies. It is the instruction the
   *   classifying model reads, so state the condition rather than restating the
   *   name.
   * @param enabled Whether the label can be applied. Defaults to true.
   */
  async createLabel(
    classifierId: string,
    name: string,
    description: string,
    options: {
      enabled?: boolean;
      status?: ClassifierLabelStatus;
      polarity?: SignalPolarity;
    } = {},
  ): Promise<ClassifierLabelRef> {
    const { enabled, status, polarity } = options;
    return this.api.sendRequest<ClassifierLabelRef>(
      HttpMethods.POST,
      Endpoints.CLASSIFIER_LABELS_ENDPOINT,
      {
        body: { name, description, enabled, status, polarity },
        urlParams: { classifierId },
      },
    );
  }

  /**
   * Get Classifier Label
   *
   * Retrieves a single label on a classifier, with the description the
   * classifying model matches against and the polarity trend reporting uses.
   * Requires the Starter plan or above.
   *
   * @param classifierId The id of the classifier the label belongs to.
   * @param labelId The id of the label.
   */
  async getLabel(
    classifierId: string,
    labelId: string,
  ): Promise<ClassifierLabel> {
    return this.api.sendRequest<ClassifierLabel>(
      HttpMethods.GET,
      Endpoints.CLASSIFIER_LABEL_ENDPOINT,
      { urlParams: { classifierId, labelId } },
    );
  }

  /**
   * Update Classifier Label
   *
   * Updates a label on a classifier and returns it. Only the fields you send
   * are changed. Promoting a generated suggestion is an update to status
   * ACTIVE, which also enables the label. Requires the Starter plan or above.
   *
   * @param classifierId The id of the classifier the label belongs to.
   * @param labelId The id of the label.
   * @param name The name of the label, unique within the classifier.
   * @param description When this label applies. It cannot be cleared.
   * @param enabled Whether the label can be applied. Defaults to true.
   */
  async updateLabel(
    classifierId: string,
    labelId: string,
    options: {
      name?: string;
      description?: string;
      enabled?: boolean;
      status?: ClassifierLabelStatus;
      polarity?: SignalPolarity;
    } = {},
  ): Promise<ClassifierLabel> {
    const { name, description, enabled, status, polarity } = options;
    return this.api.sendRequest<ClassifierLabel>(
      HttpMethods.PUT,
      Endpoints.CLASSIFIER_LABEL_ENDPOINT,
      {
        body: { name, description, enabled, status, polarity },
        urlParams: { classifierId, labelId },
      },
    );
  }

  /**
   * Delete Classifier Label
   *
   * Permanently deletes a label from a classifier and returns its id.
   * Classifications already applied with it are not removed. This action cannot
   * be undone. Requires the Starter plan or above.
   *
   * @param classifierId The id of the classifier the label belongs to.
   * @param labelId The id of the label.
   */
  async deleteLabel(
    classifierId: string,
    labelId: string,
  ): Promise<ClassifierLabelRef> {
    return this.api.sendRequest<ClassifierLabelRef>(
      HttpMethods.DELETE,
      Endpoints.CLASSIFIER_LABEL_ENDPOINT,
      { urlParams: { classifierId, labelId } },
    );
  }
}
