# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: rt-frameworks).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import List, Optional

from confidentai.api import Api, HttpMethods
from confidentai.common.types import GenerationMode, Level
from confidentai.endpoints import Endpoints
from confidentai.rt_frameworks.types import (
    AttackEngine,
    CreateRTFrameworkRequest,
    RTFramework,
    RTFrameworkList,
    RTFrameworkRef,
    RiskAssessmentRef,
    RunRTFrameworkRequest,
    UpdateRTFrameworkRequest,
)


class RTFrameworksOperations:
    _api: Api

    def list(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> RTFrameworkList:
        """List RT Frameworks

        Lists the red teaming frameworks in your Confident AI project one page
        at a time, ordered by name. Each framework is returned with its risk
        categories counted; retrieve one by id to see what those categories
        select.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.RT_FRAMEWORKS_ENDPOINT,
            response_schema=RTFrameworkList,
            query={"page": page, "pageSize": page_size},
        )

    async def a_list(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> RTFrameworkList:
        """List RT Frameworks

        Lists the red teaming frameworks in your Confident AI project one page
        at a time, ordered by name. Each framework is returned with its risk
        categories counted; retrieve one by id to see what those categories
        select.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.RT_FRAMEWORKS_ENDPOINT,
            response_schema=RTFrameworkList,
            query={"page": page, "pageSize": page_size},
        )

    def create(
        self,
        name: str,
        *,
        description: Optional[str] = None,
        template: Optional[str] = None
    ) -> RTFrameworkRef:
        """Create RT Framework

        Creates a red teaming framework in your Confident AI project and returns
        its id. Send `template` to fill it from a Confident AI template, which
        creates its risk categories with vulnerability types and attack methods
        already selected.

        Args:
            name: The name of the framework, unique within the project.
            description: What the framework covers. Send null to leave it unset.
            template: A Confident AI template to fill the framework from, which
                creates its risk categories with vulnerability types and attack
                methods already selected. Omit it for an empty framework.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.RT_FRAMEWORKS_ENDPOINT,
            response_schema=RTFrameworkRef,
            request_schema=CreateRTFrameworkRequest,
            body={
                "name": name,
                "description": description,
                "template": template,
            },
        )

    async def a_create(
        self,
        name: str,
        *,
        description: Optional[str] = None,
        template: Optional[str] = None
    ) -> RTFrameworkRef:
        """Create RT Framework

        Creates a red teaming framework in your Confident AI project and returns
        its id. Send `template` to fill it from a Confident AI template, which
        creates its risk categories with vulnerability types and attack methods
        already selected.

        Args:
            name: The name of the framework, unique within the project.
            description: What the framework covers. Send null to leave it unset.
            template: A Confident AI template to fill the framework from, which
                creates its risk categories with vulnerability types and attack
                methods already selected. Omit it for an empty framework.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.RT_FRAMEWORKS_ENDPOINT,
            response_schema=RTFrameworkRef,
            request_schema=CreateRTFrameworkRequest,
            body={
                "name": name,
                "description": description,
                "template": template,
            },
        )

    def get(self, rt_framework_id: str) -> RTFramework:
        """Get RT Framework

        Retrieves a red teaming framework by id, with each risk category
        resolved to the vulnerabilities it probes for and the attack methods it
        probes with, exactly as a run would use them.

        Args:
            rt_framework_id: The id of the red teaming framework.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.RT_FRAMEWORK_ENDPOINT,
            response_schema=RTFramework,
            path={"rtFrameworkId": rt_framework_id},
        )

    async def a_get(self, rt_framework_id: str) -> RTFramework:
        """Get RT Framework

        Retrieves a red teaming framework by id, with each risk category
        resolved to the vulnerabilities it probes for and the attack methods it
        probes with, exactly as a run would use them.

        Args:
            rt_framework_id: The id of the red teaming framework.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.RT_FRAMEWORK_ENDPOINT,
            response_schema=RTFramework,
            path={"rtFrameworkId": rt_framework_id},
        )

    def update(
        self,
        rt_framework_id: str,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None
    ) -> RTFramework:
        """Update RT Framework

        Renames a red teaming framework or changes its description, and returns
        it. Its risk categories are managed through their own endpoints.

        Args:
            rt_framework_id: The id of the red teaming framework.
            name: The name of the framework, unique within the project.
            description: What the framework covers. Send null to clear it.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.RT_FRAMEWORK_ENDPOINT,
            response_schema=RTFramework,
            request_schema=UpdateRTFrameworkRequest,
            body={"name": name, "description": description},
            path={"rtFrameworkId": rt_framework_id},
        )

    async def a_update(
        self,
        rt_framework_id: str,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None
    ) -> RTFramework:
        """Update RT Framework

        Renames a red teaming framework or changes its description, and returns
        it. Its risk categories are managed through their own endpoints.

        Args:
            rt_framework_id: The id of the red teaming framework.
            name: The name of the framework, unique within the project.
            description: What the framework covers. Send null to clear it.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.RT_FRAMEWORK_ENDPOINT,
            response_schema=RTFramework,
            request_schema=UpdateRTFrameworkRequest,
            body={"name": name, "description": description},
            path={"rtFrameworkId": rt_framework_id},
        )

    def delete(self, rt_framework_id: str) -> RTFrameworkRef:
        """Delete RT Framework

        Permanently deletes a red teaming framework and its risk categories.
        Risk assessments already run from it are kept.

        Args:
            rt_framework_id: The id of the red teaming framework.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.RT_FRAMEWORK_ENDPOINT,
            response_schema=RTFrameworkRef,
            path={"rtFrameworkId": rt_framework_id},
        )

    async def a_delete(self, rt_framework_id: str) -> RTFrameworkRef:
        """Delete RT Framework

        Permanently deletes a red teaming framework and its risk categories.
        Risk assessments already run from it are kept.

        Args:
            rt_framework_id: The id of the red teaming framework.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.RT_FRAMEWORK_ENDPOINT,
            response_schema=RTFrameworkRef,
            path={"rtFrameworkId": rt_framework_id},
        )

    def run(
        self,
        rt_framework_id: str,
        risk_categories: List[str],
        exposure: Level,
        *,
        identifier: Optional[str] = None,
        ai_connection_id: Optional[str] = None,
        prompt_alias: Optional[str] = None,
        prompt_commit: Optional[str] = None,
        generation_mode: Optional[GenerationMode] = None,
        attack_engine: Optional[AttackEngine] = None
    ) -> RiskAssessmentRef:
        """Run RT Framework

        Runs the named risk categories of a red teaming framework against your
        AI connection or prompt, and returns the id of the risk assessment it
        started. The assessment runs in the background; follow it on the
        Confident AI platform. Provide exactly one target: `aiConnectionId` or
        `promptAlias`.

        Args:
            rt_framework_id: The id of the red teaming framework.
            risk_categories: The names of the framework's risk categories to
                run. Every name must belong to this framework.
            identifier: A human-readable identifier for the risk assessment,
                shown on the Confident AI platform.
            ai_connection_id: The id of the AI connection to attack. Send this
                or `promptAlias`, never both.
            prompt_alias: The alias of the prompt to attack. Send this or
                `aiConnectionId`, never both.
            prompt_commit: The commit hash of the prompt to attack. Requires
                `promptAlias`; defaults to its latest commit.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.RT_FRAMEWORK_RUN_ENDPOINT,
            response_schema=RiskAssessmentRef,
            request_schema=RunRTFrameworkRequest,
            body={
                "riskCategories": risk_categories,
                "exposure": exposure,
                "identifier": identifier,
                "aiConnectionId": ai_connection_id,
                "promptAlias": prompt_alias,
                "promptCommit": prompt_commit,
                "generationMode": generation_mode,
                "attackEngine": attack_engine,
            },
            path={"rtFrameworkId": rt_framework_id},
        )

    async def a_run(
        self,
        rt_framework_id: str,
        risk_categories: List[str],
        exposure: Level,
        *,
        identifier: Optional[str] = None,
        ai_connection_id: Optional[str] = None,
        prompt_alias: Optional[str] = None,
        prompt_commit: Optional[str] = None,
        generation_mode: Optional[GenerationMode] = None,
        attack_engine: Optional[AttackEngine] = None
    ) -> RiskAssessmentRef:
        """Run RT Framework

        Runs the named risk categories of a red teaming framework against your
        AI connection or prompt, and returns the id of the risk assessment it
        started. The assessment runs in the background; follow it on the
        Confident AI platform. Provide exactly one target: `aiConnectionId` or
        `promptAlias`.

        Args:
            rt_framework_id: The id of the red teaming framework.
            risk_categories: The names of the framework's risk categories to
                run. Every name must belong to this framework.
            identifier: A human-readable identifier for the risk assessment,
                shown on the Confident AI platform.
            ai_connection_id: The id of the AI connection to attack. Send this
                or `promptAlias`, never both.
            prompt_alias: The alias of the prompt to attack. Send this or
                `aiConnectionId`, never both.
            prompt_commit: The commit hash of the prompt to attack. Requires
                `promptAlias`; defaults to its latest commit.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.RT_FRAMEWORK_RUN_ENDPOINT,
            response_schema=RiskAssessmentRef,
            request_schema=RunRTFrameworkRequest,
            body={
                "riskCategories": risk_categories,
                "exposure": exposure,
                "identifier": identifier,
                "aiConnectionId": ai_connection_id,
                "promptAlias": prompt_alias,
                "promptCommit": prompt_commit,
                "generationMode": generation_mode,
                "attackEngine": attack_engine,
            },
            path={"rtFrameworkId": rt_framework_id},
        )
