# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: annotation-queues).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import List, Optional

from confidentai.annotation_queues.types import (
    AssignmentStrategy,
    CreateQueueIngestionTaskRequest,
    QueueIngestionTask,
    QueueIngestionTaskList,
    QueueIngestionTaskRef,
    UpdateQueueIngestionTaskRequest,
)
from confidentai.api import Api, HttpMethods
from confidentai.common.types import FilterSet, IngestionDataModel
from confidentai.endpoints import Endpoints


class QueueIngestionTasksOperations:
    _api: Api

    def list_queue_ingestion_tasks(
        self,
        annotation_queue_id: str,
        *,
        data_model: Optional[IngestionDataModel] = None
    ) -> QueueIngestionTaskList:
        """List Queue Ingestion Tasks

        Lists the ingestion tasks filling an annotation queue, newest first.
        Each task is returned as a summary; retrieve a task by id for its
        filters and reviewers.

        Args:
            annotation_queue_id: The id of the annotation queue.
            data_model: Returns only tasks harvesting this kind of production
                item.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASKS_ENDPOINT,
            response_schema=QueueIngestionTaskList,
            path={"annotationQueueId": annotation_queue_id},
            query={"dataModel": data_model},
        )

    async def a_list_queue_ingestion_tasks(
        self,
        annotation_queue_id: str,
        *,
        data_model: Optional[IngestionDataModel] = None
    ) -> QueueIngestionTaskList:
        """List Queue Ingestion Tasks

        Lists the ingestion tasks filling an annotation queue, newest first.
        Each task is returned as a summary; retrieve a task by id for its
        filters and reviewers.

        Args:
            annotation_queue_id: The id of the annotation queue.
            data_model: Returns only tasks harvesting this kind of production
                item.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASKS_ENDPOINT,
            response_schema=QueueIngestionTaskList,
            path={"annotationQueueId": annotation_queue_id},
            query={"dataModel": data_model},
        )

    def create_queue_ingestion_task(
        self,
        annotation_queue_id: str,
        name: str,
        data_model: IngestionDataModel,
        *,
        description: Optional[str] = None,
        enabled: Optional[bool] = None,
        sample_rate: Optional[float] = None,
        filters: Optional[FilterSet] = None,
        max_items: Optional[int] = None,
        assignment_strategy: Optional[AssignmentStrategy] = None,
        reviewer_emails: Optional[List[str]] = None
    ) -> QueueIngestionTaskRef:
        """Create Queue Ingestion Task

        Creates a rule that keeps an annotation queue filled from your
        production data, and returns its id. A task only harvests once `enabled`
        is true.

        Args:
            annotation_queue_id: The id of the annotation queue.
            name: The name of the task.
            description: A note about what the task harvests. Send null to clear
                it.
            enabled: Whether the task runs. Disabling it stops new items
                arriving; items already queued are kept. Defaults to false.
            sample_rate: The fraction of matching items to queue, between 0 and
                1. Defaults to 1, all of them.
            max_items: The maximum number of items this task will ever queue.
                Send null to remove the cap.
            reviewer_emails: The project members harvested items are assigned
                to, following `assignmentStrategy`.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASKS_ENDPOINT,
            response_schema=QueueIngestionTaskRef,
            request_schema=CreateQueueIngestionTaskRequest,
            body={
                "name": name,
                "dataModel": data_model,
                "description": description,
                "enabled": enabled,
                "sampleRate": sample_rate,
                "filters": filters,
                "maxItems": max_items,
                "assignmentStrategy": assignment_strategy,
                "reviewerEmails": reviewer_emails,
            },
            path={"annotationQueueId": annotation_queue_id},
        )

    async def a_create_queue_ingestion_task(
        self,
        annotation_queue_id: str,
        name: str,
        data_model: IngestionDataModel,
        *,
        description: Optional[str] = None,
        enabled: Optional[bool] = None,
        sample_rate: Optional[float] = None,
        filters: Optional[FilterSet] = None,
        max_items: Optional[int] = None,
        assignment_strategy: Optional[AssignmentStrategy] = None,
        reviewer_emails: Optional[List[str]] = None
    ) -> QueueIngestionTaskRef:
        """Create Queue Ingestion Task

        Creates a rule that keeps an annotation queue filled from your
        production data, and returns its id. A task only harvests once `enabled`
        is true.

        Args:
            annotation_queue_id: The id of the annotation queue.
            name: The name of the task.
            description: A note about what the task harvests. Send null to clear
                it.
            enabled: Whether the task runs. Disabling it stops new items
                arriving; items already queued are kept. Defaults to false.
            sample_rate: The fraction of matching items to queue, between 0 and
                1. Defaults to 1, all of them.
            max_items: The maximum number of items this task will ever queue.
                Send null to remove the cap.
            reviewer_emails: The project members harvested items are assigned
                to, following `assignmentStrategy`.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASKS_ENDPOINT,
            response_schema=QueueIngestionTaskRef,
            request_schema=CreateQueueIngestionTaskRequest,
            body={
                "name": name,
                "dataModel": data_model,
                "description": description,
                "enabled": enabled,
                "sampleRate": sample_rate,
                "filters": filters,
                "maxItems": max_items,
                "assignmentStrategy": assignment_strategy,
                "reviewerEmails": reviewer_emails,
            },
            path={"annotationQueueId": annotation_queue_id},
        )

    def get_queue_ingestion_task(
        self, annotation_queue_id: str, queue_ingestion_task_id: str
    ) -> QueueIngestionTask:
        """Get Queue Ingestion Task

        Retrieves an ingestion task by id, with the filters an item must match
        to be queued and the reviewers harvested items are assigned to.

        Args:
            annotation_queue_id: The id of the annotation queue the task fills.
            queue_ingestion_task_id: The id of the queue ingestion task.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
            response_schema=QueueIngestionTask,
            path={
                "annotationQueueId": annotation_queue_id,
                "queueIngestionTaskId": queue_ingestion_task_id,
            },
        )

    async def a_get_queue_ingestion_task(
        self, annotation_queue_id: str, queue_ingestion_task_id: str
    ) -> QueueIngestionTask:
        """Get Queue Ingestion Task

        Retrieves an ingestion task by id, with the filters an item must match
        to be queued and the reviewers harvested items are assigned to.

        Args:
            annotation_queue_id: The id of the annotation queue the task fills.
            queue_ingestion_task_id: The id of the queue ingestion task.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
            response_schema=QueueIngestionTask,
            path={
                "annotationQueueId": annotation_queue_id,
                "queueIngestionTaskId": queue_ingestion_task_id,
            },
        )

    def update_queue_ingestion_task(
        self,
        annotation_queue_id: str,
        queue_ingestion_task_id: str,
        *,
        name: Optional[str] = None,
        data_model: Optional[IngestionDataModel] = None,
        description: Optional[str] = None,
        enabled: Optional[bool] = None,
        sample_rate: Optional[float] = None,
        filters: Optional[FilterSet] = None,
        max_items: Optional[int] = None,
        assignment_strategy: Optional[AssignmentStrategy] = None,
        reviewer_emails: Optional[List[str]] = None
    ) -> QueueIngestionTask:
        """Update Queue Ingestion Task

        Updates an ingestion task and returns it. A field you omit keeps its
        stored value; items already queued by the task are kept whatever you
        change.

        Args:
            annotation_queue_id: The id of the annotation queue the task fills.
            queue_ingestion_task_id: The id of the queue ingestion task.
            name: The name of the task.
            description: A note about what the task harvests. Send null to clear
                it.
            enabled: Whether the task runs. Disabling it stops new items
                arriving; items already queued are kept. Defaults to false.
            sample_rate: The fraction of matching items to queue, between 0 and
                1. Defaults to 1, all of them.
            max_items: The maximum number of items this task will ever queue.
                Send null to remove the cap.
            reviewer_emails: The project members harvested items are assigned
                to, following `assignmentStrategy`.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
            response_schema=QueueIngestionTask,
            request_schema=UpdateQueueIngestionTaskRequest,
            body={
                "name": name,
                "dataModel": data_model,
                "description": description,
                "enabled": enabled,
                "sampleRate": sample_rate,
                "filters": filters,
                "maxItems": max_items,
                "assignmentStrategy": assignment_strategy,
                "reviewerEmails": reviewer_emails,
            },
            path={
                "annotationQueueId": annotation_queue_id,
                "queueIngestionTaskId": queue_ingestion_task_id,
            },
        )

    async def a_update_queue_ingestion_task(
        self,
        annotation_queue_id: str,
        queue_ingestion_task_id: str,
        *,
        name: Optional[str] = None,
        data_model: Optional[IngestionDataModel] = None,
        description: Optional[str] = None,
        enabled: Optional[bool] = None,
        sample_rate: Optional[float] = None,
        filters: Optional[FilterSet] = None,
        max_items: Optional[int] = None,
        assignment_strategy: Optional[AssignmentStrategy] = None,
        reviewer_emails: Optional[List[str]] = None
    ) -> QueueIngestionTask:
        """Update Queue Ingestion Task

        Updates an ingestion task and returns it. A field you omit keeps its
        stored value; items already queued by the task are kept whatever you
        change.

        Args:
            annotation_queue_id: The id of the annotation queue the task fills.
            queue_ingestion_task_id: The id of the queue ingestion task.
            name: The name of the task.
            description: A note about what the task harvests. Send null to clear
                it.
            enabled: Whether the task runs. Disabling it stops new items
                arriving; items already queued are kept. Defaults to false.
            sample_rate: The fraction of matching items to queue, between 0 and
                1. Defaults to 1, all of them.
            max_items: The maximum number of items this task will ever queue.
                Send null to remove the cap.
            reviewer_emails: The project members harvested items are assigned
                to, following `assignmentStrategy`.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
            response_schema=QueueIngestionTask,
            request_schema=UpdateQueueIngestionTaskRequest,
            body={
                "name": name,
                "dataModel": data_model,
                "description": description,
                "enabled": enabled,
                "sampleRate": sample_rate,
                "filters": filters,
                "maxItems": max_items,
                "assignmentStrategy": assignment_strategy,
                "reviewerEmails": reviewer_emails,
            },
            path={
                "annotationQueueId": annotation_queue_id,
                "queueIngestionTaskId": queue_ingestion_task_id,
            },
        )

    def delete_queue_ingestion_task(
        self, annotation_queue_id: str, queue_ingestion_task_id: str
    ) -> QueueIngestionTaskRef:
        """Delete Queue Ingestion Task

        Permanently deletes an ingestion task, so it stops filling the queue.
        Items it already queued are kept.

        Args:
            annotation_queue_id: The id of the annotation queue the task fills.
            queue_ingestion_task_id: The id of the queue ingestion task.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
            response_schema=QueueIngestionTaskRef,
            path={
                "annotationQueueId": annotation_queue_id,
                "queueIngestionTaskId": queue_ingestion_task_id,
            },
        )

    async def a_delete_queue_ingestion_task(
        self, annotation_queue_id: str, queue_ingestion_task_id: str
    ) -> QueueIngestionTaskRef:
        """Delete Queue Ingestion Task

        Permanently deletes an ingestion task, so it stops filling the queue.
        Items it already queued are kept.

        Args:
            annotation_queue_id: The id of the annotation queue the task fills.
            queue_ingestion_task_id: The id of the queue ingestion task.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.ANNOTATION_QUEUE_QUEUE_INGESTION_TASK_ENDPOINT,
            response_schema=QueueIngestionTaskRef,
            path={
                "annotationQueueId": annotation_queue_id,
                "queueIngestionTaskId": queue_ingestion_task_id,
            },
        )
