# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: governance).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from confidentai.governance.types import GovernanceAssessment

__all__ = [
    "GovernanceAssessment",
]
