# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: organization).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Optional

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.organization.types import (
    GovernancePolicyIdentifier,
    GovernancePolicySkill,
    UpdateGovernancePolicySkillRequest,
)


class GovernancePoliciesSkillOperations:
    _api: Api

    def get_governance_policy_skill(
        self, policy_id: str
    ) -> Optional[GovernancePolicySkill]:
        """Get Governance Policy Skill

        Retrieves the Agent Skill attached to a governance policy. This is not a
        control and nothing about it is assessed: it is the instructions
        Confident AI serves to coding agents working on the projects this policy
        governs. Confident AI publishes a per-project Agent Skills git
        repository, and a project enrolled in this policy finds the skill there
        as `skills/governance/SKILL.md`, with `description` in the YAML
        frontmatter and `body` as the Markdown beneath it. Answers with null
        when the policy has none, in which case agents working on its projects
        receive no governance skill.

        Args:
            policy_id: The id of the governance policy.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_POLICY_SKILL_ENDPOINT,
            response_schema=Optional[GovernancePolicySkill],
            path={"policyId": policy_id},
        )

    async def a_get_governance_policy_skill(
        self, policy_id: str
    ) -> Optional[GovernancePolicySkill]:
        """Get Governance Policy Skill

        Retrieves the Agent Skill attached to a governance policy. This is not a
        control and nothing about it is assessed: it is the instructions
        Confident AI serves to coding agents working on the projects this policy
        governs. Confident AI publishes a per-project Agent Skills git
        repository, and a project enrolled in this policy finds the skill there
        as `skills/governance/SKILL.md`, with `description` in the YAML
        frontmatter and `body` as the Markdown beneath it. Answers with null
        when the policy has none, in which case agents working on its projects
        receive no governance skill.

        Args:
            policy_id: The id of the governance policy.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_POLICY_SKILL_ENDPOINT,
            response_schema=Optional[GovernancePolicySkill],
            path={"policyId": policy_id},
        )

    def update_governance_policy_skill(
        self, policy_id: str, description: str, body: str
    ) -> GovernancePolicySkill:
        """Update Governance Policy Skill

        Sets the Agent Skill served to coding agents working on the projects
        this governance policy governs, creating it when the policy has none and
        replacing it outright otherwise. Both `description` and `body` are
        required and must not be blank, so there is no way to patch one and
        leave the other. The new text reaches an agent the next time it clones
        the project's Agent Skills repository, where it appears as
        `skills/governance/SKILL.md`. Returns the skill as it now stands, which
        is never null.

        Args:
            policy_id: The id of the governance policy.
            description: One line on what the skill covers, which is how a
                coding agent decides whether it is relevant. Required, and must
                not be blank.
            body: The instructions themselves, in Markdown, which become the
                body of `skills/governance/SKILL.md`. Required, and must not be
                blank.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.ORGANIZATION_GOVERNANCE_POLICY_SKILL_ENDPOINT,
            response_schema=GovernancePolicySkill,
            request_schema=UpdateGovernancePolicySkillRequest,
            body={"description": description, "body": body},
            path={"policyId": policy_id},
        )

    async def a_update_governance_policy_skill(
        self, policy_id: str, description: str, body: str
    ) -> GovernancePolicySkill:
        """Update Governance Policy Skill

        Sets the Agent Skill served to coding agents working on the projects
        this governance policy governs, creating it when the policy has none and
        replacing it outright otherwise. Both `description` and `body` are
        required and must not be blank, so there is no way to patch one and
        leave the other. The new text reaches an agent the next time it clones
        the project's Agent Skills repository, where it appears as
        `skills/governance/SKILL.md`. Returns the skill as it now stands, which
        is never null.

        Args:
            policy_id: The id of the governance policy.
            description: One line on what the skill covers, which is how a
                coding agent decides whether it is relevant. Required, and must
                not be blank.
            body: The instructions themselves, in Markdown, which become the
                body of `skills/governance/SKILL.md`. Required, and must not be
                blank.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.ORGANIZATION_GOVERNANCE_POLICY_SKILL_ENDPOINT,
            response_schema=GovernancePolicySkill,
            request_schema=UpdateGovernancePolicySkillRequest,
            body={"description": description, "body": body},
            path={"policyId": policy_id},
        )

    def delete_governance_policy_skill(
        self, policy_id: str
    ) -> GovernancePolicyIdentifier:
        """Delete Governance Policy Skill

        Permanently deletes the Agent Skill attached to a governance policy and
        returns the policy's id. Coding agents working on the projects it
        governs stop receiving `skills/governance/SKILL.md` on their next clone.
        The policy, its controls and its projects are untouched, since the skill
        instructs agents rather than gating anything. A policy that has no skill
        is reported as not found. **Warning:** This action cannot be undone.

        Args:
            policy_id: The id of the governance policy.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.ORGANIZATION_GOVERNANCE_POLICY_SKILL_ENDPOINT,
            response_schema=GovernancePolicyIdentifier,
            path={"policyId": policy_id},
        )

    async def a_delete_governance_policy_skill(
        self, policy_id: str
    ) -> GovernancePolicyIdentifier:
        """Delete Governance Policy Skill

        Permanently deletes the Agent Skill attached to a governance policy and
        returns the policy's id. Coding agents working on the projects it
        governs stop receiving `skills/governance/SKILL.md` on their next clone.
        The policy, its controls and its projects are untouched, since the skill
        instructs agents rather than gating anything. A policy that has no skill
        is reported as not found. **Warning:** This action cannot be undone.

        Args:
            policy_id: The id of the governance policy.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.ORGANIZATION_GOVERNANCE_POLICY_SKILL_ENDPOINT,
            response_schema=GovernancePolicyIdentifier,
            path={"policyId": policy_id},
        )
