# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: metrics).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from confidentai.metrics.types import UpdateMetricRequest

__all__ = [
    "UpdateMetricRequest",
]
