// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: transformers).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import {
  Transformer,
  TransformerCodeDefinition,
  TransformerCodeRunResult,
  TransformerList,
  TransformerRef,
} from "./types";

export class TransformersClient {
  constructor(protected readonly api: Api) {}

  /**
   * List Transformers
   *
   * Lists the transformers in your Confident AI project one page at a time,
   * ordered by name. Use the returned ids for an AI connection's or a metric
   * collection's transformer fields; retrieve one by id to read its code.
   *
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   */
  async listTransformers(
    page?: number,
    pageSize?: number,
  ): Promise<TransformerList> {
    return this.api.sendRequest<TransformerList>(
      HttpMethods.GET,
      Endpoints.TRANSFORMERS_ENDPOINT,
      { params: { page, pageSize } },
    );
  }

  /**
   * Create Transformer
   *
   * Creates a transformer in your Confident AI project and returns its id. Test
   * the code against a sample before attaching the transformer to anything.
   *
   * @param name The name of the transformer, unique within the project.
   * @param description What the transformer extracts. Send null to leave it
   *   unset.
   */
  async createTransformer(
    name: string,
    codeDefinition: TransformerCodeDefinition,
    description?: string | null,
  ): Promise<TransformerRef> {
    return this.api.sendRequest<TransformerRef>(
      HttpMethods.POST,
      Endpoints.TRANSFORMERS_ENDPOINT,
      { body: { name, codeDefinition, description } },
    );
  }

  /**
   * Get Transformer
   *
   * Retrieves a transformer by id, including the code it runs. A transformer
   * saved without code returns `codeDefinition` as null.
   *
   * @param transformerId The id of the transformer.
   */
  async getTransformer(transformerId: string): Promise<Transformer> {
    return this.api.sendRequest<Transformer>(
      HttpMethods.GET,
      Endpoints.TRANSFORMER_ENDPOINT,
      { urlParams: { transformerId } },
    );
  }

  /**
   * Update Transformer
   *
   * Renames a transformer, changes its description, or replaces its code, and
   * returns it. Sending `codeDefinition` overwrites the stored code, which
   * every AI connection and metric collection already using this transformer
   * picks up on its next run.
   *
   * @param transformerId The id of the transformer.
   * @param name The name of the transformer, unique within the project.
   * @param description What the transformer extracts. Send null to clear it.
   */
  async updateTransformer(
    transformerId: string,
    name?: string,
    description?: string | null,
    codeDefinition?: TransformerCodeDefinition,
  ): Promise<Transformer> {
    return this.api.sendRequest<Transformer>(
      HttpMethods.PUT,
      Endpoints.TRANSFORMER_ENDPOINT,
      {
        body: { name, description, codeDefinition },
        urlParams: { transformerId },
      },
    );
  }

  /**
   * Delete Transformer
   *
   * Permanently deletes a transformer and the code stored with it. Anything
   * still pointing at it stops transforming.
   *
   * @param transformerId The id of the transformer.
   */
  async deleteTransformer(transformerId: string): Promise<TransformerRef> {
    return this.api.sendRequest<TransformerRef>(
      HttpMethods.DELETE,
      Endpoints.TRANSFORMER_ENDPOINT,
      { urlParams: { transformerId } },
    );
  }

  /**
   * Test Transformer Code
   *
   * Runs the transformer's stored code against a sample value and returns what
   * it produced. Code that raises or times out is a completed test, so it comes
   * back with a 200 and `success: false` carrying `error` and `reason` — branch
   * on `success` rather than on the status. A 404 means the transformer does
   * not exist in this project, and a 400 means it has no code saved to run.
   *
   * @param transformerId The id of the transformer.
   * @param inputData The value to pass to the transformer's `transform`
   *   function. Any JSON value is accepted; send the shape the transformer
   *   expects to see in production.
   */
  async testTransformerCode(
    transformerId: string,
    inputData?: unknown,
  ): Promise<TransformerCodeRunResult> {
    return this.api.sendRequest<TransformerCodeRunResult>(
      HttpMethods.POST,
      Endpoints.TRANSFORMER_TEST_CODE_ENDPOINT,
      { body: { inputData }, urlParams: { transformerId } },
    );
  }
}
