# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: reports).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import List, Optional

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.reports.types import (
    CreateReportRequest,
    Report,
    ReportList,
    ReportMetadataInput,
    ReportRef,
    ReportSectionInput,
    ReportStatus,
    UpdateReportRequest,
)


class ReportsClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list(
        self,
        *,
        report_template_id: Optional[str] = None,
        status: Optional[ReportStatus] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None
    ) -> ReportList:
        """List Reports

        Lists the reports in your Confident AI project one page at a time,
        newest first, without their sections. Narrow the page with
        `reportTemplateId`, `status`, or a `startDate`/`endDate` window;
        retrieve a report by id to read its sections.

        Args:
            report_template_id: Only return reports written under this report
                template.
            start_date: Only return reports created at or after this ISO 8601
                datetime.
            end_date: Only return reports created at or before this ISO 8601
                datetime.
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.REPORTS_ENDPOINT,
            response_schema=ReportList,
            query={
                "reportTemplateId": report_template_id,
                "status": status,
                "startDate": start_date,
                "endDate": end_date,
                "page": page,
                "pageSize": page_size,
            },
        )

    async def a_list(
        self,
        *,
        report_template_id: Optional[str] = None,
        status: Optional[ReportStatus] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None
    ) -> ReportList:
        """List Reports

        Lists the reports in your Confident AI project one page at a time,
        newest first, without their sections. Narrow the page with
        `reportTemplateId`, `status`, or a `startDate`/`endDate` window;
        retrieve a report by id to read its sections.

        Args:
            report_template_id: Only return reports written under this report
                template.
            start_date: Only return reports created at or after this ISO 8601
                datetime.
            end_date: Only return reports created at or before this ISO 8601
                datetime.
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.REPORTS_ENDPOINT,
            response_schema=ReportList,
            query={
                "reportTemplateId": report_template_id,
                "status": status,
                "startDate": start_date,
                "endDate": end_date,
                "page": page,
                "pageSize": page_size,
            },
        )

    def create(
        self,
        report_template_id: str,
        sections: List[ReportSectionInput],
        *,
        status: Optional[ReportStatus] = None,
        error: Optional[str] = None,
        metadata: Optional[ReportMetadataInput] = None
    ) -> ReportRef:
        """Create Report

        Writes a report into your Confident AI project and returns its id. You
        supply the finished section content and it is stored and rendered
        exactly as given, under the report template you name.

        Args:
            report_template_id: The report template to write this report under.
                Required, since a report is read under its template.
            sections: The report's sections, in render order. At least one is
                required.
            error: Why the report failed, when creating it as ERRORED.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.REPORTS_ENDPOINT,
            response_schema=ReportRef,
            request_schema=CreateReportRequest,
            body={
                "reportTemplateId": report_template_id,
                "sections": sections,
                "status": status,
                "error": error,
                "metadata": metadata,
            },
        )

    async def a_create(
        self,
        report_template_id: str,
        sections: List[ReportSectionInput],
        *,
        status: Optional[ReportStatus] = None,
        error: Optional[str] = None,
        metadata: Optional[ReportMetadataInput] = None
    ) -> ReportRef:
        """Create Report

        Writes a report into your Confident AI project and returns its id. You
        supply the finished section content and it is stored and rendered
        exactly as given, under the report template you name.

        Args:
            report_template_id: The report template to write this report under.
                Required, since a report is read under its template.
            sections: The report's sections, in render order. At least one is
                required.
            error: Why the report failed, when creating it as ERRORED.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.REPORTS_ENDPOINT,
            response_schema=ReportRef,
            request_schema=CreateReportRequest,
            body={
                "reportTemplateId": report_template_id,
                "sections": sections,
                "status": status,
                "error": error,
                "metadata": metadata,
            },
        )

    def get(self, report_id: str) -> Report:
        """Get Report

        Retrieves a report by id, with every section it renders in order. A
        section Confident AI is still writing comes back with null `content`.

        Args:
            report_id: The id of the report.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.REPORT_ENDPOINT,
            response_schema=Report,
            path={"reportId": report_id},
        )

    async def a_get(self, report_id: str) -> Report:
        """Get Report

        Retrieves a report by id, with every section it renders in order. A
        section Confident AI is still writing comes back with null `content`.

        Args:
            report_id: The id of the report.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.REPORT_ENDPOINT,
            response_schema=Report,
            path={"reportId": report_id},
        )

    def update(
        self,
        report_id: str,
        *,
        status: Optional[ReportStatus] = None,
        error: Optional[str] = None,
        metadata: Optional[ReportMetadataInput] = None,
        sections: Optional[List[ReportSectionInput]] = None
    ) -> Report:
        """Update Report

        Updates a report and returns it. Only the fields you send are changed:
        `metadata` is merged onto the report's stored header, while `sections`
        replaces its section list wholesale.

        Args:
            report_id: The id of the report.
            error: Why the report failed. Pair it with a status of ERRORED, or
                send null to clear it.
            sections: The report's sections, in render order. The list replaces
                the report's current sections rather than adding to them.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.REPORT_ENDPOINT,
            response_schema=Report,
            request_schema=UpdateReportRequest,
            body={
                "status": status,
                "error": error,
                "metadata": metadata,
                "sections": sections,
            },
            path={"reportId": report_id},
        )

    async def a_update(
        self,
        report_id: str,
        *,
        status: Optional[ReportStatus] = None,
        error: Optional[str] = None,
        metadata: Optional[ReportMetadataInput] = None,
        sections: Optional[List[ReportSectionInput]] = None
    ) -> Report:
        """Update Report

        Updates a report and returns it. Only the fields you send are changed:
        `metadata` is merged onto the report's stored header, while `sections`
        replaces its section list wholesale.

        Args:
            report_id: The id of the report.
            error: Why the report failed. Pair it with a status of ERRORED, or
                send null to clear it.
            sections: The report's sections, in render order. The list replaces
                the report's current sections rather than adding to them.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.REPORT_ENDPOINT,
            response_schema=Report,
            request_schema=UpdateReportRequest,
            body={
                "status": status,
                "error": error,
                "metadata": metadata,
                "sections": sections,
            },
            path={"reportId": report_id},
        )

    def delete(self, report_id: str) -> ReportRef:
        """Delete Report

        Permanently deletes a report and all of its sections. The report
        template it was written under is kept.

        Args:
            report_id: The id of the report.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.REPORT_ENDPOINT,
            response_schema=ReportRef,
            path={"reportId": report_id},
        )

    async def a_delete(self, report_id: str) -> ReportRef:
        """Delete Report

        Permanently deletes a report and all of its sections. The report
        template it was written under is kept.

        Args:
            report_id: The id of the report.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.REPORT_ENDPOINT,
            response_schema=ReportRef,
            path={"reportId": report_id},
        )
