# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: rt-frameworks).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from confident_ai.api import Api
from confident_ai.rt_frameworks.operations import RTFrameworksOperations
from confident_ai.rt_frameworks.risk_categories.operations import (
    RiskCategoriesOperations,
)


class RTFrameworksClient(
    RTFrameworksOperations,
    RiskCategoriesOperations,
):
    def __init__(self, api: Api) -> None:
        self._api = api
