# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: prompts).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.prompts.types import (
    Prompt,
    PromptList,
    PushPromptRequest,
    PushPromptResult,
)


class PromptsOperations:
    _api: Api

    def list(self) -> PromptList:
        """List Prompts

        Lists all the prompts in your Confident AI project.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.PROMPTS_ENDPOINT,
            response_schema=PromptList,
        )

    async def a_list(self) -> PromptList:
        """List Prompts

        Lists all the prompts in your Confident AI project.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.PROMPTS_ENDPOINT,
            response_schema=PromptList,
        )

    def push(self, prompt: PushPromptRequest) -> PushPromptResult:
        """Push Prompt

        Creates a new commit for the prompt with the given `alias`, creating the
        prompt first when it does not exist. Send `text` for a text prompt or
        `messages` for a messages prompt, not both.

        Args:
            prompt: The commit to push. Send `text` for a text prompt or
                `messages` for a messages prompt, never both. The kind must
                match the existing prompt's type. Pass a PushTextPrompt or a
                PushMessagesPrompt, from confidentai.prompts.types.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.PROMPTS_ENDPOINT,
            response_schema=PushPromptResult,
            request_schema=PushPromptRequest,
            body=prompt,
        )

    async def a_push(self, prompt: PushPromptRequest) -> PushPromptResult:
        """Push Prompt

        Creates a new commit for the prompt with the given `alias`, creating the
        prompt first when it does not exist. Send `text` for a text prompt or
        `messages` for a messages prompt, not both.

        Args:
            prompt: The commit to push. Send `text` for a text prompt or
                `messages` for a messages prompt, never both. The kind must
                match the existing prompt's type. Pass a PushTextPrompt or a
                PushMessagesPrompt, from confidentai.prompts.types.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.PROMPTS_ENDPOINT,
            response_schema=PushPromptResult,
            request_schema=PushPromptRequest,
            body=prompt,
        )

    def get_by_label(self, prompt_id: str, label: str) -> Prompt:
        """Pull Prompt by Label

        Retrieves the prompt version carrying `label`.

        Args:
            prompt_id: The unique id of the prompt.
            label: The label of the version to pull.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.PROMPT_LABEL_ENDPOINT,
            response_schema=Prompt,
            path={"promptId": prompt_id, "label": label},
        )

    async def a_get_by_label(self, prompt_id: str, label: str) -> Prompt:
        """Pull Prompt by Label

        Retrieves the prompt version carrying `label`.

        Args:
            prompt_id: The unique id of the prompt.
            label: The label of the version to pull.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.PROMPT_LABEL_ENDPOINT,
            response_schema=Prompt,
            path={"promptId": prompt_id, "label": label},
        )
