# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: attack-methods).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Any, Dict, Literal, Optional

from confidentai.api import Api, HttpMethods
from confidentai.attack_methods.types import (
    AttackMethod,
    AttackMethodList,
    AttackMethodRef,
    UpdateAttackMethodRequest,
)
from confidentai.endpoints import Endpoints


class AttackMethodsClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list_attack_methods(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        multi_turn: Optional[Literal["true", "false"]] = None
    ) -> AttackMethodList:
        """List Attack Methods

        Lists the attack methods available to your Confident AI project one page
        at a time, ordered by name. The list covers the whole catalog, whether
        or not this project has configured a method; retrieve one by id for the
        parameters it takes.

        Args:
            page: The page of attack methods to return. Defaults to 1.
            page_size: The number of attack methods per page, at most 100.
                Defaults to 25.
            multi_turn: When true, returns only multi-turn attack methods; when
                false, only single-turn ones. Omit to return both.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ATTACK_METHODS_ENDPOINT,
            response_schema=AttackMethodList,
            query={
                "page": page,
                "pageSize": page_size,
                "multiTurn": multi_turn,
            },
        )

    async def a_list_attack_methods(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        multi_turn: Optional[Literal["true", "false"]] = None
    ) -> AttackMethodList:
        """List Attack Methods

        Lists the attack methods available to your Confident AI project one page
        at a time, ordered by name. The list covers the whole catalog, whether
        or not this project has configured a method; retrieve one by id for the
        parameters it takes.

        Args:
            page: The page of attack methods to return. Defaults to 1.
            page_size: The number of attack methods per page, at most 100.
                Defaults to 25.
            multi_turn: When true, returns only multi-turn attack methods; when
                false, only single-turn ones. Omit to return both.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ATTACK_METHODS_ENDPOINT,
            response_schema=AttackMethodList,
            query={
                "page": page,
                "pageSize": page_size,
                "multiTurn": multi_turn,
            },
        )

    def get_attack_method(self, attack_method_id: str) -> AttackMethod:
        """Get Attack Method

        Retrieves an attack method by id, with the parameters it takes and the
        values in force for your project.

        Args:
            attack_method_id: The id of the attack method, as the list returns
                it. A method's catalog name also resolves.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ATTACK_METHOD_ENDPOINT,
            response_schema=AttackMethod,
            path={"attackMethodId": attack_method_id},
        )

    async def a_get_attack_method(self, attack_method_id: str) -> AttackMethod:
        """Get Attack Method

        Retrieves an attack method by id, with the parameters it takes and the
        values in force for your project.

        Args:
            attack_method_id: The id of the attack method, as the list returns
                it. A method's catalog name also resolves.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ATTACK_METHOD_ENDPOINT,
            response_schema=AttackMethod,
            path={"attackMethodId": attack_method_id},
        )

    def update_attack_method(
        self, attack_method_id: str, parameters: Dict[str, Any]
    ) -> AttackMethod:
        """Update Attack Method

        Configures the parameter values your project runs an attack method with,
        and returns the method. The values replace this project's stored
        configuration wholesale, so send every value you want kept. An attack
        method that takes no parameters cannot be configured.

        Args:
            attack_method_id: The id of the attack method, as the list returns
                it. A method's catalog name also resolves.
            parameters: The values to configure, keyed by parameter name. They
                replace this project's stored configuration wholesale, so send
                every value you want kept, and each must match the type its
                parameter declares.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.ATTACK_METHOD_ENDPOINT,
            response_schema=AttackMethod,
            request_schema=UpdateAttackMethodRequest,
            body={"parameters": parameters},
            path={"attackMethodId": attack_method_id},
        )

    async def a_update_attack_method(
        self, attack_method_id: str, parameters: Dict[str, Any]
    ) -> AttackMethod:
        """Update Attack Method

        Configures the parameter values your project runs an attack method with,
        and returns the method. The values replace this project's stored
        configuration wholesale, so send every value you want kept. An attack
        method that takes no parameters cannot be configured.

        Args:
            attack_method_id: The id of the attack method, as the list returns
                it. A method's catalog name also resolves.
            parameters: The values to configure, keyed by parameter name. They
                replace this project's stored configuration wholesale, so send
                every value you want kept, and each must match the type its
                parameter declares.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.ATTACK_METHOD_ENDPOINT,
            response_schema=AttackMethod,
            request_schema=UpdateAttackMethodRequest,
            body={"parameters": parameters},
            path={"attackMethodId": attack_method_id},
        )

    def reset_attack_method(self, attack_method_id: str) -> AttackMethodRef:
        """Reset Attack Method

        Clears your project's configuration of an attack method, so it runs with
        the catalog defaults again. The attack method itself belongs to the
        Confident AI catalog and is not deleted, which makes this safe to
        repeat.

        Args:
            attack_method_id: The id of the attack method, as the list returns
                it. A method's catalog name also resolves.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.ATTACK_METHOD_ENDPOINT,
            response_schema=AttackMethodRef,
            path={"attackMethodId": attack_method_id},
        )

    async def a_reset_attack_method(
        self, attack_method_id: str
    ) -> AttackMethodRef:
        """Reset Attack Method

        Clears your project's configuration of an attack method, so it runs with
        the catalog defaults again. The attack method itself belongs to the
        Confident AI catalog and is not deleted, which makes this safe to
        repeat.

        Args:
            attack_method_id: The id of the attack method, as the list returns
                it. A method's catalog name also resolves.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.ATTACK_METHOD_ENDPOINT,
            response_schema=AttackMethodRef,
            path={"attackMethodId": attack_method_id},
        )
