// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: export-destinations).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

export enum ExportDestinationType {
  S3 = "S3",
  GCS = "GCS",
  AZURE_BLOB = "AZURE_BLOB",
  SNOWFLAKE = "SNOWFLAKE",
}

export interface SnowflakeExportDestinationConfig {
  account: string;
  username: string;
  role: string;
  warehouse: string;
  database: string;
  schema: string;
  privateKey: string;
  privateKeyPassphrase?: string | null;
}

export interface CreateExportDestinationRequest {
  name: string;
  type?: ExportDestinationType;
  bucket?: string;
  region?: string;
  accessKeyId?: string;
  secretAccessKey?: string;
  pathPrefix?: string | null;
  snowflakeConfig?: SnowflakeExportDestinationConfig;
  enabled?: boolean;
}

export interface SnowflakeExportDestinationMaskedConfig {
  account: string;
  username: string;
  role: string;
  warehouse: string;
  database: string;
  schema: string;
  privateKey: string;
  privateKeyPassphrase: string | null;
}

export interface ExportDestination {
  id: string;
  name: string;
  type: ExportDestinationType;
  bucket: string | null;
  region: string | null;
  accessKeyId: string | null;
  secretAccessKey: string | null;
  pathPrefix: string | null;
  snowflakeConfig: SnowflakeExportDestinationMaskedConfig | null;
  enabled: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ExportDestinationSummary {
  id: string;
  name: string;
  type: ExportDestinationType;
  bucket: string | null;
  enabled: boolean;
}

export interface ExportDestinationList {
  exportDestinations: ExportDestinationSummary[];
  totalExportDestinations: number;
  page: number;
  pageSize: number;
}

export interface ExportDestinationRef {
  id: string;
}

export interface UpdateSnowflakeExportDestinationConfig {
  account?: string;
  username?: string;
  role?: string;
  warehouse?: string;
  database?: string;
  schema?: string;
  privateKey?: string;
  privateKeyPassphrase?: string | null;
}

export interface UpdateExportDestinationRequest {
  name?: string;
  type?: ExportDestinationType;
  bucket?: string;
  region?: string;
  accessKeyId?: string;
  secretAccessKey?: string;
  pathPrefix?: string | null;
  snowflakeConfig?: UpdateSnowflakeExportDestinationConfig;
  enabled?: boolean;
}
