// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: projects).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { RolesOperations } from "./roles/operations";

export class ProjectsClient extends RolesOperations {}
