// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: projects).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import {
  ModelCredentials,
  ModelProvider,
  PermissionList,
} from "../common/types";
import { CreateProjectResult, Project, ProjectList, ProjectRef } from "./types";

export class ProjectsOperations {
  constructor(protected readonly api: Api) {}

  /**
   * List Projects
   *
   * Lists every project in your organization, ordered by name. Each project is
   * returned in full, including the governance policy it is enrolled in, so a
   * caller building a project picker does not need a second call per row.
   */
  async list(): Promise<ProjectList> {
    return this.api.sendRequest<ProjectList>(
      HttpMethods.GET,
      Endpoints.PROJECTS_ENDPOINT,
    );
  }

  /**
   * Create Project
   *
   * Creates a project in your organization and provisions a project-scoped API
   * key for it. The key's full `value` is returned **once**, in this response,
   * and is redacted on every later read — so capture it here. The project is
   * seeded with Confident AI's default classifiers, online metric and trace
   * alert. How many projects you may hold depends on your plan, so this can be
   * refused on entitlement grounds even when the name is free.
   *
   * @param name The name of the project, which must not already be taken by
   *   another project in the organization.
   * @param description What the project covers. Omit it to leave it unset.
   * @param email The email of an existing member of your organization to assign
   *   as the project's Owner, which also attributes the provisioned API key to
   *   them. Omit it and the project has no member: it is reachable through its
   *   API key and to organization admins only.
   */
  async create(
    name: string,
    description?: string,
    email?: string,
  ): Promise<CreateProjectResult> {
    return this.api.sendRequest<CreateProjectResult>(
      HttpMethods.POST,
      Endpoints.PROJECTS_ENDPOINT,
      { body: { name, description, email } },
    );
  }

  /**
   * Retrieve Project
   *
   * Retrieves a single project by id, including the governance policy it is
   * enrolled in. A project in another organization is reported as not found
   * rather than as forbidden.
   *
   * @param projectId The id of the project. It must belong to the organization
   *   your API key is scoped to.
   */
  async get(projectId: string): Promise<Project> {
    return this.api.sendRequest<Project>(
      HttpMethods.GET,
      Endpoints.PROJECT_ENDPOINT,
      { urlParams: { projectId } },
    );
  }

  /**
   * Update Project
   *
   * Renames a project or changes its description, and returns the project as
   * stored. Send at least one field; a field you omit is left as it is.
   *
   * @param projectId The id of the project. It must belong to the organization
   *   your API key is scoped to.
   * @param name The name of the project, which must not already be taken by
   *   another project in the organization.
   * @param description What the project covers.
   */
  async update(
    projectId: string,
    name?: string,
    description?: string,
  ): Promise<Project> {
    return this.api.sendRequest<Project>(
      HttpMethods.PUT,
      Endpoints.PROJECT_ENDPOINT,
      { body: { name, description }, urlParams: { projectId } },
    );
  }

  /**
   * Delete Project
   *
   * Permanently deletes a project. **This cannot be undone, and it cascades**
   * to everything held under it: API keys (including one an SDK may be
   * configured with), members and role assignments, invitations, datasets,
   * prompts, metrics, test runs, dashboards, annotation queues, red teaming
   * frameworks, policies, alerts and export schedules. Ingested traces and
   * spans stop being reachable. There is no confirmation step, so the safe way
   * to retire a project is to deactivate its API keys first. Its name becomes
   * available for reuse.
   *
   * @param projectId The id of the project. It must belong to the organization
   *   your API key is scoped to.
   */
  async delete(projectId: string): Promise<ProjectRef> {
    return this.api.sendRequest<ProjectRef>(
      HttpMethods.DELETE,
      Endpoints.PROJECT_ENDPOINT,
      { urlParams: { projectId } },
    );
  }

  /**
   * Set Project Model Credentials
   *
   * Sets, replaces, or clears a project's stored credential for a single model
   * provider. While the project is still inheriting your organization's
   * credentials, the first write creates a standalone set for the project and
   * severs that inheritance — so the project then holds only the provider you
   * just sent, and any other provider it relied on has to be set again here.
   * This is a write-only surface: there is no read endpoint, and the response
   * returns every credential masked. A provider your organization's model
   * provider policy does not allow cannot have a credential set (`403`), though
   * clearing one is always permitted.
   *
   * @param projectId The id of the project, which must belong to the
   *   organization your API key is scoped to.
   * @param apiKey The provider's API key, for the API-key providers only. Send
   *   the raw secret to set it, or null to clear it; a masked value read back
   *   from a response is rejected. Sending it for a configuration provider is
   *   rejected.
   * @param modelConfig The provider's configuration, for the configuration
   *   providers only — for example `azureApiBase`, `azureDeploymentName`,
   *   `azureApiVersion` and `azureApiKey` for `AZURE`. It replaces the stored
   *   configuration wholesale rather than merging into it, so send every key
   *   the provider needs; send null to clear it. It must not be empty and must
   *   not carry masked values read back from a response. Sending it for an API-
   *   key provider is rejected. For `BEDROCK`, always send `regionName` and
   *   `modelId`, then authenticate with either `ACCESS_KEYS` (`awsAccessKeyId`
   *   and `awsSecretAccessKey`) or, when calling the OpenAI-compatible Mantle
   *   API by setting `api` to `MANTLE`, an `authType` of `API_KEY` together
   *   with `apiKey`, an optional `apiBase`, and an optional `projectId` (sent
   *   as the `OpenAI-Project` header so AWS attributes usage and cost to that
   *   Mantle project; letters, numbers, hyphens and underscores only). An API
   *   key only works with the Mantle API, and assume-role Bedrock
   *   configurations can only be managed on the Confident AI platform.
   */
  async updateModelCredentials(
    projectId: string,
    provider: ModelProvider,
    apiKey?: string | null,
    modelConfig?: Record<string, unknown> | null,
  ): Promise<ModelCredentials> {
    return this.api.sendRequest<ModelCredentials>(
      HttpMethods.PUT,
      Endpoints.PROJECT_MODEL_CREDENTIALS_ENDPOINT,
      { body: { provider, apiKey, modelConfig }, urlParams: { projectId } },
    );
  }

  /**
   * List Project Permissions
   *
   * Lists every project permission a project policy can grant. Each is named
   * `resource:action` — `dataset:read`, `golden:create` — and its id is what
   * you send in a policy's `permissionIds`. This is Confident AI's whole
   * project catalog, not only the permissions this project already uses, and it
   * is the same catalog for every project in your organization. Organization
   * permissions are a separate catalog with its own endpoint.
   *
   * @param projectId The id of the project, which must belong to the
   *   organization your API key is scoped to.
   */
  async listPermissions(projectId: string): Promise<PermissionList> {
    return this.api.sendRequest<PermissionList>(
      HttpMethods.GET,
      Endpoints.PROJECT_PERMISSIONS_ENDPOINT,
      { urlParams: { projectId } },
    );
  }
}
