// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: projects).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api } from "../api";
import { ProjectsClient } from "./client";
import {
  ApiKey,
  ApiKeyList,
  ApiKeyRef,
  AuditLogExport,
  CreatedApiKey,
  InvitationRef,
  MemberRef,
  ModelCredentials,
  ModelProvider,
  PermissionList,
  Policy,
  PolicyList,
  PolicyRef,
  RoleRef,
  RotatedApiKey,
} from "../common/types";
import {
  ClearProjectModelResult,
  Project as ProjectPayload,
  ProjectGovernancePolicy,
  ProjectInvitation,
  ProjectInvitationList,
  ProjectMember,
  ProjectMemberList,
  ProjectModel,
  ProjectRef,
  ProjectRole,
  ProjectRoleList,
  UpdateProjectModelRequest,
  UpdateProjectModelResult,
  UpdateProjectRequest,
} from "./types";

/**
 * One project of your project, held by its projectId.
 *
 * Its methods are ProjectsClient's, minus the
 * `projectId` that this handle supplies.
 */
export class Project {
  private readonly client: ProjectsClient;

  projectId?: string;
  id?: string;
  name?: string;
  description?: string | null;
  organizationId?: string;
  created_at?: string;
  governancePolicy?: ProjectGovernancePolicy | null;

  constructor(api: Api, options: { projectId?: string } = {}) {
    this.client = new ProjectsClient(api);
    this.projectId = options.projectId;
  }

  /**
   * Delete Project
   *
   * Permanently deletes a project. **This cannot be undone, and it cascades:**
   * everything held under the project goes with it — its API keys (including
   * the one an SDK may be configured with), its members and their role
   * assignments, pending invitations, datasets, prompts and their versions,
   * metrics and metric collections, test runs and their results, dashboards,
   * annotation queues and forms, red teaming frameworks and risk assessments,
   * policies, alerts and export schedules. Ingested traces and spans stop being
   * reachable once the project is gone. There is no confirmation step and no
   * recovery, so the safe way to retire a project is to deactivate its API keys
   * first. The project's name becomes available for reuse within the
   * organization.
   */
  async delete(): Promise<ProjectRef> {
    return this.client.delete(this.projectIdOrThrow());
  }

  /**
   * List Project API Keys
   *
   * Lists every API key scoped to the project, newest first. Each key's `value`
   * is masked (only its last six characters are shown) — the full value is only
   * ever returned once, by the response that issues it. A rotation whose grace
   * period has already run out is completed before the list is read, so a
   * `shadowValue` here is always still in flight.
   */
  async listApiKeys(): Promise<ApiKeyList> {
    return this.client.listApiKeys(this.projectIdOrThrow());
  }

  /**
   * Create Project API Key
   *
   * Mints a new project-scoped API key. The full `value` is returned **exactly
   * once**, in this response, and can never be retrieved again — store it
   * securely. This is the key your application uses to send traces and run
   * evaluations against the project.
   *
   * @param name A label for the key, shown on the Confident AI platform.
   * @param expiresInDays How long the key lasts, in days from now — a duration,
   *   not a date. Confident AI turns it into the `expiresAt` instant on the
   *   key. Omit it for a key that never expires.
   */
  async createApiKey(
    name: string,
    expiresInDays?: number,
  ): Promise<CreatedApiKey> {
    return this.client.createApiKey(
      this.projectIdOrThrow(),
      name,
      expiresInDays,
    );
  }

  /**
   * Get Project API Key
   *
   * Retrieves one project-scoped API key by id. Its `value` is masked — the
   * full value is only ever returned once, by the response that issues it. A
   * `rotatesAt` in the past means the grace period is over and the outgoing
   * value is already rejected on authentication, even though this endpoint
   * still shows it; listing the keys completes the rotation.
   *
   * @param apiKeyId The id of the API key.
   */
  async getApiKey(apiKeyId: string): Promise<ApiKey> {
    return this.client.getApiKey(this.projectIdOrThrow(), apiKeyId);
  }

  /**
   * Update Project API Key
   *
   * Activates or deactivates a project-scoped API key. A deactivated key is
   * rejected on authentication from the next request onwards, so anything still
   * sending traces with it starts failing; its value is unchanged and
   * reactivating it brings the same value back. Rotating is the only way to
   * change the value.
   *
   * @param apiKeyId The id of the API key.
   * @param valid Send false to deactivate the key, true to reactivate it. A
   *   deactivated key is rejected on every request, and deactivating one takes
   *   effect immediately.
   */
  async updateApiKey(apiKeyId: string, valid: boolean): Promise<ApiKey> {
    return this.client.updateApiKey(this.projectIdOrThrow(), apiKeyId, valid);
  }

  /**
   * Revoke Project API Key
   *
   * Permanently revokes a project-scoped API key. Both its current value and
   * any replacement value in flight stop authenticating at once, so anything
   * still sending traces with it starts failing. This cannot be undone — a new
   * key has to be created in its place.
   *
   * @param apiKeyId The id of the API key.
   */
  async deleteApiKey(apiKeyId: string): Promise<ApiKeyRef> {
    return this.client.deleteApiKey(this.projectIdOrThrow(), apiKeyId);
  }

  /**
   * Rotate Project API Key
   *
   * Rotates a project-scoped API key in place — the key keeps its id, name and
   * history, and no second key is created. The new value is returned **exactly
   * once**, in this response, and can never be retrieved again — store it
   * securely. With `gracePeriodInHours: 0` (the default) the key's `value` is
   * replaced as this request is served and the outgoing value stops
   * authenticating at once, so anything still sending traces with it starts
   * failing. With a grace period, the new value comes back as `shadowValue` and
   * both values authenticate until `rotatesAt`, which is the window to
   * redeploy; after it the new value becomes `value` and the outgoing one is
   * rejected. Requests made with the outgoing value in the meantime carry
   * `Sunset` and `X-Api-Key-Warning` headers announcing when it stops working.
   * The key's expiry is left alone unless `expiresInDays` is sent. Rotating an
   * **expired** key revives it: `expiresInDays` is then required (send null for
   * no expiry) and a grace period is not allowed. A rotation whose grace period
   * has already run out is completed before this one starts.
   *
   * @param apiKeyId The id of the API key.
   * @param gracePeriodInHours How long the current value keeps authenticating
   *   alongside the new one, in hours from now — a duration, not a date, stored
   *   on the key as `rotatesAt` and never set past `expiresAt`. Defaults to 0,
   *   which replaces the value immediately and stops the old one at once.
   * @param expiresInDays A new lifetime for the key, in days from now — a
   *   duration, not a date, stored on the key as `expiresAt`. Omit it to keep
   *   the current expiry, or send null to remove the expiry altogether.
   *   Required when rotating a key that has already expired.
   */
  async rotateApiKey(
    apiKeyId: string,
    gracePeriodInHours?: number,
    expiresInDays?: number | null,
  ): Promise<RotatedApiKey> {
    return this.client.rotateApiKey(
      this.projectIdOrThrow(),
      apiKeyId,
      gracePeriodInHours,
      expiresInDays,
    );
  }

  /**
   * List Project Members
   *
   * Lists the members of one project a page at a time, each with the project
   * role that decides what they can do inside it. Project members are drawn
   * from the organization's members: someone can belong to the organization and
   * not appear here, and being here is what gives them access to this project's
   * data. Removing a member from the organization removes them from every
   * project in it, this one included.
   *
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of members per page, at most 100. Defaults to
   *   25.
   */
  async listMembers(
    page?: number,
    pageSize?: number,
  ): Promise<ProjectMemberList> {
    return this.client.listMembers(this.projectIdOrThrow(), page, pageSize);
  }

  /**
   * Update Project Member Role
   *
   * Replaces a member's role in this project, which changes what they may do
   * inside it from their next request onwards. Their organization role and
   * their roles in other projects are untouched. Assigning the `Owner` role
   * transfers ownership of the project: the member becomes Owner and the
   * previous Owner is demoted to `Manager` in the same transaction, which is
   * the only way the project Owner's role changes. A role id belonging to
   * another project is rejected.
   *
   * @param userId The id of the user whose membership of this project to
   *   change.
   * @param roleId The id of the role to assign. It must be a Confident AI
   *   built-in role or one of the roles the organization or project owns.
   */
  async updateMemberRole(
    userId: string,
    roleId: string,
  ): Promise<ProjectMember> {
    return this.client.updateMemberRole(
      this.projectIdOrThrow(),
      userId,
      roleId,
    );
  }

  /**
   * Remove Project Member
   *
   * Revokes a member's access to this project only: they are disconnected from
   * it, their project role is deleted, and any invitation still outstanding for
   * their email address on this project is cleared. They keep their
   * organization membership and their access to every other project, so this
   * does not free up a seat. The project Owner cannot be removed, so transfer
   * ownership first. Removal is not reversible through this endpoint — invite
   * the same address to the project again to bring them back, which returns
   * them with the default role rather than the one they had.
   *
   * @param userId The id of the user whose membership of this project to
   *   change.
   */
  async removeMember(userId: string): Promise<MemberRef> {
    return this.client.removeMember(this.projectIdOrThrow(), userId);
  }

  /**
   * List Project Invitations
   *
   * Lists the invitations to this project that are still outstanding — those
   * the invitee has not answered, and those they declined. An invitation drops
   * off this list once it is accepted, since the invitee is a project member
   * from then on, and once it is revoked. Invitations do not expire on their
   * own. Every entry carries the token from the invitee's invite link, so treat
   * the response as sensitive. Invitations to the organization as a whole are
   * listed separately.
   */
  async listInvitations(): Promise<ProjectInvitationList> {
    return this.client.listInvitations(this.projectIdOrThrow());
  }

  /**
   * Create Project Invitations
   *
   * Invites people to this project by email and emails each of them a link.
   * Accepting it adds the invitee to the project and, if they are not already
   * in it, to the organization the project belongs to — so this endpoint can
   * grow the organization, not just the project. Addresses are lowercased and
   * must be company addresses. An address that already has an invitation to
   * this project is dropped from the batch, and so is one that is already a
   * member of it; if that leaves nothing to invite, the whole request is
   * refused as a conflict instead. Note that someone who already belongs to the
   * organization but not to this project is still invitable. `projectRoleId`
   * sets the role every invitee lands on, and the `Owner` role cannot be handed
   * out this way. On the Free plan, the organization's members plus new
   * invitations cannot exceed 2 users. Only the invitations that were created
   * are returned, each with its token.
   *
   * @param emails The email addresses to invite, between 1 and 50 of them. Each
   *   is trimmed and lowercased, and must be a company address — free and
   *   disposable domains are refused.
   * @param projectRoleId The id of the project role every invitee lands on when
   *   they accept. Omit it to give them the default `Member` role. The `Owner`
   *   role cannot be handed out this way.
   */
  async createInvitations(
    emails: string[],
    projectRoleId?: string,
  ): Promise<ProjectInvitationList> {
    return this.client.createInvitations(
      this.projectIdOrThrow(),
      emails,
      projectRoleId,
    );
  }

  /**
   * Resend Project Invitation
   *
   * Emails the project invitation again and returns it. The invitation is reset
   * in the process: its status goes back to `PENDING`, it is stamped with a new
   * creation time, and a fresh token is issued — so any link sent for it
   * earlier stops working. That reset is what revives an invitation the invitee
   * declined. An invitation that was already accepted is reset the same way,
   * which mails the member a link they no longer need without touching the
   * access they already have; revoke the invitation or remove the member
   * instead if that is what you meant. Invitations never expire on their own,
   * so resending is about a link that was lost, not one that timed out.
   *
   * @param invitationId The id of the project invitation.
   */
  async resendInvitation(invitationId: string): Promise<ProjectInvitation> {
    return this.client.resendInvitation(this.projectIdOrThrow(), invitationId);
  }

  /**
   * Revoke Project Invitation
   *
   * Deletes the project invitation, whatever its status, so its link can no
   * longer be accepted and it disappears from the project's invitation list.
   * Only the invitation goes: an invitee who already accepted keeps their place
   * in the project and in the organization, so revoke access by removing them
   * from the project's members instead. Revoking cannot be undone — invite the
   * address again to issue a new invitation with a new token.
   *
   * @param invitationId The id of the project invitation.
   */
  async deleteInvitation(invitationId: string): Promise<InvitationRef> {
    return this.client.deleteInvitation(this.projectIdOrThrow(), invitationId);
  }

  /**
   * List Project Permissions
   *
   * Lists every project permission a project policy can grant. Each is named
   * `resource:action` — `dataset:read`, `golden:create`, `user:manage` — and
   * its id is what you send in a policy's `permissionIds`. The list is
   * Confident AI's whole project catalog, not only the permissions this project
   * already uses, and it is returned in no particular order. It is the same
   * catalog for every project in your organization; organization permissions
   * are a separate catalog with its own endpoint.
   */
  async listPermissions(): Promise<PermissionList> {
    return this.client.listPermissions(this.projectIdOrThrow());
  }

  /**
   * List Project Policies
   *
   * Lists the custom access policies this project owns. Each one is a named set
   * of project permissions, returned with every permission it grants as a
   * `resource:action` pair such as `promptBranch:merge`. These are the policies
   * you attach to this project's roles; the global, system-defined roles do not
   * draw their permissions from policies, so nothing here applies to them. A
   * project's policies are separate from your organization's, and only these
   * can be attached to a project role.
   */
  async listPolicies(): Promise<PolicyList> {
    return this.client.listPolicies(this.projectIdOrThrow());
  }

  /**
   * Create Project Policy
   *
   * Creates a custom policy in this project from a set of permissions and
   * returns it. A policy on its own grants nobody anything: it takes effect
   * only once it is attached to a project role, and then applies to every
   * member holding that role. Send the permission ids from `GET
   * /v2/projects/{projectId}/permissions`, whose names are `resource:action`
   * pairs such as `promptBranch:merge`.
   *
   * @param name The name of the policy, unique within the organization or
   *   project that owns it. It is what identifies the policy when attaching it
   *   to a role.
   * @param permissionIds The ids of the permissions this policy grants. This is
   *   the policy's complete permission set: on an update the list replaces what
   *   is stored rather than adding to it, and an empty array leaves the policy
   *   granting nothing. Discover assignable ids with the permissions endpoint
   *   of the same scope; an id from the other scope's catalog is stored but
   *   never matches a permission check here.
   * @param description What the policy is for. On an update, omit it to leave
   *   the stored description unchanged, or send null to clear it.
   */
  async createPolicy(
    name: string,
    permissionIds: string[],
    description?: string | null,
  ): Promise<Policy> {
    return this.client.createPolicy(
      this.projectIdOrThrow(),
      name,
      permissionIds,
      description,
    );
  }

  /**
   * Update Project Policy
   *
   * Replaces a project policy's name, description, and granted permissions. The
   * change reaches people through the roles the policy is attached to, and it
   * reaches them immediately: permissions are resolved from the role on each
   * request, so every member holding any of those roles gains or loses the
   * affected permissions on their next call. `permissionIds` is the policy's
   * complete permission set rather than an addition to it, so sending an empty
   * array makes the policy grant nothing.
   *
   * @param policyId The id of the project policy.
   * @param name The name of the policy, unique within the organization or
   *   project that owns it. It is what identifies the policy when attaching it
   *   to a role.
   * @param permissionIds The ids of the permissions this policy grants. This is
   *   the policy's complete permission set: on an update the list replaces what
   *   is stored rather than adding to it, and an empty array leaves the policy
   *   granting nothing. Discover assignable ids with the permissions endpoint
   *   of the same scope; an id from the other scope's catalog is stored but
   *   never matches a permission check here.
   * @param description What the policy is for. On an update, omit it to leave
   *   the stored description unchanged, or send null to clear it.
   */
  async updatePolicy(
    policyId: string,
    name: string,
    permissionIds: string[],
    description?: string | null,
  ): Promise<Policy> {
    return this.client.updatePolicy(
      this.projectIdOrThrow(),
      policyId,
      name,
      permissionIds,
      description,
    );
  }

  /**
   * Delete Project Policy
   *
   * Permanently deletes a project policy. Unlike a role, a policy in use is not
   * protected: it is detached from every project role holding it, and members
   * of those roles lose the permissions it granted on their next request. The
   * permissions themselves are not deleted, and the roles survive with their
   * remaining policies — a role left with none can do nothing in the project.
   * Check `GET /v2/projects/{projectId}/roles` for the roles carrying this
   * policy before deleting it. **Warning:** This action cannot be undone.
   *
   * @param policyId The id of the project policy.
   */
  async deletePolicy(policyId: string): Promise<PolicyRef> {
    return this.client.deletePolicy(this.projectIdOrThrow(), policyId);
  }

  /**
   * List Project Roles
   *
   * Lists every role a member of this project can be given: the custom roles
   * the project owns, plus the global, system-defined roles (`projectId` is
   * null) that every project can assign. Each role is returned with the project
   * policies attached to it, which is where its permissions come from — a
   * global role's permissions are system-defined instead, so it comes back with
   * an empty `policies` array. Project roles govern access inside this project
   * only; access to organization-wide settings comes from the member's
   * organization role.
   */
  async listRoles(): Promise<ProjectRoleList> {
    return this.client.listRoles(this.projectIdOrThrow());
  }

  /**
   * Create Project Role
   *
   * Creates a custom role in this project from a set of project policies and
   * returns the role. Its permissions are the union of the permissions granted
   * by the policies in `policyIds`, so a role created with an empty list can do
   * nothing until you attach one. The role grants nobody anything until a
   * project member is assigned to it. The name must be unique among the roles
   * the project can use, including the global, system-defined ones.
   *
   * @param name The name of the role, unique among the roles the organization
   *   or project can use. It cannot match the name of a global, system-defined
   *   role, compared without regard to case.
   * @param policyIds The ids of the policies to attach to the role, which is
   *   what gives the role its permissions. This is the role's complete policy
   *   set: on an update the list replaces what is stored rather than adding to
   *   it, and an empty array leaves the role with no permissions at all.
   *   Discover assignable policies with the policies endpoint of the same
   *   scope.
   * @param description What the role is for. On an update, omit it to leave the
   *   stored description unchanged, or send null to clear it.
   */
  async createRole(
    name: string,
    policyIds: string[],
    description?: string | null,
  ): Promise<ProjectRole> {
    return this.client.createRole(
      this.projectIdOrThrow(),
      name,
      policyIds,
      description,
    );
  }

  /**
   * Update Project Role
   *
   * Replaces a custom project role's name, description, and attached policies.
   * Every member already holding the role is affected immediately: permissions
   * are resolved from the role on each request, so anything the new policy set
   * no longer grants stops working on their next call, and anything it adds
   * becomes available at once. `policyIds` is the role's complete policy set
   * rather than an addition to it, so sending an empty array leaves every
   * member holding the role with no permissions in this project. Only roles the
   * project owns can be updated; a global, system-defined role responds 404.
   *
   * @param roleId The id of the project role. It must be a role the project
   *   owns; a global, system-defined role is not addressable here.
   * @param name The name of the role, unique among the roles the organization
   *   or project can use. It cannot match the name of a global, system-defined
   *   role, compared without regard to case.
   * @param policyIds The ids of the policies to attach to the role, which is
   *   what gives the role its permissions. This is the role's complete policy
   *   set: on an update the list replaces what is stored rather than adding to
   *   it, and an empty array leaves the role with no permissions at all.
   *   Discover assignable policies with the policies endpoint of the same
   *   scope.
   * @param description What the role is for. On an update, omit it to leave the
   *   stored description unchanged, or send null to clear it.
   */
  async updateRole(
    roleId: string,
    name: string,
    policyIds: string[],
    description?: string | null,
  ): Promise<ProjectRole> {
    return this.client.updateRole(
      this.projectIdOrThrow(),
      roleId,
      name,
      policyIds,
      description,
    );
  }

  /**
   * Delete Project Role
   *
   * Permanently deletes a custom project role. A role that is still assigned to
   * at least one member cannot be deleted — the request fails and you must
   * first move those members onto another role — so deleting a role never
   * silently strips anyone of their access. The policies that were attached to
   * it are not deleted and stay available to other roles in the project. Only
   * roles the project owns can be deleted; a global, system-defined role
   * responds 404. **Warning:** This action cannot be undone.
   *
   * @param roleId The id of the project role. It must be a role the project
   *   owns; a global, system-defined role is not addressable here.
   */
  async deleteRole(roleId: string): Promise<RoleRef> {
    return this.client.deleteRole(this.projectIdOrThrow(), roleId);
  }

  /**
   * Get Project Model
   *
   * Returns the model in effect for the project, selected by the required
   * `type` query parameter. `EVALUATION` is the LLM judge that scores this
   * project's metrics. `PLATFORM` is the model behind Confident AI's own AI
   * features, like classification, summaries and report generation.
   * `SIMULATION` is the model that simulates user turns in conversation
   * simulations, including multi-turn test runs and red teaming. `source` tells
   * you where the returned model comes from: `project` when the project has an
   * override of its own, `organization` when it follows the organization's
   * default. The evaluation model is always project scoped, so it always
   * reports `project`. Reading never creates configuration, so `model` is null
   * when nothing has been set for that type — which for `PLATFORM` and
   * `SIMULATION` means neither the project nor the organization has configured
   * one.
   *
   * @param type Which of the project's models to read.
   */
  async getModel(
    type:
      | "EVALUATION"
      | "PLATFORM"
      | "SIMULATION"
      | "TEXT_TO_SPEECH"
      | "SPEECH_TO_TEXT",
  ): Promise<ProjectModel> {
    return this.client.getModel(this.projectIdOrThrow(), type);
  }

  /**
   * Set Project Model
   *
   * Sets one of the project's models, selected by the `modelType` path segment.
   * `evaluation` configures the LLM judge that scores this project's metrics.
   * `platform` configures the model behind Confident AI's own AI features, like
   * classification, summaries and report generation. `simulation` configures
   * the model that simulates user turns in conversation simulations, including
   * multi-turn test runs and red teaming. Setting `platform` or `simulation`
   * creates a project override, so the project stops following the
   * organization's default and `source` becomes `project`; remove it with the
   * DELETE method to fall back to that default. The provider's credential must
   * already be configured on the project or the organization; set it first
   * through the model credentials endpoints. A provider your organization's
   * model provider policy does not allow is rejected with a 403. `CONFIDENT_AI`
   * needs no credential and stores a null model name. `maxInputTokens` applies
   * to the platform and simulation models only and is rejected on the
   * `evaluation` path.
   *
   * @param modelType Which of the project's models to act on.
   * @param modelConfig The model to run for the type named in the path. Which
   *   of the two shapes is expected is decided by that `modelType`, not by what
   *   you send: `evaluation` takes the shape without `maxInputTokens`, and
   *   every other type — `platform`, `simulation`, `text-to-speech` and
   *   `speech-to-text` alike — takes the one with it. This replaces the whole
   *   configuration rather than patching it, so a field you omit is stored as
   *   null. `CUSTOM` is rejected: a custom model can only be configured on the
   *   Confident AI platform. Pass a UpdateEvaluationProjectModelRequest or a
   *   UpdatePlatformProjectModelRequest, from confidentai.projects.types.
   */
  async updateModel(
    modelType: string,
    modelConfig: UpdateProjectModelRequest,
  ): Promise<UpdateProjectModelResult> {
    return this.client.updateModel(
      this.projectIdOrThrow(),
      modelType,
      modelConfig,
    );
  }

  /**
   * Clear Project Model Override
   *
   * Removes the project's platform or simulation model override, so the project
   * falls back to the organization's default for that type and the override
   * toggle in its model settings shows as off. The evaluation model cannot be
   * cleared, so the `evaluation` path segment is rejected. Idempotent: it
   * succeeds even when no override exists.
   *
   * @param modelType Which of the project's models to act on.
   */
  async deleteModel(modelType: string): Promise<ClearProjectModelResult> {
    return this.client.deleteModel(this.projectIdOrThrow(), modelType);
  }

  /**
   * Set Project Model Credentials
   *
   * Sets, replaces, or clears a project's stored credential for a single model
   * provider. While the project is still inheriting your organization's
   * credentials, the first write creates a standalone credential set for the
   * project and severs that inheritance rather than writing to the
   * organization's record — so the project then holds only the provider you
   * just sent, and any other provider it was relying on has to be set again
   * here. This is a write-only surface: there is no read endpoint, and the
   * response returns every credential masked. Send `apiKey` for an API-key
   * provider or `modelConfig` for a configuration provider, and null in either
   * to clear what is stored. A provider your organization's model provider
   * policy does not allow cannot have a credential set (403), though clearing
   * one is always permitted.
   *
   * @param apiKey The provider's API key, for the API-key providers only. Send
   *   the raw secret to set it, or null to clear it; a masked value read back
   *   from a response is rejected. Sending it for a configuration provider is
   *   rejected.
   * @param modelConfig The provider's configuration, for the configuration
   *   providers only — for example `azureApiBase`, `azureDeploymentName`,
   *   `azureApiVersion` and `azureApiKey` for `AZURE`. It replaces the stored
   *   configuration wholesale rather than merging into it, so send every key
   *   the provider needs; send null to clear it. It must not be empty and must
   *   not carry masked values read back from a response. Sending it for an API-
   *   key provider is rejected. For `BEDROCK`, always send `regionName` and
   *   `modelId`, then authenticate with either `ACCESS_KEYS` (`awsAccessKeyId`
   *   and `awsSecretAccessKey`) or, when calling the OpenAI-compatible Mantle
   *   API by setting `api` to `MANTLE`, an `authType` of `API_KEY` together
   *   with `apiKey`, an optional `apiBase`, and an optional `projectId` (sent
   *   as the `OpenAI-Project` header so AWS attributes usage and cost to that
   *   Mantle project; letters, numbers, hyphens and underscores only). An API
   *   key only works with the Mantle API, and assume-role Bedrock
   *   configurations can only be managed on the Confident AI platform.
   */
  async updateModelCredentials(
    provider: ModelProvider,
    apiKey?: string | null,
    modelConfig?: Record<string, unknown> | null,
  ): Promise<ModelCredentials> {
    return this.client.updateModelCredentials(
      this.projectIdOrThrow(),
      provider,
      apiKey,
      modelConfig,
    );
  }

  /**
   * Create Project Audit Log Export
   *
   * Starts an export of one project's audit logs — every audited action
   * recorded against that project — as a gzipped CSV, and returns the export to
   * poll. Use the organization endpoint instead to cover every project at once.
   * Send an empty body (`{}`) to export every audit log ever recorded for the
   * project. Send `startTime` and `endTime` together to export a single period
   * instead: both ends are inclusive, `endTime` must be after `startTime`, and
   * an audit log export has no cap on how long that period may be. `searchTerm`
   * narrows it further. The `startTime` and `endTime` on the returned export
   * are the period its file will cover — for an all-time export, the timestamps
   * of the oldest and newest audit log matched. The export runs in the
   * background, so this responds `202` with `status: IN_PROGRESS` as soon as
   * the job is queued. Poll `GET /v2/projects/{projectId}/audit-
   * logs/exports/{exportId}` until `status` is `COMPLETED`; there is nothing to
   * fetch before then. Then call `GET /v2/projects/{projectId}/audit-
   * logs/exports/{exportId}/download`, which responds `302` with a `Location`
   * header pointing at a pre-signed object storage URL valid for 15 minutes —
   * follow the redirect to receive the file, and call the endpoint again rather
   * than storing that URL. `ERRORED` is terminal: read `errorMessage` and start
   * a new export rather than polling on. One audit log export runs at a time
   * per project and caller, so starting a second while one is `IN_PROGRESS`
   * returns `409`. A period matching no audit logs, or matching more than
   * 10,000,000 audit logs, is rejected with `400` — narrow it with `searchTerm`
   * or a shorter period.
   *
   * @param startTime Start of the period to export, inclusive, as an ISO 8601
   *   timestamp. Omit along with `endTime` to export all time.
   * @param endTime End of the period to export, inclusive, as an ISO 8601
   *   timestamp. Must be after `startTime`. Omit along with `startTime` to
   *   export all time.
   * @param searchTerm Only export audit logs matching this term. Matched as a
   *   substring against the actor email, API key name, API key id, actor type,
   *   action, HTTP method, IP address, resource id, user agent, and status
   *   code.
   */
  async createAuditLogExport(
    options: { startTime?: string; endTime?: string; searchTerm?: string } = {},
  ): Promise<AuditLogExport> {
    return this.client.createAuditLogExport(this.projectIdOrThrow(), options);
  }

  /**
   * Get Project Audit Log Export
   *
   * Retrieves a project audit log export, so that a caller can poll one it
   * started. `status` is `IN_PROGRESS` while the file is being written,
   * `COMPLETED` once the file is in storage and ready to download, or `ERRORED`
   * if the run failed, in which case `errorMessage` says why. `rowCount` is
   * null until the export completes and then reports how many audit logs its
   * file holds, and `startTime` and `endTime` are the period that file covers.
   * Poll here rather than at the download endpoint, which has nothing to serve
   * until `status` is `COMPLETED`. An export is kept for 24 hours after it was
   * created, or 5 minutes once it has failed, after which this returns `404`.
   * The lookup is by id among the exports you started in this project and is
   * not restricted to audit log exports, so an id belonging to another kind of
   * export comes back with its own `exportType`.
   *
   * @param exportId The id of the audit log export, as returned when it was
   *   created.
   */
  async getAuditLogExport(exportId: string): Promise<AuditLogExport> {
    return this.client.getAuditLogExport(this.projectIdOrThrow(), exportId);
  }

  /**
   * Retrieve Project
   *
   * Retrieves a single project by id, including the governance policy it is
   * enrolled in. The project must belong to the organization your API key is
   * scoped to; one belonging to another organization is reported as not found
   * rather than as forbidden.
   */
  async get(): Promise<this> {
    const payload = await this.client.get(this.projectIdOrThrow());
    this.load(payload);
    return this;
  }

  /**
   * Update Project
   *
   * Renames a project or changes its description, and returns the project as
   * stored. Send at least one field; a field you omit is left as it is. A name
   * already taken by another project in the organization is refused.
   */
  async update(): Promise<ProjectPayload> {
    const body = this.updateBody();
    const result = await this.client.update(
      this.projectIdOrThrow(),
      body.name,
      body.description,
    );
    this.projectId = result.id;
    return result;
  }

  private updateBody(): UpdateProjectRequest {
    const fields = { name: this.name, description: this.description };
    return fields as UpdateProjectRequest;
  }

  private load(payload: ProjectPayload): void {
    const source = payload as unknown as Record<string, unknown>;
    this.id = source["id"] as typeof this.id;
    this.name = source["name"] as typeof this.name;
    this.description = source["description"] as typeof this.description;
    this.organizationId = source[
      "organizationId"
    ] as typeof this.organizationId;
    this.created_at = source["created_at"] as typeof this.created_at;
    this.governancePolicy = source[
      "governancePolicy"
    ] as typeof this.governancePolicy;
  }

  private projectIdOrThrow(): string {
    if (this.projectId === undefined) {
      throw new Error(
        "This project has no projectId. Initialize it with " +
          "client.project(projectId), or create it first.",
      );
    }
    return this.projectId;
  }
}
