// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: projects).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api } from "../api";
import { ProjectsClient } from "./client";
import {
  ApiKey,
  ApiKeyList,
  ApiKeyRef,
  AuditLogExport,
  CreatedApiKey,
  InvitationRef,
  MemberRef,
  ModelCredentials,
  ModelProvider,
  PermissionList,
  Policy,
  PolicyList,
  PolicyRef,
  RoleRef,
  RotatedApiKey,
} from "../common/types";
import {
  ClearProjectModelResult,
  Project as ProjectPayload,
  ProjectGovernancePolicy,
  ProjectInvitation,
  ProjectInvitationList,
  ProjectMember,
  ProjectMemberList,
  ProjectModel,
  ProjectRef,
  ProjectRole,
  ProjectRoleList,
  UpdateProjectModelRequest,
  UpdateProjectModelResult,
  UpdateProjectRequest,
} from "./types";

/**
 * One project of your project, held by its projectId.
 *
 * Its methods are ProjectsClient's, minus the
 * `projectId` that this object supplies.
 */
export class Project {
  private readonly client: ProjectsClient;

  projectId?: string;
  id?: string;
  name?: string;
  description?: string | null;
  organizationId?: string;
  created_at?: string;
  governancePolicy?: ProjectGovernancePolicy | null;

  constructor(api: Api, options: { projectId?: string } = {}) {
    this.client = new ProjectsClient(api);
    this.projectId = options.projectId;
  }

  /**
   * Delete Project
   *
   * Permanently deletes a project. **This cannot be undone, and it cascades**
   * to everything held under it: API keys (including one an SDK may be
   * configured with), members and role assignments, invitations, datasets,
   * prompts, metrics, test runs, dashboards, annotation queues, red teaming
   * frameworks, policies, alerts and export schedules. Ingested traces and
   * spans stop being reachable. There is no confirmation step, so the safe way
   * to retire a project is to deactivate its API keys first. Its name becomes
   * available for reuse.
   */
  async delete(): Promise<ProjectRef> {
    return this.client.delete(this.projectIdOrThrow());
  }

  /**
   * List Project API Keys
   *
   * Lists every API key scoped to the project, newest first. Each key's `value`
   * is masked — the full value is only ever returned once, by the response that
   * issues it. A rotation whose grace period has already run out is completed
   * before the list is read, so a `shadowValue` here is always still in flight.
   */
  async listApiKeys(): Promise<ApiKeyList> {
    return this.client.listApiKeys(this.projectIdOrThrow());
  }

  /**
   * Create Project API Key
   *
   * Mints a new project-scoped API key. The full `value` is returned **exactly
   * once**, in this response, and can never be retrieved again — store it
   * securely. This is the key your application uses to send traces and run
   * evaluations against the project.
   *
   * @param name A label for the key, shown on the Confident AI platform.
   * @param expiresInDays How long the key lasts, in days from now — a duration,
   *   not a date. Confident AI turns it into the `expiresAt` instant on the
   *   key. Omit it for a key that never expires.
   */
  async createApiKey(
    name: string,
    expiresInDays?: number,
  ): Promise<CreatedApiKey> {
    return this.client.createApiKey(
      this.projectIdOrThrow(),
      name,
      expiresInDays,
    );
  }

  /**
   * Get Project API Key
   *
   * Retrieves one project-scoped API key by id, with its `value` masked. A
   * `rotatesAt` in the past means the grace period is over and the outgoing
   * value is already rejected on authentication, even though this endpoint
   * still shows it; listing the keys completes the rotation.
   *
   * @param apiKeyId The id of the API key.
   */
  async getApiKey(apiKeyId: string): Promise<ApiKey> {
    return this.client.getApiKey(this.projectIdOrThrow(), apiKeyId);
  }

  /**
   * Update Project API Key
   *
   * Activates or deactivates a project-scoped API key. A deactivated key is
   * rejected on authentication from the next request onwards, so anything still
   * sending traces with it starts failing; its value is unchanged and
   * reactivating it brings the same value back. Rotating is the only way to
   * change the value.
   *
   * @param apiKeyId The id of the API key.
   * @param valid Send false to deactivate the key, true to reactivate it. A
   *   deactivated key is rejected on every request, and deactivating one takes
   *   effect immediately.
   */
  async updateApiKey(apiKeyId: string, valid: boolean): Promise<ApiKey> {
    return this.client.updateApiKey(this.projectIdOrThrow(), apiKeyId, valid);
  }

  /**
   * Revoke Project API Key
   *
   * Permanently revokes a project-scoped API key. Both its current value and
   * any replacement value in flight stop authenticating at once, so anything
   * still sending traces with it starts failing. This cannot be undone — a new
   * key has to be created in its place.
   *
   * @param apiKeyId The id of the API key.
   */
  async deleteApiKey(apiKeyId: string): Promise<ApiKeyRef> {
    return this.client.deleteApiKey(this.projectIdOrThrow(), apiKeyId);
  }

  /**
   * Rotate Project API Key
   *
   * Rotates a project-scoped API key in place — same id, name and history, and
   * no second key is created. The new value is returned **exactly once**, in
   * this response. Requests made with the outgoing value during a grace period
   * carry `Sunset` and `X-Api-Key-Warning` headers, which is the window to
   * redeploy. Reviving an expired key cannot take a grace period.
   *
   * @param apiKeyId The id of the API key.
   * @param gracePeriodInHours How long the current value keeps authenticating
   *   alongside the new one, in hours from now — a duration, not a date, stored
   *   on the key as `rotatesAt` and never set past `expiresAt`. Defaults to 0,
   *   which replaces the value immediately and stops the old one at once.
   * @param expiresInDays A new lifetime for the key, in days from now — a
   *   duration, not a date, stored on the key as `expiresAt`. Omit it to keep
   *   the current expiry, or send null to remove the expiry altogether.
   *   Required when rotating a key that has already expired.
   */
  async rotateApiKey(
    apiKeyId: string,
    gracePeriodInHours?: number,
    expiresInDays?: number | null,
  ): Promise<RotatedApiKey> {
    return this.client.rotateApiKey(
      this.projectIdOrThrow(),
      apiKeyId,
      gracePeriodInHours,
      expiresInDays,
    );
  }

  /**
   * List Project Members
   *
   * Lists the members of one project a page at a time. Project members are
   * drawn from the organization's members: someone can belong to the
   * organization and not appear here, and being here is what gives them access
   * to this project's data.
   *
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of members per page, at most 100. Defaults to
   *   25.
   */
  async listMembers(
    page?: number,
    pageSize?: number,
  ): Promise<ProjectMemberList> {
    return this.client.listMembers(this.projectIdOrThrow(), page, pageSize);
  }

  /**
   * Update Project Member Role
   *
   * Replaces a member's role in this project, which changes what they may do
   * inside it from their next request onwards. Their organization role and
   * their roles in other projects are untouched. Assigning the `Owner` role
   * transfers ownership of the project: the member becomes Owner and the
   * previous Owner is demoted to `Manager` in the same transaction, which is
   * the only way the project Owner's role changes.
   *
   * @param userId The id of the user whose membership of this project to
   *   change.
   * @param roleId The id of the role to assign. It must be a Confident AI
   *   built-in role or one of the roles the organization or project owns.
   */
  async updateMemberRole(
    userId: string,
    roleId: string,
  ): Promise<ProjectMember> {
    return this.client.updateMemberRole(
      this.projectIdOrThrow(),
      userId,
      roleId,
    );
  }

  /**
   * Remove Project Member
   *
   * Revokes a member's access to this project only: they are disconnected from
   * it, their project role is deleted, and any outstanding invitation for their
   * email on this project is cleared. They keep their organization membership
   * and access to every other project, so this does not free up a seat. The
   * project Owner cannot be removed, so transfer ownership first. Inviting the
   * same address again brings them back with the default role rather than the
   * one they had.
   *
   * @param userId The id of the user whose membership of this project to
   *   change.
   */
  async removeMember(userId: string): Promise<MemberRef> {
    return this.client.removeMember(this.projectIdOrThrow(), userId);
  }

  /**
   * List Project Invitations
   *
   * Lists the invitations to this project that are still outstanding — those
   * the invitee has not answered, and those they declined. An invitation drops
   * off this list once it is accepted or revoked, and invitations do not expire
   * on their own. Every entry carries the token from the invitee's invite link,
   * so treat the response as sensitive. Invitations to the organization as a
   * whole are listed separately.
   */
  async listInvitations(): Promise<ProjectInvitationList> {
    return this.client.listInvitations(this.projectIdOrThrow());
  }

  /**
   * Create Project Invitations
   *
   * Invites people to this project by email, each with a link. Accepting can
   * grow the organization too, not just the project. Addresses that already
   * have an invitation to this project, or already belong to it, are dropped
   * from the batch; if that leaves nothing, the request is refused as a
   * conflict. The Free plan caps the organization's members plus invitations at
   * 2. Only the invitations created are returned.
   *
   * @param emails The email addresses to invite, between 1 and 50 of them. Each
   *   is trimmed and lowercased, and must be a company address — free and
   *   disposable domains are refused.
   * @param projectRoleId The id of the project role every invitee lands on when
   *   they accept. Omit it to give them the default `Member` role. The `Owner`
   *   role cannot be handed out this way.
   */
  async createInvitations(
    emails: string[],
    projectRoleId?: string,
  ): Promise<ProjectInvitationList> {
    return this.client.createInvitations(
      this.projectIdOrThrow(),
      emails,
      projectRoleId,
    );
  }

  /**
   * Resend Project Invitation
   *
   * Emails the project invitation again and returns it, resetting it in the
   * process: the status goes back to `PENDING`, a fresh token is issued, and
   * any link sent earlier stops working. That reset is what revives an
   * invitation the invitee declined. An invitation that was already accepted is
   * reset the same way, mailing the member a link they no longer need without
   * touching the access they have — revoke the invitation or remove the member
   * instead if that is what you meant.
   *
   * @param invitationId The id of the project invitation.
   */
  async resendInvitation(invitationId: string): Promise<ProjectInvitation> {
    return this.client.resendInvitation(this.projectIdOrThrow(), invitationId);
  }

  /**
   * Revoke Project Invitation
   *
   * Deletes the project invitation, whatever its status, so its link can no
   * longer be accepted. Only the invitation goes: an invitee who already
   * accepted keeps their place in the project and the organization, so revoke
   * access by removing them from the project's members instead. This cannot be
   * undone — invite the address again to issue a new invitation with a new
   * token.
   *
   * @param invitationId The id of the project invitation.
   */
  async deleteInvitation(invitationId: string): Promise<InvitationRef> {
    return this.client.deleteInvitation(this.projectIdOrThrow(), invitationId);
  }

  /**
   * List Project Permissions
   *
   * Lists every project permission a project policy can grant. Each is named
   * `resource:action` — `dataset:read`, `golden:create` — and its id is what
   * you send in a policy's `permissionIds`. This is Confident AI's whole
   * project catalog, not only the permissions this project already uses, and it
   * is the same catalog for every project in your organization. Organization
   * permissions are a separate catalog with its own endpoint.
   */
  async listPermissions(): Promise<PermissionList> {
    return this.client.listPermissions(this.projectIdOrThrow());
  }

  /**
   * List Project Policies
   *
   * Lists the custom access policies this project owns. Each is a named set of
   * project permissions, returned with every permission it grants as a
   * `resource:action` pair such as `promptBranch:merge`. These are what you
   * attach to this project's roles; the global, system-defined roles do not
   * draw their permissions from policies, so nothing here applies to them. A
   * project's policies are separate from your organization's.
   */
  async listPolicies(): Promise<PolicyList> {
    return this.client.listPolicies(this.projectIdOrThrow());
  }

  /**
   * Create Project Policy
   *
   * Creates a custom policy in this project from a set of permissions and
   * returns it. A policy on its own grants nobody anything: it takes effect
   * only once it is attached to a project role, and then applies to every
   * member holding that role.
   *
   * @param name The name of the policy, unique within the organization or
   *   project that owns it. It is what identifies the policy when attaching it
   *   to a role.
   * @param permissionIds The ids of the permissions this policy grants. This is
   *   the policy's complete permission set: on an update the list replaces what
   *   is stored rather than adding to it, and an empty array leaves the policy
   *   granting nothing. Discover assignable ids with the permissions endpoint
   *   of the same scope; an id from the other scope's catalog is stored but
   *   never matches a permission check here.
   * @param description What the policy is for. On an update, omit it to leave
   *   the stored description unchanged, or send null to clear it.
   */
  async createPolicy(
    name: string,
    permissionIds: string[],
    description?: string | null,
  ): Promise<Policy> {
    return this.client.createPolicy(
      this.projectIdOrThrow(),
      name,
      permissionIds,
      description,
    );
  }

  /**
   * Update Project Policy
   *
   * Replaces a project policy's name, description, and granted permissions. The
   * change reaches people through the roles the policy is attached to, and it
   * reaches them immediately: every member holding any of those roles gains or
   * loses the affected permissions on their next call.
   *
   * @param policyId The id of the project policy.
   * @param name The name of the policy, unique within the organization or
   *   project that owns it. It is what identifies the policy when attaching it
   *   to a role.
   * @param permissionIds The ids of the permissions this policy grants. This is
   *   the policy's complete permission set: on an update the list replaces what
   *   is stored rather than adding to it, and an empty array leaves the policy
   *   granting nothing. Discover assignable ids with the permissions endpoint
   *   of the same scope; an id from the other scope's catalog is stored but
   *   never matches a permission check here.
   * @param description What the policy is for. On an update, omit it to leave
   *   the stored description unchanged, or send null to clear it.
   */
  async updatePolicy(
    policyId: string,
    name: string,
    permissionIds: string[],
    description?: string | null,
  ): Promise<Policy> {
    return this.client.updatePolicy(
      this.projectIdOrThrow(),
      policyId,
      name,
      permissionIds,
      description,
    );
  }

  /**
   * Delete Project Policy
   *
   * Permanently deletes a project policy. Unlike a role, a policy in use is not
   * protected: it is detached from every project role holding it, and members
   * of those roles lose the permissions it granted on their next request. The
   * permissions themselves survive, as do the roles — though a role left with
   * no policies can do nothing in the project. List the project's roles first
   * to see which carry this policy.
   *
   * @param policyId The id of the project policy.
   */
  async deletePolicy(policyId: string): Promise<PolicyRef> {
    return this.client.deletePolicy(this.projectIdOrThrow(), policyId);
  }

  /**
   * List Project Roles
   *
   * Lists every role a member of this project can be given: the custom roles
   * the project owns, plus the global, system-defined ones (`projectId` is
   * null). Project roles govern access inside this project only; organization-
   * wide settings come from the member's organization role.
   */
  async listRoles(): Promise<ProjectRoleList> {
    return this.client.listRoles(this.projectIdOrThrow());
  }

  /**
   * Create Project Role
   *
   * Creates a custom role in this project from a set of project policies and
   * returns the role. Its permissions are the union of what those policies
   * grant, so a role created with an empty `policyIds` can do nothing until you
   * attach one, and it grants nobody anything until a project member is
   * assigned to it.
   *
   * @param name The name of the role, unique among the roles the organization
   *   or project can use. It cannot match the name of a global, system-defined
   *   role, compared without regard to case.
   * @param policyIds The ids of the policies to attach to the role, which is
   *   what gives the role its permissions. This is the role's complete policy
   *   set: on an update the list replaces what is stored rather than adding to
   *   it, and an empty array leaves the role with no permissions at all.
   *   Discover assignable policies with the policies endpoint of the same
   *   scope.
   * @param description What the role is for. On an update, omit it to leave the
   *   stored description unchanged, or send null to clear it.
   */
  async createRole(
    name: string,
    policyIds: string[],
    description?: string | null,
  ): Promise<ProjectRole> {
    return this.client.createRole(
      this.projectIdOrThrow(),
      name,
      policyIds,
      description,
    );
  }

  /**
   * Update Project Role
   *
   * Replaces a custom project role's name, description, and attached policies.
   * Every member holding the role is affected immediately, since permissions
   * are resolved on each request. A global, system-defined role responds `404`.
   *
   * @param roleId The id of the project role. It must be a role the project
   *   owns; a global, system-defined role is not addressable here.
   * @param name The name of the role, unique among the roles the organization
   *   or project can use. It cannot match the name of a global, system-defined
   *   role, compared without regard to case.
   * @param policyIds The ids of the policies to attach to the role, which is
   *   what gives the role its permissions. This is the role's complete policy
   *   set: on an update the list replaces what is stored rather than adding to
   *   it, and an empty array leaves the role with no permissions at all.
   *   Discover assignable policies with the policies endpoint of the same
   *   scope.
   * @param description What the role is for. On an update, omit it to leave the
   *   stored description unchanged, or send null to clear it.
   */
  async updateRole(
    roleId: string,
    name: string,
    policyIds: string[],
    description?: string | null,
  ): Promise<ProjectRole> {
    return this.client.updateRole(
      this.projectIdOrThrow(),
      roleId,
      name,
      policyIds,
      description,
    );
  }

  /**
   * Delete Project Role
   *
   * Permanently deletes a custom project role. A role still assigned to at
   * least one member cannot be deleted — move those members onto another role
   * first — so deleting a role never silently strips anyone of their access.
   * The policies attached to it are not deleted and stay available to other
   * roles in the project. A global, system-defined role responds `404`. **This
   * cannot be undone.**
   *
   * @param roleId The id of the project role. It must be a role the project
   *   owns; a global, system-defined role is not addressable here.
   */
  async deleteRole(roleId: string): Promise<RoleRef> {
    return this.client.deleteRole(this.projectIdOrThrow(), roleId);
  }

  /**
   * Get Project Model
   *
   * Returns which model the project uses for the `type` you ask for. `PLATFORM`
   * and `SIMULATION` fall back to the organization's default when the project
   * has no override of its own; `EVALUATION` is always project scoped. Reading
   * never creates configuration.
   *
   * @param type Which of the project's models to read.
   */
  async getModel(
    type:
      | "EVALUATION"
      | "PLATFORM"
      | "SIMULATION"
      | "TEXT_TO_SPEECH"
      | "SPEECH_TO_TEXT"
      | "DECISION"
      | "SPEECH_TO_SPEECH",
  ): Promise<ProjectModel> {
    return this.client.getModel(this.projectIdOrThrow(), type);
  }

  /**
   * Set Project Model
   *
   * Sets one of the project's models, selected by the `modelType` path segment;
   * `decision` configures the model used by JEVAL metrics. The provider's
   * credential must already be configured on the project or organization, and a
   * provider blocked by the organization's model provider policy is rejected.
   * `CONFIDENT_AI` needs no credential and stores a null model name.
   *
   * @param modelType Which of the project's models to act on.
   * @param modelConfig The model to run for the type named in the path. The
   *   accepted shape is determined by `modelType`: `decision` accepts only
   *   provider and name, `evaluation` also accepts max concurrency, and
   *   platform, simulation, and speech models also accept max input tokens.
   *   This replaces the whole configuration rather than patching it. `CUSTOM`
   *   is rejected. Pass one of UpdateEvaluationProjectModelRequest,
   *   UpdateDecisionProjectModelRequest, UpdatePlatformProjectModelRequest,
   *   from confidentai.projects.types.
   */
  async updateModel(
    modelType: string,
    modelConfig: UpdateProjectModelRequest,
  ): Promise<UpdateProjectModelResult> {
    return this.client.updateModel(
      this.projectIdOrThrow(),
      modelType,
      modelConfig,
    );
  }

  /**
   * Clear Project Model Override
   *
   * Removes a project model override and falls back to the organization's
   * default. Evaluation and decision models cannot be cleared. Idempotent when
   * no override exists.
   *
   * @param modelType Which of the project's models to act on.
   */
  async deleteModel(modelType: string): Promise<ClearProjectModelResult> {
    return this.client.deleteModel(this.projectIdOrThrow(), modelType);
  }

  /**
   * Set Project Model Credentials
   *
   * Sets, replaces, or clears a project's stored credential for a single model
   * provider. While the project is still inheriting your organization's
   * credentials, the first write creates a standalone set for the project and
   * severs that inheritance — so the project then holds only the provider you
   * just sent, and any other provider it relied on has to be set again here.
   * This is a write-only surface: there is no read endpoint, and the response
   * returns every credential masked. A provider your organization's model
   * provider policy does not allow cannot have a credential set (`403`), though
   * clearing one is always permitted.
   *
   * @param apiKey The provider's API key, for the API-key providers only. Send
   *   the raw secret to set it, or null to clear it; a masked value read back
   *   from a response is rejected. Sending it for a configuration provider is
   *   rejected.
   * @param modelConfig The provider's configuration, for the configuration
   *   providers only — for example `azureApiBase`, `azureDeploymentName`,
   *   `azureApiVersion` and `azureApiKey` for `AZURE`. It replaces the stored
   *   configuration wholesale rather than merging into it, so send every key
   *   the provider needs; send null to clear it. It must not be empty and must
   *   not carry masked values read back from a response. Sending it for an API-
   *   key provider is rejected. For `BEDROCK`, always send `regionName` and
   *   `modelId`, then authenticate with either `ACCESS_KEYS` (`awsAccessKeyId`
   *   and `awsSecretAccessKey`) or, when calling the OpenAI-compatible Mantle
   *   API by setting `api` to `MANTLE`, an `authType` of `API_KEY` together
   *   with `apiKey`, an optional `apiBase`, and an optional `projectId` (sent
   *   as the `OpenAI-Project` header so AWS attributes usage and cost to that
   *   Mantle project; letters, numbers, hyphens and underscores only). An API
   *   key only works with the Mantle API, and assume-role Bedrock
   *   configurations can only be managed on the Confident AI platform.
   */
  async updateModelCredentials(
    provider: ModelProvider,
    apiKey?: string | null,
    modelConfig?: Record<string, unknown> | null,
  ): Promise<ModelCredentials> {
    return this.client.updateModelCredentials(
      this.projectIdOrThrow(),
      provider,
      apiKey,
      modelConfig,
    );
  }

  /**
   * Create Project Audit Log Export
   *
   * Starts a background export of one project's audit logs — every audited
   * action recorded against that project — as a gzipped CSV, and responds `202`
   * with the export to poll. Use the organization endpoint to cover every
   * project at once. Poll `GET /v2/projects/{projectId}/audit-
   * logs/exports/{exportId}` until `status` is `COMPLETED`, then call `GET
   * /v2/projects/{projectId}/audit-logs/exports/{exportId}/download` for the
   * file; `ERRORED` is terminal. One export runs at a time per project and
   * caller, so starting a second returns `409`, and a period matching no audit
   * logs, or more than 10,000,000 audit logs, is rejected with `400`.
   *
   * @param startTime Start of the period to export, inclusive, as an ISO 8601
   *   timestamp. Omit along with `endTime` to export all time.
   * @param endTime End of the period to export, inclusive, as an ISO 8601
   *   timestamp. Must be after `startTime`. Omit along with `startTime` to
   *   export all time.
   * @param searchTerm Only export audit logs matching this term. Matched as a
   *   substring against the actor email, API key name, API key id, actor type,
   *   action, HTTP method, IP address, resource id, user agent, and status
   *   code.
   */
  async createAuditLogExport(
    options: { startTime?: string; endTime?: string; searchTerm?: string } = {},
  ): Promise<AuditLogExport> {
    return this.client.createAuditLogExport(this.projectIdOrThrow(), options);
  }

  /**
   * Get Project Audit Log Export
   *
   * Retrieves a project audit log export, so you can poll one you started —
   * poll here rather than at the download endpoint, which has nothing to serve
   * until `status` is `COMPLETED`. An export is kept for 24 hours, or 5 minutes
   * once it has failed, after which this returns `404`. The lookup is not
   * restricted to audit log exports, so another kind of export id comes back
   * with its own `exportType`.
   *
   * @param exportId The id of the audit log export, as returned when it was
   *   created.
   */
  async getAuditLogExport(exportId: string): Promise<AuditLogExport> {
    return this.client.getAuditLogExport(this.projectIdOrThrow(), exportId);
  }

  /**
   * Retrieve Project
   *
   * Retrieves a single project by id, including the governance policy it is
   * enrolled in. A project in another organization is reported as not found
   * rather than as forbidden.
   */
  async get(): Promise<this> {
    const payload = await this.client.get(this.projectIdOrThrow());
    this.load(payload);
    return this;
  }

  /**
   * Update Project
   *
   * Renames a project or changes its description, and returns the project as
   * stored. Send at least one field; a field you omit is left as it is.
   */
  async update(): Promise<ProjectPayload> {
    const body = this.updateBody();
    const result = await this.client.update(
      this.projectIdOrThrow(),
      body.name,
      body.description,
    );
    this.projectId = result.id;
    return result;
  }

  private updateBody(): UpdateProjectRequest {
    const fields = { name: this.name, description: this.description };
    return fields as UpdateProjectRequest;
  }

  private load(payload: ProjectPayload): void {
    const source = payload as unknown as Record<string, unknown>;
    this.id = source["id"] as typeof this.id;
    this.name = source["name"] as typeof this.name;
    this.description = source["description"] as typeof this.description;
    this.organizationId = source[
      "organizationId"
    ] as typeof this.organizationId;
    this.created_at = source["created_at"] as typeof this.created_at;
    this.governancePolicy = source[
      "governancePolicy"
    ] as typeof this.governancePolicy;
  }

  private projectIdOrThrow(): string {
    if (this.projectId === undefined) {
      throw new Error(
        "This project has no projectId. Initialize it with " +
          "client.project(projectId), or create it first.",
      );
    }
    return this.projectId;
  }
}
