# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: projects).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Optional

from confident_ai.api import Api, HttpMethods
from confident_ai.common.types import (
    AuditLogExport,
    CreateAuditLogExportRequest,
)
from confident_ai.endpoints import Endpoints


class AuditLogsExportsOperations:
    _api: Api

    def create_audit_log_export(
        self,
        project_id: str,
        *,
        start_time: Optional[str] = None,
        end_time: Optional[str] = None,
        search_term: Optional[str] = None
    ) -> AuditLogExport:
        """Create Project Audit Log Export

        Starts a background export of one project's audit logs — every audited
        action recorded against that project — as a gzipped CSV, and responds
        `202` with the export to poll. Use the organization endpoint to cover
        every project at once. Poll `GET /v2/projects/{projectId}/audit-
        logs/exports/{exportId}` until `status` is `COMPLETED`, then call `GET
        /v2/projects/{projectId}/audit-logs/exports/{exportId}/download` for the
        file; `ERRORED` is terminal. One export runs at a time per project and
        caller, so starting a second returns `409`, and a period matching no
        audit logs, or more than 10,000,000 audit logs, is rejected with `400`.

        Args:
            project_id: The id of the project whose audit logs are exported. It
                must belong to the organization the API key belongs to.
            start_time: Start of the period to export, inclusive, as an ISO 8601
                timestamp. Omit along with `endTime` to export all time.
            end_time: End of the period to export, inclusive, as an ISO 8601
                timestamp. Must be after `startTime`. Omit along with
                `startTime` to export all time.
            search_term: Only export audit logs matching this term. Matched as a
                substring against the actor email, API key name, API key id,
                actor type, action, HTTP method, IP address, resource id, user
                agent, and status code.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.PROJECT_AUDIT_LOGS_EXPORTS_ENDPOINT,
            response_schema=AuditLogExport,
            request_schema=CreateAuditLogExportRequest,
            body={
                "startTime": start_time,
                "endTime": end_time,
                "searchTerm": search_term,
            },
            path={"projectId": project_id},
        )

    async def a_create_audit_log_export(
        self,
        project_id: str,
        *,
        start_time: Optional[str] = None,
        end_time: Optional[str] = None,
        search_term: Optional[str] = None
    ) -> AuditLogExport:
        """Create Project Audit Log Export

        Starts a background export of one project's audit logs — every audited
        action recorded against that project — as a gzipped CSV, and responds
        `202` with the export to poll. Use the organization endpoint to cover
        every project at once. Poll `GET /v2/projects/{projectId}/audit-
        logs/exports/{exportId}` until `status` is `COMPLETED`, then call `GET
        /v2/projects/{projectId}/audit-logs/exports/{exportId}/download` for the
        file; `ERRORED` is terminal. One export runs at a time per project and
        caller, so starting a second returns `409`, and a period matching no
        audit logs, or more than 10,000,000 audit logs, is rejected with `400`.

        Args:
            project_id: The id of the project whose audit logs are exported. It
                must belong to the organization the API key belongs to.
            start_time: Start of the period to export, inclusive, as an ISO 8601
                timestamp. Omit along with `endTime` to export all time.
            end_time: End of the period to export, inclusive, as an ISO 8601
                timestamp. Must be after `startTime`. Omit along with
                `startTime` to export all time.
            search_term: Only export audit logs matching this term. Matched as a
                substring against the actor email, API key name, API key id,
                actor type, action, HTTP method, IP address, resource id, user
                agent, and status code.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.PROJECT_AUDIT_LOGS_EXPORTS_ENDPOINT,
            response_schema=AuditLogExport,
            request_schema=CreateAuditLogExportRequest,
            body={
                "startTime": start_time,
                "endTime": end_time,
                "searchTerm": search_term,
            },
            path={"projectId": project_id},
        )

    def get_audit_log_export(
        self, project_id: str, export_id: str
    ) -> AuditLogExport:
        """Get Project Audit Log Export

        Retrieves a project audit log export, so you can poll one you started —
        poll here rather than at the download endpoint, which has nothing to
        serve until `status` is `COMPLETED`. An export is kept for 24 hours, or
        5 minutes once it has failed, after which this returns `404`. The lookup
        is not restricted to audit log exports, so another kind of export id
        comes back with its own `exportType`.

        Args:
            project_id: The id of the project whose audit logs are exported. It
                must belong to the organization the API key belongs to.
            export_id: The id of the audit log export, as returned when it was
                created.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.PROJECT_AUDIT_LOGS_EXPORT_ENDPOINT,
            response_schema=AuditLogExport,
            path={"projectId": project_id, "exportId": export_id},
        )

    async def a_get_audit_log_export(
        self, project_id: str, export_id: str
    ) -> AuditLogExport:
        """Get Project Audit Log Export

        Retrieves a project audit log export, so you can poll one you started —
        poll here rather than at the download endpoint, which has nothing to
        serve until `status` is `COMPLETED`. An export is kept for 24 hours, or
        5 minutes once it has failed, after which this returns `404`. The lookup
        is not restricted to audit log exports, so another kind of export id
        comes back with its own `exportType`.

        Args:
            project_id: The id of the project whose audit logs are exported. It
                must belong to the organization the API key belongs to.
            export_id: The id of the audit log export, as returned when it was
                created.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.PROJECT_AUDIT_LOGS_EXPORT_ENDPOINT,
            response_schema=AuditLogExport,
            path={"projectId": project_id, "exportId": export_id},
        )
