# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: ai-connections).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from confidentai.ai_connections.types import (
    AIConnection,
    AIConnectionKeyValue,
    AIConnectionList,
    AIConnectionPayloadMode,
    AIConnectionPingResult,
    AIConnectionPromptBranchRef,
    AIConnectionPromptCommitRef,
    AIConnectionPromptLabelRef,
    AIConnectionPromptRef,
    AIConnectionPromptVersionRef,
    AIConnectionRef,
    AIConnectionResponseMode,
    AIConnectionSummary,
    AIConnectionType,
    CreateAIConnectionRequest,
    PingAIConnectionRequest,
    UpdateAIConnectionRequest,
)

__all__ = [
    "AIConnection",
    "AIConnectionKeyValue",
    "AIConnectionList",
    "AIConnectionPayloadMode",
    "AIConnectionPingResult",
    "AIConnectionPromptBranchRef",
    "AIConnectionPromptCommitRef",
    "AIConnectionPromptLabelRef",
    "AIConnectionPromptRef",
    "AIConnectionPromptVersionRef",
    "AIConnectionRef",
    "AIConnectionResponseMode",
    "AIConnectionSummary",
    "AIConnectionType",
    "CreateAIConnectionRequest",
    "PingAIConnectionRequest",
    "UpdateAIConnectionRequest",
]
