# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: ai-connections).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import Field

from confidentai.types import ConfidentBaseModel


class AIConnectionPayloadMode(Enum):
    JSON = "JSON"
    CODE = "CODE"


class AIConnectionResponseMode(Enum):
    HTTP_RESPONSE = "HTTP_RESPONSE"
    SSE_STREAMING = "SSE_STREAMING"
    HTTP_STREAMING = "HTTP_STREAMING"
    WEBSOCKET = "WEBSOCKET"
    PHONE = "PHONE"
    SIP = "SIP"
    WEBRTC = "WEBRTC"


class AIConnectionType(Enum):
    ENDPOINT = "ENDPOINT"
    RELAY_ENDPOINT = "RELAY_ENDPOINT"
    AGENT_HANDLER = "AGENT_HANDLER"


class AIConnectionKeyValue(ConfidentBaseModel):
    key: str
    value: str


class AIConnectionPromptVersionRef(ConfidentBaseModel):
    alias: str
    version: str


class AIConnectionPromptLabelRef(ConfidentBaseModel):
    alias: str
    label: str


class AIConnectionPromptBranchRef(ConfidentBaseModel):
    alias: str
    branch: str


class AIConnectionPromptCommitRef(ConfidentBaseModel):
    alias: str
    hash: str


AIConnectionPromptRef = Union[
    AIConnectionPromptVersionRef,
    AIConnectionPromptLabelRef,
    AIConnectionPromptBranchRef,
    AIConnectionPromptCommitRef,
]


class AIConnection(ConfidentBaseModel):
    id: str
    name: str
    type: AIConnectionType
    active: bool
    endpoint: Optional[str]
    response_mode: Optional[AIConnectionResponseMode] = Field(
        alias="responseMode",
    )
    async_response: bool = Field(alias="asyncResponse")
    timeout: Optional[int]
    max_concurrency: Optional[int] = Field(alias="maxConcurrency")
    max_retries: Optional[int] = Field(alias="maxRetries")
    default_num_generations: Optional[int] = Field(
        alias="defaultNumGenerations",
    )
    headers: Optional[List[AIConnectionKeyValue]]
    query_params: Optional[List[AIConnectionKeyValue]] = Field(
        alias="queryParams",
    )
    payload: Optional[Dict[str, Any]]
    payload_mode: AIConnectionPayloadMode = Field(alias="payloadMode")
    hyperparameters: Optional[Dict[str, Any]]
    authentication: Optional[Dict[str, Any]]
    cloud_provider: Optional[Dict[str, Any]] = Field(alias="cloudProvider")
    actual_output_key_path: List[Union[str, int]] = Field(
        alias="actualOutputKeyPath",
    )
    retrieval_context_key_path: List[Union[str, int]] = Field(
        alias="retrievalContextKeyPath",
    )
    tools_called_key_path: List[Union[str, int]] = Field(
        alias="toolsCalledKeyPath",
    )
    state_key_path: List[Union[str, int]] = Field(alias="stateKeyPath")
    input_token_count_key_path: List[Union[str, int]] = Field(
        alias="inputTokenCountKeyPath",
    )
    output_token_count_key_path: List[Union[str, int]] = Field(
        alias="outputTokenCountKeyPath",
    )
    token_cost_key_path: List[Union[str, int]] = Field(alias="tokenCostKeyPath")
    actual_output_transformer_id: Optional[str] = Field(
        alias="actualOutputTransformerId",
    )
    retrieval_context_transformer_id: Optional[str] = Field(
        alias="retrievalContextTransformerId",
    )
    tools_called_transformer_id: Optional[str] = Field(
        alias="toolsCalledTransformerId",
    )
    state_transformer_id: Optional[str] = Field(alias="stateTransformerId")
    input_token_count_transformer_id: Optional[str] = Field(
        alias="inputTokenCountTransformerId",
    )
    output_token_count_transformer_id: Optional[str] = Field(
        alias="outputTokenCountTransformerId",
    )
    token_cost_transformer_id: Optional[str] = Field(
        alias="tokenCostTransformerId",
    )
    actual_output_event: Optional[str] = Field(alias="actualOutputEvent")
    retrieval_context_event: Optional[str] = Field(
        alias="retrievalContextEvent",
    )
    tools_called_event: Optional[str] = Field(alias="toolsCalledEvent")
    state_event: Optional[str] = Field(alias="stateEvent")
    actual_output_accumulate: bool = Field(alias="actualOutputAccumulate")
    prompts: Optional[Dict[str, AIConnectionPromptRef]]


class AIConnectionSummary(ConfidentBaseModel):
    id: str
    name: str
    endpoint: Optional[str]
    active: bool


class AIConnectionList(ConfidentBaseModel):
    ai_connections: List[AIConnectionSummary] = Field(alias="aiConnections")
    total_ai_connections: int = Field(alias="totalAIConnections")
    page: int
    page_size: int = Field(alias="pageSize")


class AIConnectionPingResult(ConfidentBaseModel):
    active: bool
    error: Optional[str]
    status_code: Optional[int] = Field(alias="statusCode")
    time_taken: Optional[float] = Field(alias="timeTaken")
    request: Optional[Dict[str, Any]]
    response: Optional[Dict[str, Any]]
    raw_response: Optional[str] = Field(alias="rawResponse")
    actual_output: Optional[str] = Field(alias="actualOutput")
    retrieval_context: Optional[List[str]] = Field(alias="retrievalContext")
    tools_called: Optional[List[Dict[str, Any]]] = Field(alias="toolsCalled")
    state: Optional[Dict[str, Any]]
    input_token_count: Optional[float] = Field(alias="inputTokenCount")
    output_token_count: Optional[float] = Field(alias="outputTokenCount")
    token_cost: Optional[float] = Field(alias="tokenCost")
    invalid_actual_output: bool = Field(alias="invalidActualOutput")
    invalid_retrieval_context: bool = Field(alias="invalidRetrievalContext")
    invalid_tools_called: bool = Field(alias="invalidToolsCalled")
    invalid_state: bool = Field(alias="invalidState")
    invalid_input_token_count: bool = Field(alias="invalidInputTokenCount")
    invalid_output_token_count: bool = Field(alias="invalidOutputTokenCount")
    invalid_token_cost: bool = Field(alias="invalidTokenCost")


class AIConnectionRef(ConfidentBaseModel):
    id: str


class CreateAIConnectionRequest(ConfidentBaseModel):
    name: str
    type: Optional[AIConnectionType] = None
    endpoint: Optional[str] = None
    response_mode: Optional[AIConnectionResponseMode] = Field(
        default=None,
        alias="responseMode",
    )
    async_response: Optional[bool] = Field(default=None, alias="asyncResponse")
    timeout: Optional[int] = None
    max_concurrency: Optional[int] = Field(default=None, alias="maxConcurrency")
    max_retries: Optional[int] = Field(default=None, alias="maxRetries")
    default_num_generations: Optional[int] = Field(
        default=None,
        alias="defaultNumGenerations",
    )
    headers: Optional[List[AIConnectionKeyValue]] = None
    query_params: Optional[List[AIConnectionKeyValue]] = Field(
        default=None,
        alias="queryParams",
    )
    payload: Optional[Dict[str, Any]] = None
    hyperparameters: Optional[Dict[str, Any]] = None
    authentication: Optional[Dict[str, Any]] = None
    cloud_provider: Optional[Dict[str, Any]] = Field(
        default=None,
        alias="cloudProvider",
    )
    actual_output_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="actualOutputKeyPath",
    )
    retrieval_context_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="retrievalContextKeyPath",
    )
    tools_called_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="toolsCalledKeyPath",
    )
    state_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="stateKeyPath",
    )
    input_token_count_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="inputTokenCountKeyPath",
    )
    output_token_count_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="outputTokenCountKeyPath",
    )
    token_cost_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="tokenCostKeyPath",
    )
    actual_output_event: Optional[str] = Field(
        default=None,
        alias="actualOutputEvent",
    )
    retrieval_context_event: Optional[str] = Field(
        default=None,
        alias="retrievalContextEvent",
    )
    tools_called_event: Optional[str] = Field(
        default=None,
        alias="toolsCalledEvent",
    )
    state_event: Optional[str] = Field(default=None, alias="stateEvent")
    actual_output_accumulate: Optional[bool] = Field(
        default=None,
        alias="actualOutputAccumulate",
    )
    actual_output_transformer_id: Optional[str] = Field(
        default=None,
        alias="actualOutputTransformerId",
    )
    retrieval_context_transformer_id: Optional[str] = Field(
        default=None,
        alias="retrievalContextTransformerId",
    )
    tools_called_transformer_id: Optional[str] = Field(
        default=None,
        alias="toolsCalledTransformerId",
    )
    state_transformer_id: Optional[str] = Field(
        default=None,
        alias="stateTransformerId",
    )
    input_token_count_transformer_id: Optional[str] = Field(
        default=None,
        alias="inputTokenCountTransformerId",
    )
    output_token_count_transformer_id: Optional[str] = Field(
        default=None,
        alias="outputTokenCountTransformerId",
    )
    token_cost_transformer_id: Optional[str] = Field(
        default=None,
        alias="tokenCostTransformerId",
    )
    prompts: Optional[Dict[str, AIConnectionPromptRef]] = None


class PingAIConnectionRequest(ConfidentBaseModel):
    multiturn: Optional[bool] = None


class UpdateAIConnectionRequest(ConfidentBaseModel):
    name: Optional[str] = None
    type: Optional[AIConnectionType] = None
    endpoint: Optional[str] = None
    response_mode: Optional[AIConnectionResponseMode] = Field(
        default=None,
        alias="responseMode",
    )
    async_response: Optional[bool] = Field(default=None, alias="asyncResponse")
    timeout: Optional[int] = None
    max_concurrency: Optional[int] = Field(default=None, alias="maxConcurrency")
    max_retries: Optional[int] = Field(default=None, alias="maxRetries")
    default_num_generations: Optional[int] = Field(
        default=None,
        alias="defaultNumGenerations",
    )
    headers: Optional[List[AIConnectionKeyValue]] = None
    query_params: Optional[List[AIConnectionKeyValue]] = Field(
        default=None,
        alias="queryParams",
    )
    payload: Optional[Dict[str, Any]] = None
    hyperparameters: Optional[Dict[str, Any]] = None
    authentication: Optional[Dict[str, Any]] = None
    cloud_provider: Optional[Dict[str, Any]] = Field(
        default=None,
        alias="cloudProvider",
    )
    actual_output_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="actualOutputKeyPath",
    )
    retrieval_context_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="retrievalContextKeyPath",
    )
    tools_called_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="toolsCalledKeyPath",
    )
    state_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="stateKeyPath",
    )
    input_token_count_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="inputTokenCountKeyPath",
    )
    output_token_count_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="outputTokenCountKeyPath",
    )
    token_cost_key_path: Optional[List[Union[str, int]]] = Field(
        default=None,
        alias="tokenCostKeyPath",
    )
    actual_output_event: Optional[str] = Field(
        default=None,
        alias="actualOutputEvent",
    )
    retrieval_context_event: Optional[str] = Field(
        default=None,
        alias="retrievalContextEvent",
    )
    tools_called_event: Optional[str] = Field(
        default=None,
        alias="toolsCalledEvent",
    )
    state_event: Optional[str] = Field(default=None, alias="stateEvent")
    actual_output_accumulate: Optional[bool] = Field(
        default=None,
        alias="actualOutputAccumulate",
    )
    actual_output_transformer_id: Optional[str] = Field(
        default=None,
        alias="actualOutputTransformerId",
    )
    retrieval_context_transformer_id: Optional[str] = Field(
        default=None,
        alias="retrievalContextTransformerId",
    )
    tools_called_transformer_id: Optional[str] = Field(
        default=None,
        alias="toolsCalledTransformerId",
    )
    state_transformer_id: Optional[str] = Field(
        default=None,
        alias="stateTransformerId",
    )
    input_token_count_transformer_id: Optional[str] = Field(
        default=None,
        alias="inputTokenCountTransformerId",
    )
    output_token_count_transformer_id: Optional[str] = Field(
        default=None,
        alias="outputTokenCountTransformerId",
    )
    token_cost_transformer_id: Optional[str] = Field(
        default=None,
        alias="tokenCostTransformerId",
    )
    prompts: Optional[Dict[str, AIConnectionPromptRef]] = None
