# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: widgets).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from confidentai.widgets.types import (
    AdHocWidgetQueryRequest,
    AdHocWidgetQueryResult,
)

__all__ = [
    "AdHocWidgetQueryRequest",
    "AdHocWidgetQueryResult",
]
