# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: widgets).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Optional

from confidentai.api import Api, HttpMethods
from confidentai.common.types import CreateWidgetRequest, WidgetGranularity
from confidentai.endpoints import Endpoints
from confidentai.widgets.types import (
    AdHocWidgetQueryRequest,
    AdHocWidgetQueryResult,
)


class WidgetsClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def query_ad_hoc(
        self,
        widget: CreateWidgetRequest,
        *,
        start_time: Optional[str] = None,
        end_time: Optional[str] = None,
        granularity: Optional[WidgetGranularity] = None
    ) -> AdHocWidgetQueryResult:
        """Query Ad Hoc Widget

        Computes the data for a widget you define inline, without saving it to a
        dashboard. Use it to chart your observability data on demand. Branch on
        `data.kind` to read the result: the widget's `type` and `mode` say how
        it is drawn, not how the payload is shaped. A query accepts at most 20
        lines, a `topK.limit` of at most 100, and a range no longer than 366
        days.

        Args:
            start_time: The start of the range to compute over, as an ISO 8601
                datetime. Must be sent together with `endTime`, and overrides a
                range set on the widget itself.
            end_time: The end of the range to compute over, as an ISO 8601
                datetime. Must be sent together with `startTime`, and must be
                later than it.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.WIDGETS_QUERY_ENDPOINT,
            response_schema=AdHocWidgetQueryResult,
            request_schema=AdHocWidgetQueryRequest,
            body={
                "widget": widget,
                "startTime": start_time,
                "endTime": end_time,
                "granularity": granularity,
            },
        )

    async def a_query_ad_hoc(
        self,
        widget: CreateWidgetRequest,
        *,
        start_time: Optional[str] = None,
        end_time: Optional[str] = None,
        granularity: Optional[WidgetGranularity] = None
    ) -> AdHocWidgetQueryResult:
        """Query Ad Hoc Widget

        Computes the data for a widget you define inline, without saving it to a
        dashboard. Use it to chart your observability data on demand. Branch on
        `data.kind` to read the result: the widget's `type` and `mode` say how
        it is drawn, not how the payload is shaped. A query accepts at most 20
        lines, a `topK.limit` of at most 100, and a range no longer than 366
        days.

        Args:
            start_time: The start of the range to compute over, as an ISO 8601
                datetime. Must be sent together with `endTime`, and overrides a
                range set on the widget itself.
            end_time: The end of the range to compute over, as an ISO 8601
                datetime. Must be sent together with `startTime`, and must be
                later than it.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.WIDGETS_QUERY_ENDPOINT,
            response_schema=AdHocWidgetQueryResult,
            request_schema=AdHocWidgetQueryRequest,
            body={
                "widget": widget,
                "startTime": start_time,
                "endTime": end_time,
                "granularity": granularity,
            },
        )
