// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: projects).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { InvitationsOperations } from "../invitations/operations";
import { MemberRef } from "../../common/types";
import { ProjectMember, ProjectMemberList } from "../types";

export class MembersOperations extends InvitationsOperations {
  /**
   * List Project Members
   *
   * Lists the members of one project a page at a time, each with the project
   * role that decides what they can do inside it. Project members are drawn
   * from the organization's members: someone can belong to the organization and
   * not appear here, and being here is what gives them access to this project's
   * data. Removing a member from the organization removes them from every
   * project in it, this one included.
   *
   * @param projectId The id of the project, which must belong to your
   *   organization.
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of members per page, at most 100. Defaults to
   *   25.
   */
  async listMembers(
    projectId: string,
    page?: number,
    pageSize?: number,
  ): Promise<ProjectMemberList> {
    return this.api.sendRequest<ProjectMemberList>(
      HttpMethods.GET,
      Endpoints.PROJECT_MEMBERS_ENDPOINT,
      { urlParams: { projectId }, params: { page, pageSize } },
    );
  }

  /**
   * Update Project Member Role
   *
   * Replaces a member's role in this project, which changes what they may do
   * inside it from their next request onwards. Their organization role and
   * their roles in other projects are untouched. Assigning the `Owner` role
   * transfers ownership of the project: the member becomes Owner and the
   * previous Owner is demoted to `Manager` in the same transaction, which is
   * the only way the project Owner's role changes. A role id belonging to
   * another project is rejected.
   *
   * @param projectId The id of the project, which must belong to your
   *   organization.
   * @param userId The id of the user whose membership of this project to
   *   change.
   * @param roleId The id of the role to assign. It must be a Confident AI
   *   built-in role or one of the roles the organization or project owns.
   */
  async updateMemberRole(
    projectId: string,
    userId: string,
    roleId: string,
  ): Promise<ProjectMember> {
    return this.api.sendRequest<ProjectMember>(
      HttpMethods.PUT,
      Endpoints.PROJECT_MEMBER_ENDPOINT,
      { body: { roleId }, urlParams: { projectId, userId } },
    );
  }

  /**
   * Remove Project Member
   *
   * Revokes a member's access to this project only: they are disconnected from
   * it, their project role is deleted, and any invitation still outstanding for
   * their email address on this project is cleared. They keep their
   * organization membership and their access to every other project, so this
   * does not free up a seat. The project Owner cannot be removed, so transfer
   * ownership first. Removal is not reversible through this endpoint — invite
   * the same address to the project again to bring them back, which returns
   * them with the default role rather than the one they had.
   *
   * @param projectId The id of the project, which must belong to your
   *   organization.
   * @param userId The id of the user whose membership of this project to
   *   change.
   */
  async removeMember(projectId: string, userId: string): Promise<MemberRef> {
    return this.api.sendRequest<MemberRef>(
      HttpMethods.DELETE,
      Endpoints.PROJECT_MEMBER_ENDPOINT,
      { urlParams: { projectId, userId } },
    );
  }
}
