# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: vulnerabilities).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import List, Literal, Optional

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.vulnerabilities.types import (
    CreateVulnerabilityRequest,
    UpdateVulnerabilityRequest,
    Vulnerability,
    VulnerabilityEvaluationExample,
    VulnerabilityList,
    VulnerabilityRef,
)


class VulnerabilitiesClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list_vulnerabilities(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        category: Optional[str] = None,
        built_in: Optional[Literal["true", "false"]] = None
    ) -> VulnerabilityList:
        """List Vulnerabilities

        Lists the vulnerabilities available to your Confident AI project one
        page at a time: the ones Confident AI ships first, then the ones your
        project defined. Filter by catalog category or by whether a
        vulnerability is built in.

        Args:
            page: The page of vulnerabilities to return. Defaults to 1.
            page_size: The number of vulnerabilities per page, at most 100.
                Defaults to 25.
            category: Returns only vulnerabilities in this catalog category. An
                unknown category is rejected with the list of valid ones.
            built_in: When true, returns only the vulnerabilities Confident AI
                ships; when false, only the ones your project defined. Omit to
                return both.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.VULNERABILITIES_ENDPOINT,
            response_schema=VulnerabilityList,
            query={
                "page": page,
                "pageSize": page_size,
                "category": category,
                "builtIn": built_in,
            },
        )

    async def a_list_vulnerabilities(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        category: Optional[str] = None,
        built_in: Optional[Literal["true", "false"]] = None
    ) -> VulnerabilityList:
        """List Vulnerabilities

        Lists the vulnerabilities available to your Confident AI project one
        page at a time: the ones Confident AI ships first, then the ones your
        project defined. Filter by catalog category or by whether a
        vulnerability is built in.

        Args:
            page: The page of vulnerabilities to return. Defaults to 1.
            page_size: The number of vulnerabilities per page, at most 100.
                Defaults to 25.
            category: Returns only vulnerabilities in this catalog category. An
                unknown category is rejected with the list of valid ones.
            built_in: When true, returns only the vulnerabilities Confident AI
                ships; when false, only the ones your project defined. Omit to
                return both.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.VULNERABILITIES_ENDPOINT,
            response_schema=VulnerabilityList,
            query={
                "page": page,
                "pageSize": page_size,
                "category": category,
                "builtIn": built_in,
            },
        )

    def create_vulnerability(
        self,
        name: str,
        criteria: str,
        vulnerability_types: List[str],
        *,
        description: Optional[str] = None,
        evaluation_guidelines: Optional[List[str]] = None,
        evaluation_examples: Optional[
            List[VulnerabilityEvaluationExample]
        ] = None
    ) -> VulnerabilityRef:
        """Create Vulnerability

        Creates a vulnerability in your Confident AI project and returns its id.
        Give it at least one type: a risk category selects types, not
        vulnerabilities. The name cannot match one Confident AI ships — update
        that one instead to customise it for this project.

        Args:
            name: The name of the vulnerability, unique within the project.
            criteria: The rule the evaluator applies to decide whether a reply
                is vulnerable.
            vulnerability_types: The names of the types this vulnerability
                breaks down into. At least one is required, and they must be
                distinct.
            description: What the vulnerability covers.
            evaluation_guidelines: Extra instructions the evaluator follows when
                applying `criteria`.
            evaluation_examples: Worked examples that steer the evaluator.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.VULNERABILITIES_ENDPOINT,
            response_schema=VulnerabilityRef,
            request_schema=CreateVulnerabilityRequest,
            body={
                "name": name,
                "criteria": criteria,
                "vulnerabilityTypes": vulnerability_types,
                "description": description,
                "evaluationGuidelines": evaluation_guidelines,
                "evaluationExamples": evaluation_examples,
            },
        )

    async def a_create_vulnerability(
        self,
        name: str,
        criteria: str,
        vulnerability_types: List[str],
        *,
        description: Optional[str] = None,
        evaluation_guidelines: Optional[List[str]] = None,
        evaluation_examples: Optional[
            List[VulnerabilityEvaluationExample]
        ] = None
    ) -> VulnerabilityRef:
        """Create Vulnerability

        Creates a vulnerability in your Confident AI project and returns its id.
        Give it at least one type: a risk category selects types, not
        vulnerabilities. The name cannot match one Confident AI ships — update
        that one instead to customise it for this project.

        Args:
            name: The name of the vulnerability, unique within the project.
            criteria: The rule the evaluator applies to decide whether a reply
                is vulnerable.
            vulnerability_types: The names of the types this vulnerability
                breaks down into. At least one is required, and they must be
                distinct.
            description: What the vulnerability covers.
            evaluation_guidelines: Extra instructions the evaluator follows when
                applying `criteria`.
            evaluation_examples: Worked examples that steer the evaluator.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.VULNERABILITIES_ENDPOINT,
            response_schema=VulnerabilityRef,
            request_schema=CreateVulnerabilityRequest,
            body={
                "name": name,
                "criteria": criteria,
                "vulnerabilityTypes": vulnerability_types,
                "description": description,
                "evaluationGuidelines": evaluation_guidelines,
                "evaluationExamples": evaluation_examples,
            },
        )

    def get_vulnerability(self, vulnerability_id: str) -> Vulnerability:
        """Get Vulnerability

        Retrieves a vulnerability by id, with the criteria the evaluator
        applies, the guidelines and examples that steer it, and the types it
        breaks down into.

        Args:
            vulnerability_id: The id of the vulnerability, as the list returns
                it. A built-in's catalog name also resolves.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.VULNERABILITY_ENDPOINT,
            response_schema=Vulnerability,
            path={"vulnerabilityId": vulnerability_id},
        )

    async def a_get_vulnerability(self, vulnerability_id: str) -> Vulnerability:
        """Get Vulnerability

        Retrieves a vulnerability by id, with the criteria the evaluator
        applies, the guidelines and examples that steer it, and the types it
        breaks down into.

        Args:
            vulnerability_id: The id of the vulnerability, as the list returns
                it. A built-in's catalog name also resolves.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.VULNERABILITY_ENDPOINT,
            response_schema=Vulnerability,
            path={"vulnerabilityId": vulnerability_id},
        )

    def update_vulnerability(
        self,
        vulnerability_id: str,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None,
        criteria: Optional[str] = None,
        vulnerability_types: Optional[List[str]] = None,
        evaluation_guidelines: Optional[List[str]] = None,
        evaluation_examples: Optional[
            List[VulnerabilityEvaluationExample]
        ] = None
    ) -> Vulnerability:
        """Update Vulnerability

        Updates a vulnerability and returns it. Updating one Confident AI ships
        makes this project its own copy of it, leaving every other project
        untouched, and a built-in cannot be renamed. Sending
        `vulnerabilityTypes` replaces the stored types, so a name you leave out
        is removed.

        Args:
            vulnerability_id: The id of the vulnerability, as the list returns
                it. A built-in's catalog name also resolves.
            name: The name of the vulnerability, unique within the project.
            description: What the vulnerability covers.
            criteria: The rule the evaluator applies to decide whether a reply
                is vulnerable.
            vulnerability_types: The complete list of type names this
                vulnerability should have. It replaces the stored types: a name
                you leave out is removed, and the names must be distinct.
            evaluation_guidelines: Extra instructions the evaluator follows when
                applying `criteria`.
            evaluation_examples: Worked examples that steer the evaluator.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.VULNERABILITY_ENDPOINT,
            response_schema=Vulnerability,
            request_schema=UpdateVulnerabilityRequest,
            body={
                "name": name,
                "description": description,
                "criteria": criteria,
                "vulnerabilityTypes": vulnerability_types,
                "evaluationGuidelines": evaluation_guidelines,
                "evaluationExamples": evaluation_examples,
            },
            path={"vulnerabilityId": vulnerability_id},
        )

    async def a_update_vulnerability(
        self,
        vulnerability_id: str,
        *,
        name: Optional[str] = None,
        description: Optional[str] = None,
        criteria: Optional[str] = None,
        vulnerability_types: Optional[List[str]] = None,
        evaluation_guidelines: Optional[List[str]] = None,
        evaluation_examples: Optional[
            List[VulnerabilityEvaluationExample]
        ] = None
    ) -> Vulnerability:
        """Update Vulnerability

        Updates a vulnerability and returns it. Updating one Confident AI ships
        makes this project its own copy of it, leaving every other project
        untouched, and a built-in cannot be renamed. Sending
        `vulnerabilityTypes` replaces the stored types, so a name you leave out
        is removed.

        Args:
            vulnerability_id: The id of the vulnerability, as the list returns
                it. A built-in's catalog name also resolves.
            name: The name of the vulnerability, unique within the project.
            description: What the vulnerability covers.
            criteria: The rule the evaluator applies to decide whether a reply
                is vulnerable.
            vulnerability_types: The complete list of type names this
                vulnerability should have. It replaces the stored types: a name
                you leave out is removed, and the names must be distinct.
            evaluation_guidelines: Extra instructions the evaluator follows when
                applying `criteria`.
            evaluation_examples: Worked examples that steer the evaluator.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.VULNERABILITY_ENDPOINT,
            response_schema=Vulnerability,
            request_schema=UpdateVulnerabilityRequest,
            body={
                "name": name,
                "description": description,
                "criteria": criteria,
                "vulnerabilityTypes": vulnerability_types,
                "evaluationGuidelines": evaluation_guidelines,
                "evaluationExamples": evaluation_examples,
            },
            path={"vulnerabilityId": vulnerability_id},
        )

    def delete_vulnerability(self, vulnerability_id: str) -> VulnerabilityRef:
        """Delete Vulnerability

        Permanently deletes a vulnerability your project defined, along with its
        types. A vulnerability Confident AI ships that this project has never
        customised has nothing to delete, and is rejected.

        Args:
            vulnerability_id: The id of the vulnerability, as the list returns
                it. A built-in's catalog name also resolves.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.VULNERABILITY_ENDPOINT,
            response_schema=VulnerabilityRef,
            path={"vulnerabilityId": vulnerability_id},
        )

    async def a_delete_vulnerability(
        self, vulnerability_id: str
    ) -> VulnerabilityRef:
        """Delete Vulnerability

        Permanently deletes a vulnerability your project defined, along with its
        types. A vulnerability Confident AI ships that this project has never
        customised has nothing to delete, and is rejected.

        Args:
            vulnerability_id: The id of the vulnerability, as the list returns
                it. A built-in's catalog name also resolves.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.VULNERABILITY_ENDPOINT,
            response_schema=VulnerabilityRef,
            path={"vulnerabilityId": vulnerability_id},
        )
