// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: organization).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { ApiKeysOperations } from "../api-keys/operations";
import { AuditLogExport } from "../../common/types";

export class AuditLogsExportsOperations extends ApiKeysOperations {
  /**
   * Create Organization Audit Log Export
   *
   * Starts an export of your organization's audit logs — every audited action
   * across every project — as a gzipped CSV, and returns the export to poll.
   * Send an empty body (`{}`) to export every audit log ever recorded. Send
   * `startTime` and `endTime` together to export a single period instead: both
   * ends are inclusive, `endTime` must be after `startTime`, and an audit log
   * export has no cap on how long that period may be. `searchTerm` narrows it
   * further. The `startTime` and `endTime` on the returned export are the
   * period its file will cover — for an all-time export, the timestamps of the
   * oldest and newest audit log matched. The export runs in the background, so
   * this responds `202` with `status: IN_PROGRESS` as soon as the job is
   * queued. Poll `GET /v2/organization/audit-logs/exports/{exportId}` until
   * `status` is `COMPLETED`; there is nothing to fetch before then. Then call
   * `GET /v2/organization/audit-logs/exports/{exportId}/download`, which
   * responds `302` with a `Location` header pointing at a pre-signed object
   * storage URL valid for 15 minutes — follow the redirect to receive the file,
   * and call the endpoint again rather than storing that URL. `ERRORED` is
   * terminal: read `errorMessage` and start a new export rather than polling
   * on. One audit log export runs at a time per organization and caller, so
   * starting a second while one is `IN_PROGRESS` returns `409`. A period
   * matching no audit logs, or matching more than 10,000,000 audit logs, is
   * rejected with `400` — narrow it with `searchTerm` or a shorter period.
   *
   * @param startTime Start of the period to export, inclusive, as an ISO 8601
   *   timestamp. Omit along with `endTime` to export all time.
   * @param endTime End of the period to export, inclusive, as an ISO 8601
   *   timestamp. Must be after `startTime`. Omit along with `startTime` to
   *   export all time.
   * @param searchTerm Only export audit logs matching this term. Matched as a
   *   substring against the actor email, API key name, API key id, actor type,
   *   action, HTTP method, IP address, resource id, user agent, and status
   *   code.
   */
  async createOrganizationAuditLogExport(
    startTime?: string,
    endTime?: string,
    searchTerm?: string,
  ): Promise<AuditLogExport> {
    return this.api.sendRequest<AuditLogExport>(
      HttpMethods.POST,
      Endpoints.ORGANIZATION_AUDIT_LOGS_EXPORTS_ENDPOINT,
      { body: { startTime, endTime, searchTerm } },
    );
  }

  /**
   * Get Organization Audit Log Export
   *
   * Retrieves an organization audit log export, so that a caller can poll one
   * it started. `status` is `IN_PROGRESS` while the file is being written,
   * `COMPLETED` once the file is in storage and ready to download, or `ERRORED`
   * if the run failed, in which case `errorMessage` says why. `rowCount` is
   * null until the export completes and then reports how many audit logs its
   * file holds, and `startTime` and `endTime` are the period that file covers.
   * Poll here rather than at the download endpoint, which has nothing to serve
   * until `status` is `COMPLETED`. An export is kept for 24 hours after it was
   * created, or 5 minutes once it has failed, after which this returns `404`.
   * The lookup is by id among the exports you started and is not restricted to
   * audit log exports, so an id belonging to another kind of export comes back
   * with its own `exportType`.
   *
   * @param exportId The id of the audit log export, as returned when it was
   *   created.
   */
  async getOrganizationAuditLogExport(
    exportId: string,
  ): Promise<AuditLogExport> {
    return this.api.sendRequest<AuditLogExport>(
      HttpMethods.GET,
      Endpoints.ORGANIZATION_AUDIT_LOGS_EXPORT_ENDPOINT,
      { urlParams: { exportId } },
    );
  }
}
