// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: report-templates).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { ScheduleIntervalUnit, ScheduleRecurrenceType } from "../common/types";

export enum ReportTemplateSectionSeverity {
  INFO = "INFO",
  SUCCESS = "SUCCESS",
  WARNING = "WARNING",
  DANGER = "DANGER",
}

export enum ReportTemplateSectionType {
  CONTENT = "CONTENT",
  STAT_CARDS = "STAT_CARDS",
  TABLE = "TABLE",
  GRAPH = "GRAPH",
  ADMONITION = "ADMONITION",
}

export enum ReportTemplateType {
  RISK_ASSESSMENT_REPORT = "RISK_ASSESSMENT_REPORT",
  EXECUTIVE_REPORT = "EXECUTIVE_REPORT",
}

export interface ReportTemplateSectionContent {
  text?: string | null;
  severity?: ReportTemplateSectionSeverity | null;
}

export interface ReportTemplateSectionConfig {
  id?: string;
  type: ReportTemplateSectionType;
  heading?: string | null;
  useAI?: boolean;
  prompt?: string | null;
  content?: ReportTemplateSectionContent | null;
  startOnNewPage?: boolean;
}

export interface CreateReportTemplateRequest {
  name: string;
  description?: string | null;
  templateSections?: ReportTemplateSectionConfig[];
  enabled?: boolean;
  recurrence?: ScheduleRecurrenceType;
  repeatEvery?: number | null;
  repeatUnit?: ScheduleIntervalUnit | null;
  startAt?: string | null;
  maxRuns?: number | null;
  endAt?: string | null;
}

export interface ReportTemplateSchedule {
  recurrence: ScheduleRecurrenceType;
  repeatEvery: number | null;
  repeatUnit: ScheduleIntervalUnit | null;
  startAt: string | null;
  maxRuns: number | null;
  endAt: string | null;
  runCount: number;
  lastRunAt: string | null;
}

export interface ReportTemplateSection {
  id: string;
  type: ReportTemplateSectionType;
  heading: string | null;
  order: number;
  useAI: boolean;
  prompt: string | null;
  content: ReportTemplateSectionContent | null;
  startOnNewPage: boolean;
}

export interface ReportTemplate {
  id: string;
  name: string;
  description: string | null;
  type: ReportTemplateType | null;
  enabled: boolean;
  createdAt: string;
  schedule: ReportTemplateSchedule | null;
  templateSections: ReportTemplateSection[];
}

export interface ReportTemplateSummary {
  id: string;
  name: string;
  description: string | null;
  type: ReportTemplateType | null;
  enabled: boolean;
  createdAt: string;
}

export interface ReportTemplateList {
  reportTemplates: ReportTemplateSummary[];
  totalReportTemplates: number;
  page: number;
  pageSize: number;
}

export interface ReportTemplateRef {
  id: string;
}

export interface UpdateReportTemplateRequest {
  name?: string;
  description?: string | null;
  templateSections?: ReportTemplateSectionConfig[];
  enabled?: boolean;
  recurrence?: ScheduleRecurrenceType;
  repeatEvery?: number | null;
  repeatUnit?: ScheduleIntervalUnit | null;
  startAt?: string | null;
  maxRuns?: number | null;
  endAt?: string | null;
}
