# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: mcp-servers).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Dict, List, Optional

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.mcp_servers.types import (
    CreateMcpServerRequest,
    McpServer,
    McpServerAuthConfig,
    McpServerAuthType,
    McpServerConnection,
    McpServerList,
    McpServerRef,
    McpServerTransport,
    UpdateMcpServerRequest,
)


class McpServersClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> McpServerList:
        """List MCP Servers

        Lists the MCP servers registered in your Confident AI project one page
        at a time, ordered by name. Credentials are never included here —
        neither the static headers nor the OAuth config — so retrieve a server
        by id to see its configuration.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.MCP_SERVERS_ENDPOINT,
            response_schema=McpServerList,
            query={"page": page, "pageSize": page_size},
        )

    async def a_list(
        self, *, page: Optional[int] = None, page_size: Optional[int] = None
    ) -> McpServerList:
        """List MCP Servers

        Lists the MCP servers registered in your Confident AI project one page
        at a time, ordered by name. Credentials are never included here —
        neither the static headers nor the OAuth config — so retrieve a server
        by id to see its configuration.

        Args:
            page: The page to return. Defaults to 1.
            page_size: The number of results per page, at most 100. Defaults to
                25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.MCP_SERVERS_ENDPOINT,
            response_schema=McpServerList,
            query={"page": page, "pageSize": page_size},
        )

    def create(
        self,
        name: str,
        transport: McpServerTransport,
        *,
        description: Optional[str] = None,
        url: Optional[str] = None,
        headers: Optional[Dict[str, str]] = None,
        auth_type: Optional[McpServerAuthType] = None,
        auth_config: Optional[McpServerAuthConfig] = None,
        command: Optional[str] = None,
        args: Optional[List[str]] = None
    ) -> McpServerRef:
        """Create MCP Server

        Registers one of your MCP servers with the project and returns its id.
        Registering does not connect — call the connect route to verify the
        server and discover its tools.

        Args:
            name: The name of the MCP server, unique within the project.
            description: What the MCP server is for. Send null to leave it
                unset.
            url: The URL of the server. Required when `transport` is `HTTP`, and
                cleared otherwise.
            headers: Static headers sent with every request. Only used when
                `authType` is `HEADERS`, and cleared otherwise. This map is
                stored as a whole rather than merged, so send every header you
                want to keep.
            auth_config: The credentials for a non-`HEADERS` auth type. Send
                null to clear them.
            command: The command that launches the server. Required when
                `transport` is `STDIO`, and cleared otherwise.
            args: The arguments passed to `command`. `STDIO` transport only.
                This list is stored as a whole rather than appended to.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.MCP_SERVERS_ENDPOINT,
            response_schema=McpServerRef,
            request_schema=CreateMcpServerRequest,
            body={
                "name": name,
                "transport": transport,
                "description": description,
                "url": url,
                "headers": headers,
                "authType": auth_type,
                "authConfig": auth_config,
                "command": command,
                "args": args,
            },
        )

    async def a_create(
        self,
        name: str,
        transport: McpServerTransport,
        *,
        description: Optional[str] = None,
        url: Optional[str] = None,
        headers: Optional[Dict[str, str]] = None,
        auth_type: Optional[McpServerAuthType] = None,
        auth_config: Optional[McpServerAuthConfig] = None,
        command: Optional[str] = None,
        args: Optional[List[str]] = None
    ) -> McpServerRef:
        """Create MCP Server

        Registers one of your MCP servers with the project and returns its id.
        Registering does not connect — call the connect route to verify the
        server and discover its tools.

        Args:
            name: The name of the MCP server, unique within the project.
            description: What the MCP server is for. Send null to leave it
                unset.
            url: The URL of the server. Required when `transport` is `HTTP`, and
                cleared otherwise.
            headers: Static headers sent with every request. Only used when
                `authType` is `HEADERS`, and cleared otherwise. This map is
                stored as a whole rather than merged, so send every header you
                want to keep.
            auth_config: The credentials for a non-`HEADERS` auth type. Send
                null to clear them.
            command: The command that launches the server. Required when
                `transport` is `STDIO`, and cleared otherwise.
            args: The arguments passed to `command`. `STDIO` transport only.
                This list is stored as a whole rather than appended to.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.MCP_SERVERS_ENDPOINT,
            response_schema=McpServerRef,
            request_schema=CreateMcpServerRequest,
            body={
                "name": name,
                "transport": transport,
                "description": description,
                "url": url,
                "headers": headers,
                "authType": auth_type,
                "authConfig": auth_config,
                "command": command,
                "args": args,
            },
        )

    def get(self, mcp_server_id: str) -> McpServer:
        """Get MCP Server

        Retrieves an MCP server by id, with its full configuration and the tools
        its last successful connection discovered. The stored OAuth client
        secret is not returned: `authConfig.clientSecretPreview` masks it
        instead.

        Args:
            mcp_server_id: The id of the MCP server.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.MCP_SERVER_ENDPOINT,
            response_schema=McpServer,
            path={"mcpServerId": mcp_server_id},
        )

    async def a_get(self, mcp_server_id: str) -> McpServer:
        """Get MCP Server

        Retrieves an MCP server by id, with its full configuration and the tools
        its last successful connection discovered. The stored OAuth client
        secret is not returned: `authConfig.clientSecretPreview` masks it
        instead.

        Args:
            mcp_server_id: The id of the MCP server.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.MCP_SERVER_ENDPOINT,
            response_schema=McpServer,
            path={"mcpServerId": mcp_server_id},
        )

    def update(
        self,
        mcp_server_id: str,
        *,
        name: Optional[str] = None,
        transport: Optional[McpServerTransport] = None,
        description: Optional[str] = None,
        url: Optional[str] = None,
        headers: Optional[Dict[str, str]] = None,
        auth_type: Optional[McpServerAuthType] = None,
        auth_config: Optional[McpServerAuthConfig] = None,
        command: Optional[str] = None,
        args: Optional[List[str]] = None
    ) -> McpServer:
        """Update MCP Server

        Updates an MCP server and returns it. Only the fields you send change,
        and the merged result must be valid — switching `transport` needs that
        transport's required field in the same call. Omit
        `authConfig.clientSecret` to keep the stored secret; the masked
        `clientSecretPreview` you read back is ignored if you send it. Any
        successful update resets `connected` to false, so connect again
        afterwards.

        Args:
            mcp_server_id: The id of the MCP server.
            name: The name of the MCP server, unique within the project.
            description: What the MCP server is for. Send null to leave it
                unset.
            url: The URL of the server. Required when `transport` is `HTTP`, and
                cleared otherwise.
            headers: Static headers sent with every request. Only used when
                `authType` is `HEADERS`, and cleared otherwise. This map is
                stored as a whole rather than merged, so send every header you
                want to keep.
            auth_config: The credentials for a non-`HEADERS` auth type. Send
                null to clear them.
            command: The command that launches the server. Required when
                `transport` is `STDIO`, and cleared otherwise.
            args: The arguments passed to `command`. `STDIO` transport only.
                This list is stored as a whole rather than appended to.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.MCP_SERVER_ENDPOINT,
            response_schema=McpServer,
            request_schema=UpdateMcpServerRequest,
            body={
                "name": name,
                "transport": transport,
                "description": description,
                "url": url,
                "headers": headers,
                "authType": auth_type,
                "authConfig": auth_config,
                "command": command,
                "args": args,
            },
            path={"mcpServerId": mcp_server_id},
        )

    async def a_update(
        self,
        mcp_server_id: str,
        *,
        name: Optional[str] = None,
        transport: Optional[McpServerTransport] = None,
        description: Optional[str] = None,
        url: Optional[str] = None,
        headers: Optional[Dict[str, str]] = None,
        auth_type: Optional[McpServerAuthType] = None,
        auth_config: Optional[McpServerAuthConfig] = None,
        command: Optional[str] = None,
        args: Optional[List[str]] = None
    ) -> McpServer:
        """Update MCP Server

        Updates an MCP server and returns it. Only the fields you send change,
        and the merged result must be valid — switching `transport` needs that
        transport's required field in the same call. Omit
        `authConfig.clientSecret` to keep the stored secret; the masked
        `clientSecretPreview` you read back is ignored if you send it. Any
        successful update resets `connected` to false, so connect again
        afterwards.

        Args:
            mcp_server_id: The id of the MCP server.
            name: The name of the MCP server, unique within the project.
            description: What the MCP server is for. Send null to leave it
                unset.
            url: The URL of the server. Required when `transport` is `HTTP`, and
                cleared otherwise.
            headers: Static headers sent with every request. Only used when
                `authType` is `HEADERS`, and cleared otherwise. This map is
                stored as a whole rather than merged, so send every header you
                want to keep.
            auth_config: The credentials for a non-`HEADERS` auth type. Send
                null to clear them.
            command: The command that launches the server. Required when
                `transport` is `STDIO`, and cleared otherwise.
            args: The arguments passed to `command`. `STDIO` transport only.
                This list is stored as a whole rather than appended to.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.MCP_SERVER_ENDPOINT,
            response_schema=McpServer,
            request_schema=UpdateMcpServerRequest,
            body={
                "name": name,
                "transport": transport,
                "description": description,
                "url": url,
                "headers": headers,
                "authType": auth_type,
                "authConfig": auth_config,
                "command": command,
                "args": args,
            },
            path={"mcpServerId": mcp_server_id},
        )

    def delete(self, mcp_server_id: str) -> McpServerRef:
        """Delete MCP Server

        Permanently deletes an MCP server from your project. This cannot be
        undone, and evaluations and AI connections that used the server stop
        using it.

        Args:
            mcp_server_id: The id of the MCP server.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.MCP_SERVER_ENDPOINT,
            response_schema=McpServerRef,
            path={"mcpServerId": mcp_server_id},
        )

    async def a_delete(self, mcp_server_id: str) -> McpServerRef:
        """Delete MCP Server

        Permanently deletes an MCP server from your project. This cannot be
        undone, and evaluations and AI connections that used the server stop
        using it.

        Args:
            mcp_server_id: The id of the MCP server.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.MCP_SERVER_ENDPOINT,
            response_schema=McpServerRef,
            path={"mcpServerId": mcp_server_id},
        )

    def connect(self, mcp_server_id: str) -> McpServerConnection:
        """Connect MCP Server

        Connects to the MCP server, lists the tools it exposes, and replaces its
        stored `connected` and `availableTools` with the result. This reaches
        out to your own server and can take a few seconds. A server that fails
        to connect is not an error: the response is still 200 with `connected`
        false and `error` set to what went wrong, so read `connected` for the
        verdict.

        Args:
            mcp_server_id: The id of the MCP server.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.MCP_SERVER_CONNECT_ENDPOINT,
            response_schema=McpServerConnection,
            path={"mcpServerId": mcp_server_id},
        )

    async def a_connect(self, mcp_server_id: str) -> McpServerConnection:
        """Connect MCP Server

        Connects to the MCP server, lists the tools it exposes, and replaces its
        stored `connected` and `availableTools` with the result. This reaches
        out to your own server and can take a few seconds. A server that fails
        to connect is not an error: the response is still 200 with `connected`
        false and `error` set to what went wrong, so read `connected` for the
        verdict.

        Args:
            mcp_server_id: The id of the MCP server.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.MCP_SERVER_CONNECT_ENDPOINT,
            response_schema=McpServerConnection,
            path={"mcpServerId": mcp_server_id},
        )
