// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: classifiers).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { LabelsOperations } from "./labels/operations";

export class ClassifiersClient extends LabelsOperations {}
