// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: organization).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { GovernanceControlGroupsOperations } from "../governance-control-groups/operations";
import {
  AssessGovernanceControlResult,
  CreatableGovernanceControlType,
  GovernanceControl,
  GovernanceControlActivity,
  GovernanceControlAssessmentList,
  GovernanceControlList,
  GovernanceControlPreDeploymentConfig,
  GovernanceControlRef,
  GovernanceControlRuntimeConfig,
  GovernanceControlType,
} from "../types";

export class GovernanceControlsOperations extends GovernanceControlGroupsOperations {
  /**
   * List Governance Controls
   *
   * Lists your organization's governance controls, newest created first, each
   * with its health across the projects it governs. A control's definition is
   * not included — read its versions for that. Health is computed from the
   * latest verdict per governed project, so it reflects the current state
   * rather than the whole assessment history.
   *
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of controls per page, at most 100. Defaults to
   *   25.
   */
  async listGovernanceControls(
    options: {
      type?: GovernanceControlType;
      activity?: GovernanceControlActivity;
      page?: number;
      pageSize?: number;
    } = {},
  ): Promise<GovernanceControlList> {
    const { type, activity, page, pageSize } = options;
    return this.api.sendRequest<GovernanceControlList>(
      HttpMethods.GET,
      Endpoints.ORGANIZATION_GOVERNANCE_CONTROLS_ENDPOINT,
      { params: { type, activity, page, pageSize } },
    );
  }

  /**
   * Create Governance Control
   *
   * Creates a governance control and returns its id. Supplying the config that
   * matches the control's `type` snapshots its first version in the same call;
   * omitting it creates the control with no definition, which assesses as ERROR
   * until you add a version. Operational controls are seeded by Confident AI
   * and cannot be created here. A new control governs nothing until a
   * governance policy holds it.
   *
   * @param name The name of the control, unique within your organization.
   * @param description What the control checks and why. Send null to leave it
   *   unset.
   * @param governancePolicyId Accepted but not acted on: the control is created
   *   unattached whether or not you send it. Attach it through the governance
   *   policy's own controls endpoint.
   */
  async createGovernanceControl(
    name: string,
    type: CreatableGovernanceControlType,
    options: {
      description?: string | null;
      runtimeConfig?: GovernanceControlRuntimeConfig;
      preDeploymentConfig?: GovernanceControlPreDeploymentConfig;
      governancePolicyId?: string;
    } = {},
  ): Promise<GovernanceControlRef> {
    const {
      description,
      runtimeConfig,
      preDeploymentConfig,
      governancePolicyId,
    } = options;
    return this.api.sendRequest<GovernanceControlRef>(
      HttpMethods.POST,
      Endpoints.ORGANIZATION_GOVERNANCE_CONTROLS_ENDPOINT,
      {
        body: {
          name,
          type,
          description,
          runtimeConfig,
          preDeploymentConfig,
          governancePolicyId,
        },
      },
    );
  }

  /**
   * Get Governance Control
   *
   * Retrieves a single governance control with its health across the projects
   * it governs and when it was last assessed. The rule it evaluates is not
   * returned here — list the control's versions to read its definition.
   *
   * @param controlId The id of the governance control.
   */
  async getGovernanceControl(controlId: string): Promise<GovernanceControl> {
    return this.api.sendRequest<GovernanceControl>(
      HttpMethods.GET,
      Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_ENDPOINT,
      { urlParams: { controlId } },
    );
  }

  /**
   * Update Governance Control
   *
   * Updates a governance control's name or description and returns it as
   * stored. Both live on the control itself rather than on a version, so this
   * does not snapshot a new version and does not change what the control checks
   * — append a version for that. An operational control's name and description
   * come from Confident AI's registry and cannot be edited.
   *
   * @param controlId The id of the governance control.
   * @param name The name of the control, unique within your organization.
   * @param description What the control checks and why. Send null to clear it.
   */
  async updateGovernanceControl(
    controlId: string,
    name?: string,
    description?: string | null,
  ): Promise<GovernanceControl> {
    return this.api.sendRequest<GovernanceControl>(
      HttpMethods.PUT,
      Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_ENDPOINT,
      { body: { name, description }, urlParams: { controlId } },
    );
  }

  /**
   * Delete Governance Control
   *
   * Permanently deletes a governance control, every version of its definition,
   * and every verdict recorded against it. Any policy holding the control loses
   * it and stops applying that check. **Warning:** This action cannot be
   * undone. To stop a control gating one policy without deleting it, remove it
   * from that policy instead.
   *
   * @param controlId The id of the governance control.
   */
  async deleteGovernanceControl(
    controlId: string,
  ): Promise<GovernanceControlRef> {
    return this.api.sendRequest<GovernanceControlRef>(
      HttpMethods.DELETE,
      Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_ENDPOINT,
      { urlParams: { controlId } },
    );
  }

  /**
   * Assess Governance Control
   *
   * Runs a governance control now against every project it governs and records
   * a fresh verdict per project, rather than waiting for the scheduled sweep. A
   * project is governed when its policy holds the control or extends a base
   * policy that holds it, and the run always uses the control's current
   * version. Each project resolves to one verdict. A RUNTIME control aggregates
   * its data model over the trailing 24 hours and returns FAIL when the result
   * sits on the threshold's `direction` side of it, PASS when it does not, and
   * NO_DATA when the window produced nothing to measure. A pre-deployment
   * control returns PASS when the newest completed run in its window satisfies
   * the control's filters, FAIL when it does not, and NO_DATA when there is no
   * such run. An OPERATIONAL control returns whatever the platform check finds.
   * Any control that is not fully configured, or whose aggregation does not fit
   * its data model, returns ERROR with the reason on the assessment. Every
   * verdict is stored, so it becomes the project's current status for this
   * control and appears in the control's assessment history. Assessments are
   * append-only — running this repeatedly adds rows rather than replacing them.
   * It consumes evaluation resources proportional to the number of governed
   * projects. A control attached to no policy, or one with no version yet,
   * governs nothing and returns zero counts.
   *
   * @param controlId The id of the governance control.
   */
  async assessGovernanceControl(
    controlId: string,
  ): Promise<AssessGovernanceControlResult> {
    return this.api.sendRequest<AssessGovernanceControlResult>(
      HttpMethods.POST,
      Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_ASSESS_ENDPOINT,
      { urlParams: { controlId } },
    );
  }

  /**
   * List Governance Assessments
   *
   * Lists a governance control's recorded verdicts, one per project per run,
   * ordered newest recorded first with ties broken by assessment id. Verdicts
   * belong to the version of the definition they were computed against, so they
   * are read one version at a time: send `version` to read a past version's
   * verdicts, or omit it to read the current version, which the response echoes
   * back. There is no time window — every verdict ever recorded against that
   * version is paginated here, so a control assessed daily across five projects
   * returns five rows per day rather than a single current state. The newest
   * verdict for a project is that project's current status; everything older is
   * history. A control with no versions yet is a 404 rather than an empty list.
   *
   * @param controlId The id of the governance control.
   * @param version The `version` label of the control version to read verdicts
   *   for. Omit it to read the current version, which is the one with the
   *   highest sequence.
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of assessments per page, at most 100. Defaults
   *   to 25.
   */
  async listGovernanceControlAssessments(
    controlId: string,
    options: { version?: string; page?: number; pageSize?: number } = {},
  ): Promise<GovernanceControlAssessmentList> {
    const { version, page, pageSize } = options;
    return this.api.sendRequest<GovernanceControlAssessmentList>(
      HttpMethods.GET,
      Endpoints.ORGANIZATION_GOVERNANCE_CONTROL_ASSESSMENTS_ENDPOINT,
      { urlParams: { controlId }, params: { version, page, pageSize } },
    );
  }
}
