# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: organization).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from confidentai.api import Api
from confidentai.organization.operations import OrganizationOperations
from confidentai.organization.api_keys.operations import ApiKeysOperations
from confidentai.organization.audit_logs_exports.operations import (
    AuditLogsExportsOperations,
)
from confidentai.organization.governance_control_groups.operations import (
    GovernanceControlGroupsOperations,
)
from confidentai.organization.governance_controls.operations import (
    GovernanceControlsOperations,
)
from confidentai.organization.governance_controls.versions.operations import (
    GovernanceControlsVersionsOperations,
)
from confidentai.organization.governance_policies.operations import (
    GovernancePoliciesOperations,
)
from confidentai.organization.governance_policies.controls.operations import (
    GovernancePoliciesControlsOperations,
)
from confidentai.organization.governance_policies.skill.operations import (
    GovernancePoliciesSkillOperations,
)
from confidentai.organization.governance_projects.operations import (
    GovernanceProjectsOperations,
)
from confidentai.organization.invitations.operations import (
    InvitationsOperations,
)
from confidentai.organization.members.operations import MembersOperations
from confidentai.organization.models.operations import ModelsOperations
from confidentai.organization.policies.operations import PoliciesOperations
from confidentai.organization.roles.operations import RolesOperations


class OrganizationClient(
    OrganizationOperations,
    ApiKeysOperations,
    AuditLogsExportsOperations,
    GovernanceControlGroupsOperations,
    GovernanceControlsOperations,
    GovernanceControlsVersionsOperations,
    GovernancePoliciesOperations,
    GovernancePoliciesControlsOperations,
    GovernancePoliciesSkillOperations,
    GovernanceProjectsOperations,
    InvitationsOperations,
    MembersOperations,
    ModelsOperations,
    PoliciesOperations,
    RolesOperations,
):
    def __init__(self, api: Api) -> None:
        self._api = api
