// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: governance).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import { GovernanceAssessment } from "./types";

export class GovernanceClient {
  constructor(protected readonly api: Api) {}

  /**
   * Assess Governance
   *
   * Assesses this project against every control in the governance policy it
   * belongs to, and returns whether they all passed. Call it as a gate in a
   * deployment pipeline: a false `passed` means at least one control is
   * failing. A project that belongs to no governance policy is rejected with a
   * 400.
   */
  async assess(): Promise<GovernanceAssessment> {
    return this.api.sendRequest<GovernanceAssessment>(
      HttpMethods.POST,
      Endpoints.GOVERNANCE_ASSESS_ENDPOINT,
    );
  }
}
