// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: governance).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { GovernancePolicyReference } from "../common/types";

export interface GovernanceAssessment {
  passed: boolean;
  governancePolicy: GovernancePolicyReference;
}
