# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: threads).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import Field

from confidentai.common.types import (
    AnnotationSummary,
    Classification,
    MetricData,
    Trace,
)
from confidentai.types import ConfidentBaseModel


class ThreadSortBy(Enum):
    LASTACTIVITY = "lastActivity"
    CREATEDAT = "createdAt"


class Thread(ConfidentBaseModel):
    id: str
    created_at: str = Field(alias="createdAt")
    last_activity: str = Field(alias="lastActivity")
    metadata: Optional[Dict[str, Any]]
    tags: Optional[List[str]]
    labels: Dict[str, Classification]
    metric_collection_name: Optional[str] = Field(alias="metricCollectionName")
    total_traces: int = Field(alias="totalTraces")
    metrics_data: List[MetricData] = Field(alias="metricsData")
    annotations: List[AnnotationSummary]
    traces: List[Trace]


class ThreadSummary(ConfidentBaseModel):
    id: str
    created_at: str = Field(alias="createdAt")
    last_activity: str = Field(alias="lastActivity")
    metadata: Optional[Dict[str, Any]]
    tags: Optional[List[str]]
    labels: Dict[str, Classification]
    metric_collection_name: Optional[str] = Field(alias="metricCollectionName")
    total_traces: int = Field(alias="totalTraces")


class ThreadList(ConfidentBaseModel):
    threads: List[ThreadSummary]
    total_threads: Optional[int] = Field(default=None, alias="totalThreads")
    next_cursor: Optional[str] = Field(alias="nextCursor")
