# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: projects).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Literal

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.projects.types import (
    ClearProjectModelResult,
    ProjectModel,
    UpdateProjectModelRequest,
    UpdateProjectModelResult,
)


class ModelsOperations:
    _api: Api

    def get_model(
        self,
        project_id: str,
        *,
        type: Literal[
            "EVALUATION",
            "PLATFORM",
            "SIMULATION",
            "TEXT_TO_SPEECH",
            "SPEECH_TO_TEXT",
        ]
    ) -> ProjectModel:
        """Get Project Model

        Returns the model in effect for the project, selected by the required
        `type` query parameter. `EVALUATION` is the LLM judge that scores this
        project's metrics. `PLATFORM` is the model behind Confident AI's own AI
        features, like classification, summaries and report generation.
        `SIMULATION` is the model that simulates user turns in conversation
        simulations, including multi-turn test runs and red teaming. `source`
        tells you where the returned model comes from: `project` when the
        project has an override of its own, `organization` when it follows the
        organization's default. The evaluation model is always project scoped,
        so it always reports `project`. Reading never creates configuration, so
        `model` is null when nothing has been set for that type — which for
        `PLATFORM` and `SIMULATION` means neither the project nor the
        organization has configured one.

        Args:
            project_id: The id of the project, which must belong to the
                organization your API key is scoped to.
            type: Which of the project's models to read.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.PROJECT_MODELS_ENDPOINT,
            response_schema=ProjectModel,
            path={"projectId": project_id},
            query={"type": type},
        )

    async def a_get_model(
        self,
        project_id: str,
        *,
        type: Literal[
            "EVALUATION",
            "PLATFORM",
            "SIMULATION",
            "TEXT_TO_SPEECH",
            "SPEECH_TO_TEXT",
        ]
    ) -> ProjectModel:
        """Get Project Model

        Returns the model in effect for the project, selected by the required
        `type` query parameter. `EVALUATION` is the LLM judge that scores this
        project's metrics. `PLATFORM` is the model behind Confident AI's own AI
        features, like classification, summaries and report generation.
        `SIMULATION` is the model that simulates user turns in conversation
        simulations, including multi-turn test runs and red teaming. `source`
        tells you where the returned model comes from: `project` when the
        project has an override of its own, `organization` when it follows the
        organization's default. The evaluation model is always project scoped,
        so it always reports `project`. Reading never creates configuration, so
        `model` is null when nothing has been set for that type — which for
        `PLATFORM` and `SIMULATION` means neither the project nor the
        organization has configured one.

        Args:
            project_id: The id of the project, which must belong to the
                organization your API key is scoped to.
            type: Which of the project's models to read.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.PROJECT_MODELS_ENDPOINT,
            response_schema=ProjectModel,
            path={"projectId": project_id},
            query={"type": type},
        )

    def update_model(
        self,
        project_id: str,
        model_type: str,
        model_config: UpdateProjectModelRequest,
    ) -> UpdateProjectModelResult:
        """Set Project Model

        Sets one of the project's models, selected by the `modelType` path
        segment. `evaluation` configures the LLM judge that scores this
        project's metrics. `platform` configures the model behind Confident AI's
        own AI features, like classification, summaries and report generation.
        `simulation` configures the model that simulates user turns in
        conversation simulations, including multi-turn test runs and red
        teaming. Setting `platform` or `simulation` creates a project override,
        so the project stops following the organization's default and `source`
        becomes `project`; remove it with the DELETE method to fall back to that
        default. The provider's credential must already be configured on the
        project or the organization; set it first through the model credentials
        endpoints. A provider your organization's model provider policy does not
        allow is rejected with a 403. `CONFIDENT_AI` needs no credential and
        stores a null model name. `maxInputTokens` applies to the platform and
        simulation models only and is rejected on the `evaluation` path.

        Args:
            project_id: The id of the project, which must belong to the
                organization your API key is scoped to.
            model_type: Which of the project's models to act on.
            model_config: The model to run for the type named in the path. Which
                of the two shapes is expected is decided by that `modelType`,
                not by what you send: `evaluation` takes the shape without
                `maxInputTokens`, and every other type — `platform`,
                `simulation`, `text-to-speech` and `speech-to-text` alike —
                takes the one with it. This replaces the whole configuration
                rather than patching it, so a field you omit is stored as null.
                `CUSTOM` is rejected: a custom model can only be configured on
                the Confident AI platform. Pass a
                UpdateEvaluationProjectModelRequest or a
                UpdatePlatformProjectModelRequest, from
                confidentai.projects.types.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.PROJECT_MODEL_ENDPOINT,
            response_schema=UpdateProjectModelResult,
            request_schema=UpdateProjectModelRequest,
            body=model_config,
            path={"projectId": project_id, "modelType": model_type},
        )

    async def a_update_model(
        self,
        project_id: str,
        model_type: str,
        model_config: UpdateProjectModelRequest,
    ) -> UpdateProjectModelResult:
        """Set Project Model

        Sets one of the project's models, selected by the `modelType` path
        segment. `evaluation` configures the LLM judge that scores this
        project's metrics. `platform` configures the model behind Confident AI's
        own AI features, like classification, summaries and report generation.
        `simulation` configures the model that simulates user turns in
        conversation simulations, including multi-turn test runs and red
        teaming. Setting `platform` or `simulation` creates a project override,
        so the project stops following the organization's default and `source`
        becomes `project`; remove it with the DELETE method to fall back to that
        default. The provider's credential must already be configured on the
        project or the organization; set it first through the model credentials
        endpoints. A provider your organization's model provider policy does not
        allow is rejected with a 403. `CONFIDENT_AI` needs no credential and
        stores a null model name. `maxInputTokens` applies to the platform and
        simulation models only and is rejected on the `evaluation` path.

        Args:
            project_id: The id of the project, which must belong to the
                organization your API key is scoped to.
            model_type: Which of the project's models to act on.
            model_config: The model to run for the type named in the path. Which
                of the two shapes is expected is decided by that `modelType`,
                not by what you send: `evaluation` takes the shape without
                `maxInputTokens`, and every other type — `platform`,
                `simulation`, `text-to-speech` and `speech-to-text` alike —
                takes the one with it. This replaces the whole configuration
                rather than patching it, so a field you omit is stored as null.
                `CUSTOM` is rejected: a custom model can only be configured on
                the Confident AI platform. Pass a
                UpdateEvaluationProjectModelRequest or a
                UpdatePlatformProjectModelRequest, from
                confidentai.projects.types.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.PROJECT_MODEL_ENDPOINT,
            response_schema=UpdateProjectModelResult,
            request_schema=UpdateProjectModelRequest,
            body=model_config,
            path={"projectId": project_id, "modelType": model_type},
        )

    def delete_model(
        self, project_id: str, model_type: str
    ) -> ClearProjectModelResult:
        """Clear Project Model Override

        Removes the project's platform or simulation model override, so the
        project falls back to the organization's default for that type and the
        override toggle in its model settings shows as off. The evaluation model
        cannot be cleared, so the `evaluation` path segment is rejected.
        Idempotent: it succeeds even when no override exists.

        Args:
            project_id: The id of the project, which must belong to the
                organization your API key is scoped to.
            model_type: Which of the project's models to act on.
        """
        return self._api.request(
            HttpMethods.DELETE,
            Endpoints.PROJECT_MODEL_ENDPOINT,
            response_schema=ClearProjectModelResult,
            path={"projectId": project_id, "modelType": model_type},
        )

    async def a_delete_model(
        self, project_id: str, model_type: str
    ) -> ClearProjectModelResult:
        """Clear Project Model Override

        Removes the project's platform or simulation model override, so the
        project falls back to the organization's default for that type and the
        override toggle in its model settings shows as off. The evaluation model
        cannot be cleared, so the `evaluation` path segment is rejected.
        Idempotent: it succeeds even when no override exists.

        Args:
            project_id: The id of the project, which must belong to the
                organization your API key is scoped to.
            model_type: Which of the project's models to act on.
        """
        return await self._api.a_request(
            HttpMethods.DELETE,
            Endpoints.PROJECT_MODEL_ENDPOINT,
            response_schema=ClearProjectModelResult,
            path={"projectId": project_id, "modelType": model_type},
        )
