// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: widgets).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import {
  CreateWidgetRequest,
  WidgetData,
  WidgetGranularity,
  WidgetMode,
  WidgetType,
} from "../common/types";

export interface AdHocWidgetQueryRequest {
  widget: CreateWidgetRequest;
  startTime?: string;
  endTime?: string;
  granularity?: WidgetGranularity;
}

export interface AdHocWidgetQueryResult {
  type: WidgetType | null;
  mode: WidgetMode | null;
  data: WidgetData;
}
