// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: organization).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../../api";
import { Endpoints } from "../../../endpoints";
import { GovernancePoliciesOperations } from "../operations";
import { GovernancePolicyControlList } from "../../types";

export class GovernancePoliciesControlsOperations extends GovernancePoliciesOperations {
  /**
   * List Governance Policy Controls
   *
   * Lists every control the governance policy applies, with each control's
   * current definition and its latest verdict in each enrolled project.
   * Controls the policy inherits from the policies it extends are included and
   * carry a `baseGovernancePolicy` naming where they come from. A control your
   * organization owns but has not attached to this policy does not appear here
   * — creating a control does not attach it to anything.
   * `totalGovernancePolicyControls` is the length of the list; this response is
   * not paginated.
   *
   * @param policyId The id of the governance policy.
   */
  async listGovernancePolicyControls(
    policyId: string,
  ): Promise<GovernancePolicyControlList> {
    return this.api.sendRequest<GovernancePolicyControlList>(
      HttpMethods.GET,
      Endpoints.ORGANIZATION_GOVERNANCE_POLICY_CONTROLS_ENDPOINT,
      { urlParams: { policyId } },
    );
  }

  /**
   * Update Governance Policy Controls
   *
   * Replaces the set of controls the governance policy attaches directly,
   * changing what it gates its projects on from the next assessment onward.
   * This is how a control comes to govern anything: creating a control leaves
   * it attached to no policy, so it gates no project and is never assessed
   * until a policy attaches it here. `controlIds` is the complete set: anything
   * the policy currently attaches and you leave out is detached, and an empty
   * array detaches all of them. Every id must name a control in your
   * organization, or the whole request is rejected. An inherited control cannot
   * be listed here — it is attached on the base policy that owns it, and naming
   * it would silently turn an inherited control into a direct attachment.
   * Returns the policy's controls as they now stand, inherited ones included.
   *
   * @param policyId The id of the governance policy.
   * @param controlIds The complete set of controls the policy should attach
   *   directly. Any control it currently attaches and you leave out is
   *   detached, and an empty array detaches all of them. An inherited control
   *   cannot appear here — it is attached on the base policy that owns it.
   */
  async updateGovernancePolicyControls(
    policyId: string,
    controlIds: string[],
  ): Promise<GovernancePolicyControlList> {
    return this.api.sendRequest<GovernancePolicyControlList>(
      HttpMethods.PUT,
      Endpoints.ORGANIZATION_GOVERNANCE_POLICY_CONTROLS_ENDPOINT,
      { body: { controlIds }, urlParams: { policyId } },
    );
  }

  /**
   * Remove Governance Policy Controls
   *
   * Detaches the named controls from the governance policy, leaving its other
   * controls in place, so the policy stops gating its projects on them. The
   * controls themselves are not deleted and stay available to other policies,
   * and verdicts already recorded are kept. An inherited control cannot be
   * detached here: it is managed on the base policy that owns it, and the
   * request is rejected naming that policy rather than silently doing nothing.
   * Returns the policy's controls as they now stand.
   *
   * @param policyId The id of the governance policy.
   * @param controlIds The controls to detach from the policy. Send at least
   *   one. An inherited control cannot be detached here — it is managed on the
   *   base policy that owns it.
   */
  async removeGovernancePolicyControls(
    policyId: string,
    controlIds: string[],
  ): Promise<GovernancePolicyControlList> {
    return this.api.sendRequest<GovernancePolicyControlList>(
      HttpMethods.DELETE,
      Endpoints.ORGANIZATION_GOVERNANCE_POLICY_CONTROLS_ENDPOINT,
      { body: { controlIds }, urlParams: { policyId } },
    );
  }
}
