// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: projects).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { ProjectsOperations } from "../operations";
import {
  ApiKey,
  ApiKeyList,
  ApiKeyRef,
  CreatedApiKey,
  RotatedApiKey,
} from "../../common/types";

export class ApiKeysOperations extends ProjectsOperations {
  /**
   * List Project API Keys
   *
   * Lists every API key scoped to the project, newest first. Each key's `value`
   * is masked (only its last six characters are shown) — the full value is only
   * ever returned once, by the response that issues it. A rotation whose grace
   * period has already run out is completed before the list is read, so a
   * `shadowValue` here is always still in flight.
   *
   * @param projectId The id of the project the key belongs to.
   */
  async listApiKeys(projectId: string): Promise<ApiKeyList> {
    return this.api.sendRequest<ApiKeyList>(
      HttpMethods.GET,
      Endpoints.PROJECT_API_KEYS_ENDPOINT,
      { urlParams: { projectId } },
    );
  }

  /**
   * Create Project API Key
   *
   * Mints a new project-scoped API key. The full `value` is returned **exactly
   * once**, in this response, and can never be retrieved again — store it
   * securely. This is the key your application uses to send traces and run
   * evaluations against the project.
   *
   * @param projectId The id of the project the key belongs to.
   * @param name A label for the key, shown on the Confident AI platform.
   * @param expiresInDays How long the key lasts, in days from now — a duration,
   *   not a date. Confident AI turns it into the `expiresAt` instant on the
   *   key. Omit it for a key that never expires.
   */
  async createApiKey(
    projectId: string,
    name: string,
    expiresInDays?: number,
  ): Promise<CreatedApiKey> {
    return this.api.sendRequest<CreatedApiKey>(
      HttpMethods.POST,
      Endpoints.PROJECT_API_KEYS_ENDPOINT,
      { body: { name, expiresInDays }, urlParams: { projectId } },
    );
  }

  /**
   * Get Project API Key
   *
   * Retrieves one project-scoped API key by id. Its `value` is masked — the
   * full value is only ever returned once, by the response that issues it. A
   * `rotatesAt` in the past means the grace period is over and the outgoing
   * value is already rejected on authentication, even though this endpoint
   * still shows it; listing the keys completes the rotation.
   *
   * @param projectId The id of the project the key belongs to.
   * @param apiKeyId The id of the API key.
   */
  async getApiKey(projectId: string, apiKeyId: string): Promise<ApiKey> {
    return this.api.sendRequest<ApiKey>(
      HttpMethods.GET,
      Endpoints.PROJECT_API_KEY_ENDPOINT,
      { urlParams: { projectId, apiKeyId } },
    );
  }

  /**
   * Update Project API Key
   *
   * Activates or deactivates a project-scoped API key. A deactivated key is
   * rejected on authentication from the next request onwards, so anything still
   * sending traces with it starts failing; its value is unchanged and
   * reactivating it brings the same value back. Rotating is the only way to
   * change the value.
   *
   * @param projectId The id of the project the key belongs to.
   * @param apiKeyId The id of the API key.
   * @param valid Send false to deactivate the key, true to reactivate it. A
   *   deactivated key is rejected on every request, and deactivating one takes
   *   effect immediately.
   */
  async updateApiKey(
    projectId: string,
    apiKeyId: string,
    valid: boolean,
  ): Promise<ApiKey> {
    return this.api.sendRequest<ApiKey>(
      HttpMethods.PUT,
      Endpoints.PROJECT_API_KEY_ENDPOINT,
      { body: { valid }, urlParams: { projectId, apiKeyId } },
    );
  }

  /**
   * Revoke Project API Key
   *
   * Permanently revokes a project-scoped API key. Both its current value and
   * any replacement value in flight stop authenticating at once, so anything
   * still sending traces with it starts failing. This cannot be undone — a new
   * key has to be created in its place.
   *
   * @param projectId The id of the project the key belongs to.
   * @param apiKeyId The id of the API key.
   */
  async deleteApiKey(projectId: string, apiKeyId: string): Promise<ApiKeyRef> {
    return this.api.sendRequest<ApiKeyRef>(
      HttpMethods.DELETE,
      Endpoints.PROJECT_API_KEY_ENDPOINT,
      { urlParams: { projectId, apiKeyId } },
    );
  }

  /**
   * Rotate Project API Key
   *
   * Rotates a project-scoped API key in place — the key keeps its id, name and
   * history, and no second key is created. The new value is returned **exactly
   * once**, in this response, and can never be retrieved again — store it
   * securely. With `gracePeriodInHours: 0` (the default) the key's `value` is
   * replaced as this request is served and the outgoing value stops
   * authenticating at once, so anything still sending traces with it starts
   * failing. With a grace period, the new value comes back as `shadowValue` and
   * both values authenticate until `rotatesAt`, which is the window to
   * redeploy; after it the new value becomes `value` and the outgoing one is
   * rejected. Requests made with the outgoing value in the meantime carry
   * `Sunset` and `X-Api-Key-Warning` headers announcing when it stops working.
   * The key's expiry is left alone unless `expiresInDays` is sent. Rotating an
   * **expired** key revives it: `expiresInDays` is then required (send null for
   * no expiry) and a grace period is not allowed. A rotation whose grace period
   * has already run out is completed before this one starts.
   *
   * @param projectId The id of the project the key belongs to.
   * @param apiKeyId The id of the API key.
   * @param gracePeriodInHours How long the current value keeps authenticating
   *   alongside the new one, in hours from now — a duration, not a date, stored
   *   on the key as `rotatesAt` and never set past `expiresAt`. Defaults to 0,
   *   which replaces the value immediately and stops the old one at once.
   * @param expiresInDays A new lifetime for the key, in days from now — a
   *   duration, not a date, stored on the key as `expiresAt`. Omit it to keep
   *   the current expiry, or send null to remove the expiry altogether.
   *   Required when rotating a key that has already expired.
   */
  async rotateApiKey(
    projectId: string,
    apiKeyId: string,
    gracePeriodInHours?: number,
    expiresInDays?: number | null,
  ): Promise<RotatedApiKey> {
    return this.api.sendRequest<RotatedApiKey>(
      HttpMethods.POST,
      Endpoints.PROJECT_API_KEY_ROTATE_ENDPOINT,
      {
        body: { gracePeriodInHours, expiresInDays },
        urlParams: { projectId, apiKeyId },
      },
    );
  }
}
