# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: organization).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Optional

from confident_ai.api import Api, HttpMethods
from confident_ai.endpoints import Endpoints
from confident_ai.organization.types import (
    GovernanceProject,
    GovernanceProjectList,
    GovernanceProjectStatus,
)


class GovernanceProjectsOperations:
    _api: Api

    def list_governance_projects(
        self,
        *,
        status: Optional[GovernanceProjectStatus] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None
    ) -> GovernanceProjectList:
        """List Projects

        Lists every project in your organization with its governance standing,
        ordered by project name, alongside an organization-wide roll-up of how
        many projects fall into each status. Projects enrolled in no governance
        policy are included, with a `status` of `not_enrolled` and a `null`
        `health`, since the inventory is what tells you which projects are
        ungoverned.

        Args:
            status: Only return projects with this status. The
                `governanceProjectPortfolio` roll-up always covers the whole
                organization and is not narrowed by this filter.
            page: The page to return. Defaults to 1.
            page_size: The number of projects per page, at most 100. Defaults to
                25.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_PROJECTS_ENDPOINT,
            response_schema=GovernanceProjectList,
            query={"status": status, "page": page, "pageSize": page_size},
        )

    async def a_list_governance_projects(
        self,
        *,
        status: Optional[GovernanceProjectStatus] = None,
        page: Optional[int] = None,
        page_size: Optional[int] = None
    ) -> GovernanceProjectList:
        """List Projects

        Lists every project in your organization with its governance standing,
        ordered by project name, alongside an organization-wide roll-up of how
        many projects fall into each status. Projects enrolled in no governance
        policy are included, with a `status` of `not_enrolled` and a `null`
        `health`, since the inventory is what tells you which projects are
        ungoverned.

        Args:
            status: Only return projects with this status. The
                `governanceProjectPortfolio` roll-up always covers the whole
                organization and is not narrowed by this filter.
            page: The page to return. Defaults to 1.
            page_size: The number of projects per page, at most 100. Defaults to
                25.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_PROJECTS_ENDPOINT,
            response_schema=GovernanceProjectList,
            query={"status": status, "page": page, "pageSize": page_size},
        )

    def get_governance_project(self, project_id: str) -> GovernanceProject:
        """Get Project

        Retrieves one project's governance view in full: every control its
        policy applies, inherited ones included, together with its recent
        verdict history. A project enrolled in no policy is reported as not
        found, so use the inventory listing to tell an ungoverned project from
        one that does not exist.

        Args:
            project_id: The id of the project.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_PROJECT_ENDPOINT,
            response_schema=GovernanceProject,
            path={"projectId": project_id},
        )

    async def a_get_governance_project(
        self, project_id: str
    ) -> GovernanceProject:
        """Get Project

        Retrieves one project's governance view in full: every control its
        policy applies, inherited ones included, together with its recent
        verdict history. A project enrolled in no policy is reported as not
        found, so use the inventory listing to tell an ungoverned project from
        one that does not exist.

        Args:
            project_id: The id of the project.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ORGANIZATION_GOVERNANCE_PROJECT_ENDPOINT,
            response_schema=GovernanceProject,
            path={"projectId": project_id},
        )
