# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: prompts).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Optional

from confidentai.api import Api, HttpMethods
from confidentai.endpoints import Endpoints
from confidentai.prompts.types import Prompt, PromptCommitList


class CommitsOperations:
    _api: Api

    def get_prompt_commits(
        self, prompt_id: str, *, branch: Optional[str] = None
    ) -> PromptCommitList:
        """List Prompt Commits

        Lists the commits of the prompt, newest first. Pass `branch` to list
        only the commits reachable from that branch.

        Args:
            prompt_id: The unique id of the prompt.
            branch: The name of the branch to read from. Defaults to `main` when
                omitted.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.PROMPT_COMMITS_ENDPOINT,
            response_schema=PromptCommitList,
            path={"promptId": prompt_id},
            query={"branch": branch},
        )

    async def a_get_prompt_commits(
        self, prompt_id: str, *, branch: Optional[str] = None
    ) -> PromptCommitList:
        """List Prompt Commits

        Lists the commits of the prompt, newest first. Pass `branch` to list
        only the commits reachable from that branch.

        Args:
            prompt_id: The unique id of the prompt.
            branch: The name of the branch to read from. Defaults to `main` when
                omitted.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.PROMPT_COMMITS_ENDPOINT,
            response_schema=PromptCommitList,
            path={"promptId": prompt_id},
            query={"branch": branch},
        )

    def get_prompt_by_commit(
        self, prompt_id: str, hash: str, *, branch: Optional[str] = None
    ) -> Prompt:
        """Pull Prompt by Commit

        Retrieves the prompt commit with the given `hash`. The commit is looked
        up on `main` unless a `branch` is given.

        Args:
            prompt_id: The unique id of the prompt.
            hash: The hash of the commit to pull.
            branch: The name of the branch to read from. Defaults to `main` when
                omitted.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.PROMPT_COMMIT_ENDPOINT,
            response_schema=Prompt,
            path={"promptId": prompt_id, "hash": hash},
            query={"branch": branch},
        )

    async def a_get_prompt_by_commit(
        self, prompt_id: str, hash: str, *, branch: Optional[str] = None
    ) -> Prompt:
        """Pull Prompt by Commit

        Retrieves the prompt commit with the given `hash`. The commit is looked
        up on `main` unless a `branch` is given.

        Args:
            prompt_id: The unique id of the prompt.
            hash: The hash of the commit to pull.
            branch: The name of the branch to read from. Defaults to `main` when
                omitted.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.PROMPT_COMMIT_ENDPOINT,
            response_schema=Prompt,
            path={"promptId": prompt_id, "hash": hash},
            query={"branch": branch},
        )
