// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: rt-frameworks).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { RiskCategoriesOperations } from "./risk-categories/operations";

export class RTFrameworksClient extends RiskCategoriesOperations {}
