// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: rt-frameworks).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { GenerationMode, Level } from "../common/types";

export interface AttackEngine {
  generationGuidelines?: string[];
}

export interface CreateRTFrameworkRequest {
  name: string;
  description?: string | null;
  template?: string;
}

export interface CreateRiskCategoryRequest {
  name: string;
  description?: string | null;
  vulnerabilityTypeIds?: string[];
  attackMethodIds?: string[];
  vulnerabilityIdToPriorityLevel?: Record<string, number> | null;
}

export interface FrameworkAttackMethod {
  name: string;
  multiTurn: boolean;
  parameters: Record<string, unknown> | null;
}

export interface FrameworkVulnerabilityEvaluationExample {
  input: string;
  actualOutput: string;
  score: number;
  reason: string;
}

export interface FrameworkVulnerability {
  name: string;
  types: string[];
  criteria: string | null;
  evaluationGuidelines: string[];
  evaluationExamples: FrameworkVulnerabilityEvaluationExample[] | null;
}

export interface FrameworkRiskCategory {
  id: string;
  name: string;
  description: string | null;
  vulnerabilities: FrameworkVulnerability[];
  attackMethods: FrameworkAttackMethod[];
}

export interface FrameworkRiskCategorySummary {
  name: string;
  numVulnerabilityTypes: number;
  numAttackMethods: number;
}

export interface RTFramework {
  id: string;
  name: string;
  description: string | null;
  riskCategories: FrameworkRiskCategory[];
}

export interface RTFrameworkSummary {
  id: string;
  name: string;
  description: string | null;
  riskCategories: FrameworkRiskCategorySummary[];
}

export interface RTFrameworkList {
  rtFrameworks: RTFrameworkSummary[];
  totalRTFrameworks: number;
  page: number;
  pageSize: number;
}

export interface RTFrameworkRef {
  id: string;
}

export interface RiskAssessmentRef {
  id: string;
}

export interface RiskCategoryVulnerabilityType {
  id: string;
  name: string;
  vulnerabilityId: string;
  vulnerabilityName: string;
}

export interface RiskCategoryAttackMethod {
  id: string;
  name: string;
  multiTurn: boolean;
}

export interface RiskCategory {
  id: string;
  name: string;
  description: string | null;
  vulnerabilityTypes: RiskCategoryVulnerabilityType[];
  attackMethods: RiskCategoryAttackMethod[];
  vulnerabilityIdToPriorityLevel: Record<string, number>;
}

export interface RiskCategorySummary {
  id: string;
  name: string;
  description: string | null;
  numVulnerabilityTypes: number;
  numAttackMethods: number;
}

export interface RiskCategoryList {
  riskCategories: RiskCategorySummary[];
  totalRiskCategories: number;
  page: number;
  pageSize: number;
}

export interface RiskCategoryRef {
  id: string;
}

export interface RunRTFrameworkRequest {
  identifier?: string;
  riskCategories: string[];
  exposure: Level;
  aiConnectionId?: string;
  promptAlias?: string;
  promptCommit?: string;
  generationMode?: GenerationMode;
  attackEngine?: AttackEngine;
}

export interface UpdateRTFrameworkRequest {
  name?: string;
  description?: string | null;
}

export interface UpdateRiskCategoryRequest {
  name?: string;
  description?: string | null;
  vulnerabilityTypeIds?: string[];
  attackMethodIds?: string[];
  vulnerabilityIdToPriorityLevel?: Record<string, number> | null;
}
