# @generated by scripts/generate_sdk.py from
# packages/shared/openapi/openapi.yml (tag: annotations).
# Do not edit by hand — change the route in confident-cloud
# and regenerate.

from typing import Dict, Literal, Optional

from confidentai.annotations.types import (
    Annotation,
    AnnotationList,
    AnnotationRef,
    AnnotationSortBy,
    CreateAnnotationRequest,
    UpdateAnnotationRequest,
)
from confidentai.api import Api, HttpMethods
from confidentai.common.types import AnnotationType, MLLMImage
from confidentai.endpoints import Endpoints


class AnnotationsClient:
    def __init__(self, api: Api) -> None:
        self._api = api

    def list(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        sort_by: Optional[AnnotationSortBy] = None,
        ascending: Optional[Literal["true", "false"]] = None,
        trace_uuid: Optional[str] = None,
        span_uuid: Optional[str] = None,
        thread_id: Optional[str] = None,
        type: Optional[AnnotationType] = None
    ) -> AnnotationList:
        """List Annotations

        Lists the annotations in your Confident AI project one page at a time,
        newest first by default. Filter by the trace, span or thread they were
        left on, by rating scale, and by time window.

        Args:
            page: The page of annotations to return. Defaults to 1.
            page_size: The number of annotations per page, at most 100. Defaults
                to 25.
            start: Returns only annotations left at or after this ISO 8601
                datetime. Defaults to 60 days ago.
            end: Returns only annotations left before this ISO 8601 datetime.
                Defaults to the current time.
            sort_by: This determines the field to sort by. Defaults to
                `createdAt`.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`, which returns the
                newest annotations first.
            trace_uuid: Returns only annotations left on this trace.
            span_uuid: Returns only annotations left on this span.
            thread_id: Returns only annotations left on this thread.
            type: Returns only annotations recorded on this scale.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ANNOTATIONS_ENDPOINT,
            response_schema=AnnotationList,
            query={
                "page": page,
                "pageSize": page_size,
                "start": start,
                "end": end,
                "sortBy": sort_by,
                "ascending": ascending,
                "traceUuid": trace_uuid,
                "spanUuid": span_uuid,
                "threadId": thread_id,
                "type": type,
            },
        )

    async def a_list(
        self,
        *,
        page: Optional[int] = None,
        page_size: Optional[int] = None,
        start: Optional[str] = None,
        end: Optional[str] = None,
        sort_by: Optional[AnnotationSortBy] = None,
        ascending: Optional[Literal["true", "false"]] = None,
        trace_uuid: Optional[str] = None,
        span_uuid: Optional[str] = None,
        thread_id: Optional[str] = None,
        type: Optional[AnnotationType] = None
    ) -> AnnotationList:
        """List Annotations

        Lists the annotations in your Confident AI project one page at a time,
        newest first by default. Filter by the trace, span or thread they were
        left on, by rating scale, and by time window.

        Args:
            page: The page of annotations to return. Defaults to 1.
            page_size: The number of annotations per page, at most 100. Defaults
                to 25.
            start: Returns only annotations left at or after this ISO 8601
                datetime. Defaults to 60 days ago.
            end: Returns only annotations left before this ISO 8601 datetime.
                Defaults to the current time.
            sort_by: This determines the field to sort by. Defaults to
                `createdAt`.
            ascending: This determines if the field specified in `sortBy` should
                be in ascending order. Defaults to `false`, which returns the
                newest annotations first.
            trace_uuid: Returns only annotations left on this trace.
            span_uuid: Returns only annotations left on this span.
            thread_id: Returns only annotations left on this thread.
            type: Returns only annotations recorded on this scale.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ANNOTATIONS_ENDPOINT,
            response_schema=AnnotationList,
            query={
                "page": page,
                "pageSize": page_size,
                "start": start,
                "end": end,
                "sortBy": sort_by,
                "ascending": ascending,
                "traceUuid": trace_uuid,
                "spanUuid": span_uuid,
                "threadId": thread_id,
                "type": type,
            },
        )

    def create(self, annotation: CreateAnnotationRequest) -> AnnotationRef:
        """Create Annotation

        Records a rating against exactly one trace, span or thread, and returns
        its id. The target must already exist in your project. A rating on a
        THUMBS_RATING scale is 0 or 1; on a FIVE_STAR_RATING scale it is 1 to 5.

        Args:
            annotation: A rating to record against exactly one target. Send
                `traceUuid`, `spanUuid` or `threadId` — never more than one —
                and the field that goes with it: `expectedOutput` for a trace or
                span, `expectedOutcome` for a thread. `type` defaults to
                THUMBS_RATING. Pass one of TraceAnnotationRequest,
                SpanAnnotationRequest, ThreadAnnotationRequest, from
                confidentai.annotations.types.
        """
        return self._api.request(
            HttpMethods.POST,
            Endpoints.ANNOTATIONS_ENDPOINT,
            response_schema=AnnotationRef,
            request_schema=CreateAnnotationRequest,
            body=annotation,
        )

    async def a_create(
        self, annotation: CreateAnnotationRequest
    ) -> AnnotationRef:
        """Create Annotation

        Records a rating against exactly one trace, span or thread, and returns
        its id. The target must already exist in your project. A rating on a
        THUMBS_RATING scale is 0 or 1; on a FIVE_STAR_RATING scale it is 1 to 5.

        Args:
            annotation: A rating to record against exactly one target. Send
                `traceUuid`, `spanUuid` or `threadId` — never more than one —
                and the field that goes with it: `expectedOutput` for a trace or
                span, `expectedOutcome` for a thread. `type` defaults to
                THUMBS_RATING. Pass one of TraceAnnotationRequest,
                SpanAnnotationRequest, ThreadAnnotationRequest, from
                confidentai.annotations.types.
        """
        return await self._api.a_request(
            HttpMethods.POST,
            Endpoints.ANNOTATIONS_ENDPOINT,
            response_schema=AnnotationRef,
            request_schema=CreateAnnotationRequest,
            body=annotation,
        )

    def get(self, annotation_id: str) -> Annotation:
        """Get Annotation

        Retrieves an annotation by id from your Confident AI project, with the
        ids of the trace, span or thread it was left on and the team member who
        left it.

        Args:
            annotation_id: The id of the annotation.
        """
        return self._api.request(
            HttpMethods.GET,
            Endpoints.ANNOTATION_ENDPOINT,
            response_schema=Annotation,
            path={"annotationId": annotation_id},
        )

    async def a_get(self, annotation_id: str) -> Annotation:
        """Get Annotation

        Retrieves an annotation by id from your Confident AI project, with the
        ids of the trace, span or thread it was left on and the team member who
        left it.

        Args:
            annotation_id: The id of the annotation.
        """
        return await self._api.a_request(
            HttpMethods.GET,
            Endpoints.ANNOTATION_ENDPOINT,
            response_schema=Annotation,
            path={"annotationId": annotation_id},
        )

    def update(
        self,
        annotation_id: str,
        *,
        rating: Optional[int] = None,
        type: Optional[AnnotationType] = None,
        explanation: Optional[str] = None,
        expected_output: Optional[str] = None,
        expected_outcome: Optional[str] = None,
        images_mapping: Optional[Dict[str, MLLMImage]] = None
    ) -> AnnotationRef:
        """Update Annotation

        Updates the rating, scale or text of an annotation and returns its id.
        The target it was left on cannot be changed: `expectedOutput` is
        rejected on a thread annotation, and `expectedOutcome` on a trace or
        span annotation.

        Args:
            annotation_id: The id of the annotation.
            rating: The rating to record: 0 or 1 for a THUMBS_RATING, 1 to 5 for
                a FIVE_STAR_RATING.
            explanation: Why the rating was given.
            expected_output: The output the target should have produced. Only
                for an annotation left on a trace or span.
            expected_outcome: The outcome the conversation should have reached.
                Only for an annotation left on a thread.
            images_mapping: Images referenced by `[DEEPEVAL:IMAGE:<key>]`
                markers in the text fields, keyed by that marker's key.
        """
        return self._api.request(
            HttpMethods.PUT,
            Endpoints.ANNOTATION_ENDPOINT,
            response_schema=AnnotationRef,
            request_schema=UpdateAnnotationRequest,
            body={
                "rating": rating,
                "type": type,
                "explanation": explanation,
                "expectedOutput": expected_output,
                "expectedOutcome": expected_outcome,
                "imagesMapping": images_mapping,
            },
            path={"annotationId": annotation_id},
        )

    async def a_update(
        self,
        annotation_id: str,
        *,
        rating: Optional[int] = None,
        type: Optional[AnnotationType] = None,
        explanation: Optional[str] = None,
        expected_output: Optional[str] = None,
        expected_outcome: Optional[str] = None,
        images_mapping: Optional[Dict[str, MLLMImage]] = None
    ) -> AnnotationRef:
        """Update Annotation

        Updates the rating, scale or text of an annotation and returns its id.
        The target it was left on cannot be changed: `expectedOutput` is
        rejected on a thread annotation, and `expectedOutcome` on a trace or
        span annotation.

        Args:
            annotation_id: The id of the annotation.
            rating: The rating to record: 0 or 1 for a THUMBS_RATING, 1 to 5 for
                a FIVE_STAR_RATING.
            explanation: Why the rating was given.
            expected_output: The output the target should have produced. Only
                for an annotation left on a trace or span.
            expected_outcome: The outcome the conversation should have reached.
                Only for an annotation left on a thread.
            images_mapping: Images referenced by `[DEEPEVAL:IMAGE:<key>]`
                markers in the text fields, keyed by that marker's key.
        """
        return await self._api.a_request(
            HttpMethods.PUT,
            Endpoints.ANNOTATION_ENDPOINT,
            response_schema=AnnotationRef,
            request_schema=UpdateAnnotationRequest,
            body={
                "rating": rating,
                "type": type,
                "explanation": explanation,
                "expectedOutput": expected_output,
                "expectedOutcome": expected_outcome,
                "imagesMapping": images_mapping,
            },
            path={"annotationId": annotation_id},
        )
