// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: rt-frameworks).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { HttpMethods } from "../../api";
import { Endpoints } from "../../endpoints";
import { RTFrameworksOperations } from "../operations";
import { RiskCategory, RiskCategoryList, RiskCategoryRef } from "../types";

export class RiskCategoriesOperations extends RTFrameworksOperations {
  /**
   * List Risk Categories
   *
   * Lists the risk categories of a red teaming framework one page at a time,
   * ordered by name. Each is returned with its selections counted; retrieve one
   * by id to see which vulnerability types and attack methods it holds.
   *
   * @param rtFrameworkId The id of the red teaming framework.
   * @param page The page to return. Defaults to 1.
   * @param pageSize The number of results per page, at most 100. Defaults to
   *   25.
   */
  async listRiskCategories(
    rtFrameworkId: string,
    page?: number,
    pageSize?: number,
  ): Promise<RiskCategoryList> {
    return this.api.sendRequest<RiskCategoryList>(
      HttpMethods.GET,
      Endpoints.RT_FRAMEWORK_RISK_CATEGORIES_ENDPOINT,
      { urlParams: { rtFrameworkId }, params: { page, pageSize } },
    );
  }

  /**
   * Create Risk Category
   *
   * Adds a risk category to a red teaming framework and returns its id. Send
   * `vulnerabilityTypeIds` and `attackMethodIds` to fill it in the same call: a
   * category with neither probes for nothing when the framework runs.
   *
   * @param rtFrameworkId The id of the red teaming framework.
   * @param name The name of the risk category, unique within the framework.
   * @param description What this risk category covers. Send null to clear it.
   * @param vulnerabilityTypeIds The ids of the vulnerability types to probe
   *   for. The list replaces the category's current selection.
   * @param attackMethodIds The ids of the attack methods to probe with. The
   *   list replaces the category's current selection.
   * @param vulnerabilityIdToPriorityLevel How much of the assessment each
   *   vulnerability gets, keyed by vulnerability id, from 0 to 3. Send null to
   *   clear every weight.
   */
  async createRiskCategory(
    rtFrameworkId: string,
    name: string,
    options: {
      description?: string | null;
      vulnerabilityTypeIds?: string[];
      attackMethodIds?: string[];
      vulnerabilityIdToPriorityLevel?: Record<string, number> | null;
    } = {},
  ): Promise<RiskCategoryRef> {
    const {
      description,
      vulnerabilityTypeIds,
      attackMethodIds,
      vulnerabilityIdToPriorityLevel,
    } = options;
    return this.api.sendRequest<RiskCategoryRef>(
      HttpMethods.POST,
      Endpoints.RT_FRAMEWORK_RISK_CATEGORIES_ENDPOINT,
      {
        body: {
          name,
          description,
          vulnerabilityTypeIds,
          attackMethodIds,
          vulnerabilityIdToPriorityLevel,
        },
        urlParams: { rtFrameworkId },
      },
    );
  }

  /**
   * Get Risk Category
   *
   * Retrieves a risk category by id, with the vulnerability types it probes
   * for, the attack methods it probes with, and how much of an assessment each
   * vulnerability gets.
   *
   * @param rtFrameworkId The id of the red teaming framework the category
   *   belongs to.
   * @param riskCategoryId The id of the risk category.
   */
  async getRiskCategory(
    rtFrameworkId: string,
    riskCategoryId: string,
  ): Promise<RiskCategory> {
    return this.api.sendRequest<RiskCategory>(
      HttpMethods.GET,
      Endpoints.RT_FRAMEWORK_RISK_CATEGORY_ENDPOINT,
      { urlParams: { rtFrameworkId, riskCategoryId } },
    );
  }

  /**
   * Update Risk Category
   *
   * Updates a risk category and returns it. Each list you send replaces the
   * stored selection rather than adding to it, so send the complete set of
   * vulnerability type ids or attack method ids you want the category to hold.
   *
   * @param rtFrameworkId The id of the red teaming framework the category
   *   belongs to.
   * @param riskCategoryId The id of the risk category.
   * @param name The name of the risk category, unique within the framework.
   * @param description What this risk category covers. Send null to clear it.
   * @param vulnerabilityTypeIds The ids of the vulnerability types to probe
   *   for. The list replaces the category's current selection.
   * @param attackMethodIds The ids of the attack methods to probe with. The
   *   list replaces the category's current selection.
   * @param vulnerabilityIdToPriorityLevel How much of the assessment each
   *   vulnerability gets, keyed by vulnerability id, from 0 to 3. Send null to
   *   clear every weight.
   */
  async updateRiskCategory(
    rtFrameworkId: string,
    riskCategoryId: string,
    options: {
      name?: string;
      description?: string | null;
      vulnerabilityTypeIds?: string[];
      attackMethodIds?: string[];
      vulnerabilityIdToPriorityLevel?: Record<string, number> | null;
    } = {},
  ): Promise<RiskCategory> {
    const {
      name,
      description,
      vulnerabilityTypeIds,
      attackMethodIds,
      vulnerabilityIdToPriorityLevel,
    } = options;
    return this.api.sendRequest<RiskCategory>(
      HttpMethods.PUT,
      Endpoints.RT_FRAMEWORK_RISK_CATEGORY_ENDPOINT,
      {
        body: {
          name,
          description,
          vulnerabilityTypeIds,
          attackMethodIds,
          vulnerabilityIdToPriorityLevel,
        },
        urlParams: { rtFrameworkId, riskCategoryId },
      },
    );
  }

  /**
   * Delete Risk Category
   *
   * Permanently deletes a risk category from its framework, along with the
   * selections and weights it held. The vulnerabilities and attack methods
   * themselves are untouched.
   *
   * @param rtFrameworkId The id of the red teaming framework the category
   *   belongs to.
   * @param riskCategoryId The id of the risk category.
   */
  async deleteRiskCategory(
    rtFrameworkId: string,
    riskCategoryId: string,
  ): Promise<RiskCategoryRef> {
    return this.api.sendRequest<RiskCategoryRef>(
      HttpMethods.DELETE,
      Endpoints.RT_FRAMEWORK_RISK_CATEGORY_ENDPOINT,
      { urlParams: { rtFrameworkId, riskCategoryId } },
    );
  }
}
