// @generated by scripts/generate_sdk.py from
// packages/shared/openapi/openapi.yml (tag: annotations).
// Do not edit by hand — change the route in confident-cloud
// and regenerate.

import { Api, HttpMethods } from "../api";
import { Endpoints } from "../endpoints";
import { AnnotationType, MLLMImage } from "../common/types";
import {
  Annotation,
  AnnotationList,
  AnnotationRef,
  AnnotationSortBy,
  CreateAnnotationRequest,
} from "./types";

export class AnnotationsClient {
  constructor(protected readonly api: Api) {}

  /**
   * List Annotations
   *
   * Lists the annotations in your Confident AI project one page at a time,
   * newest first by default. Filter by the trace, span or thread they were left
   * on, by rating scale, and by time window.
   *
   * @param page The page of annotations to return. Defaults to 1.
   * @param pageSize The number of annotations per page, at most 100. Defaults
   *   to 25.
   * @param start Returns only annotations left at or after this ISO 8601
   *   datetime. Defaults to 60 days ago.
   * @param end Returns only annotations left before this ISO 8601 datetime.
   *   Defaults to the current time.
   * @param sortBy This determines the field to sort by. Defaults to
   *   `createdAt`.
   * @param ascending This determines if the field specified in `sortBy` should
   *   be in ascending order. Defaults to `false`, which returns the newest
   *   annotations first.
   * @param traceUuid Returns only annotations left on this trace.
   * @param spanUuid Returns only annotations left on this span.
   * @param threadId Returns only annotations left on this thread.
   * @param type Returns only annotations recorded on this scale.
   */
  async list(
    page?: number,
    pageSize?: number,
    start?: string,
    end?: string,
    sortBy?: AnnotationSortBy,
    ascending?: "true" | "false",
    traceUuid?: string,
    spanUuid?: string,
    threadId?: string,
    type?: AnnotationType,
  ): Promise<AnnotationList> {
    return this.api.sendRequest<AnnotationList>(
      HttpMethods.GET,
      Endpoints.ANNOTATIONS_ENDPOINT,
      {
        params: {
          page,
          pageSize,
          start,
          end,
          sortBy,
          ascending,
          traceUuid,
          spanUuid,
          threadId,
          type,
        },
      },
    );
  }

  /**
   * Create Annotation
   *
   * Records a rating against exactly one trace, span or thread, and returns its
   * id. The target must already exist in your project. A rating on a
   * THUMBS_RATING scale is 0 or 1; on a FIVE_STAR_RATING scale it is 1 to 5.
   *
   * @param annotation A rating to record against exactly one target. Send
   *   `traceUuid`, `spanUuid` or `threadId` — never more than one — and the
   *   field that goes with it: `expectedOutput` for a trace or span,
   *   `expectedOutcome` for a thread. `type` defaults to THUMBS_RATING. Pass
   *   one of TraceAnnotationRequest, SpanAnnotationRequest,
   *   ThreadAnnotationRequest, from confidentai.annotations.types.
   */
  async create(annotation: CreateAnnotationRequest): Promise<AnnotationRef> {
    return this.api.sendRequest<AnnotationRef>(
      HttpMethods.POST,
      Endpoints.ANNOTATIONS_ENDPOINT,
      { body: annotation },
    );
  }

  /**
   * Get Annotation
   *
   * Retrieves an annotation by id from your Confident AI project, with the ids
   * of the trace, span or thread it was left on and the team member who left
   * it.
   *
   * @param annotationId The id of the annotation.
   */
  async get(annotationId: string): Promise<Annotation> {
    return this.api.sendRequest<Annotation>(
      HttpMethods.GET,
      Endpoints.ANNOTATION_ENDPOINT,
      { urlParams: { annotationId } },
    );
  }

  /**
   * Update Annotation
   *
   * Updates the rating, scale or text of an annotation and returns its id. The
   * target it was left on cannot be changed: `expectedOutput` is rejected on a
   * thread annotation, and `expectedOutcome` on a trace or span annotation.
   *
   * @param annotationId The id of the annotation.
   * @param rating The rating to record: 0 or 1 for a THUMBS_RATING, 1 to 5 for
   *   a FIVE_STAR_RATING.
   * @param explanation Why the rating was given.
   * @param expectedOutput The output the target should have produced. Only for
   *   an annotation left on a trace or span.
   * @param expectedOutcome The outcome the conversation should have reached.
   *   Only for an annotation left on a thread.
   * @param imagesMapping Images referenced by `[DEEPEVAL:IMAGE:<key>]` markers
   *   in the text fields, keyed by that marker's key.
   */
  async update(
    annotationId: string,
    rating?: number,
    type?: AnnotationType,
    explanation?: string,
    expectedOutput?: string,
    expectedOutcome?: string,
    imagesMapping?: Record<string, MLLMImage>,
  ): Promise<AnnotationRef> {
    return this.api.sendRequest<AnnotationRef>(
      HttpMethods.PUT,
      Endpoints.ANNOTATION_ENDPOINT,
      {
        body: {
          rating,
          type,
          explanation,
          expectedOutput,
          expectedOutcome,
          imagesMapping,
        },
        urlParams: { annotationId },
      },
    );
  }
}
